const $=id=>document.getElementById(id);
let jobs=[],selected=null,frame=0,page=0,lastVideo='',cardSignature='',loadedJob='',sourceInfo=null,uploadedName='',uploadedPath='',busy=false;
let jobsSignature='',exportsSignature='',videoOptionsSignature='',activeVideo=null,jobEventSignature='',videoEventSignature='',loadingVideo=false;
const versionLists=new Map(),viewStateKey='animation-workbench:job-view:v1';
let jobViews={};
try{jobViews=JSON.parse(localStorage.getItem(viewStateKey)||'{}');if(!jobViews||typeof jobViews!=='object'||Array.isArray(jobViews))jobViews={}}catch{}
function viewState(id=selected){return jobViews[id]||(jobViews[id]={frame:1,version:'',videoTimes:{}})}
function saveViews(){clearTimeout(saveViews.timer);saveViews.timer=setTimeout(()=>{try{localStorage.setItem(viewStateKey,JSON.stringify(jobViews))}catch{}},300)}
function saveVideoPosition(){if(!activeVideo||loadingVideo)return;const time=$('video').currentTime;if(Number.isFinite(time)){const state=viewState(activeVideo.jobId);state.videoTimes=state.videoTimes||{};state.videoTimes[activeVideo.kind]=time;saveViews()}}
function emitFrame(source){window.dispatchEvent(new CustomEvent('workbench:frame',{detail:{frame:frame+1,source}}))}
function playbackVisible(){return $('tabPlayback')?.getAttribute('aria-selected')==='true'}
function framesVisible(){return $('tabFrames')?.getAttribute('aria-selected')==='true'}
function selectJob(id){if(id===selected)return;saveVideoPosition();selected=id;loadedJob='';cardSignature='';render()}
const stateNames={ready:'待開始',running:'處理中',paused:'已暫停',review:'待確認',complete:'已完成',attention:'需檢查'};
const frameNames={done:'完成',pending:'等待',running:'處理中',submitting:'提交中',failed:'失敗'};
function current(){return jobs.find(j=>j.id===selected)}
function notice(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('toast').hidden=true,9000)}
async function api(path,data){let r;try{r=await fetch('/api/'+path,data===undefined?{cache:'no-store'}:{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-Token':window.APP_TOKEN},body:JSON.stringify(data)})}catch(error){if(error.name==='AbortError')throw error;throw Error('無法連線到工作台。請重新執行「啟動工具」，再重新整理頁面；這不代表素材檔案損壞。')}const v=await r.json();if(!r.ok)throw Error(v.error);return v}
function file(j,p){return '/file/'+j.id+'/'+p.split('/').map(encodeURIComponent).join('/')}
function path(j,k){return j.paths?.[k]||{frames:'frames',png:'rgba',cache:'candidates',output:'exports'}[k]}
function image(el,empty,url){if(el.getAttribute('src')!==url){el.style.visibility='hidden';empty.hidden=false;el.onload=()=>{el.style.visibility='visible';empty.hidden=true;resizeStillImages()};el.onerror=()=>{el.style.visibility='hidden';empty.hidden=false;empty.textContent='圖片尚未產生或已移出資料夾'};el.src=url}}
function showFrame(j){
 const f=j?.frames[frame],count=j?.frames.length||0;
 ['prevFrame','nextFrame','jumpGo','scrub'].forEach(id=>$(id).disabled=!count);$('prevFrame').disabled=!count||frame===0;$('nextFrame').disabled=!count||frame>=count-1;$('jump').max=$('scrub').max=count||1;
 if(!f){for(const id of ['original','result','compareOriginal','compareResult']){$(id).removeAttribute('src');$(id).style.visibility='hidden'}for(const id of ['originalEmpty','resultEmpty','compareEmpty']){$(id).hidden=false;$(id).textContent='尚未拆幀'}$('frameLabel').textContent='透明 PNG';$('warnings').textContent='';return}
 image($('original'),$('originalEmpty'),file(j,path(j,'frames')+'/'+f.file));if(f.status==='done')image($('result'),$('resultEmpty'),file(j,path(j,'png')+'/'+f.file)+'?v='+(f.seconds||0));else{$('result').removeAttribute('src');$('result').style.visibility='hidden';$('resultEmpty').textContent='此幀尚未完成';$('resultEmpty').hidden=false}$('frameLabel').textContent='透明 PNG · 第 '+(frame+1)+' 幀';$('warnings').textContent=[...(f.warnings||[]),f.error||''].join('；');if(document.activeElement!==$('jump'))$('jump').value=frame+1;$('scrub').value=frame+1;syncComparison(j,f)
}
function showCards(j){if(!j)return;const start=page*12,subset=j.frames.slice(start,start+12),sig=j.id+':'+page+':'+JSON.stringify(subset.map(f=>[f.file,f.status,f.seconds]));if(sig!==cardSignature){cardSignature=sig;const focused=document.activeElement?.dataset?.frame;$('cards').replaceChildren();subset.forEach((f,n)=>{const i=start+n,b=document.createElement('button');b.className='card';b.dataset.frame=i;b.textContent=(i+1)+' · '+(frameNames[f.status]||f.status);if(f.status==='done'){const im=document.createElement('img');im.loading='lazy';im.alt='第 '+(i+1)+' 幀';im.src=file(j,path(j,'png')+'/'+f.file)+'?v='+f.seconds;b.prepend(im)}b.onclick=()=>selectFrame(i);$('cards').append(b)});if(focused!=null)$('cards').querySelector('[data-frame="'+focused+'"]')?.focus({preventScroll:true})}for(const b of $('cards').children){const active=Number(b.dataset.frame)===frame;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))}$('pageInfo').textContent=j.frames.length?`${start+1}–${Math.min(start+12,j.frames.length)} / ${j.frames.length} 幀`:'尚未拆幀';$('prevPage').disabled=page===0;$('nextPage').disabled=start+12>=j.frames.length}
function selectFrame(i,source='frames',emit=true){const j=current();if(!j?.frames.length)return;frame=Math.max(0,Math.min(j.frames.length-1,Math.round(Number(i)||0)));page=Math.floor(frame/12);viewState().frame=frame+1;saveViews();showCards(j);showFrame(j);if(source!=='playback'&&activeVideo?.jobId===j.id){const start=activeVideo.sourceRange[0],end=activeVideo.sourceRange[1];if(frame+1>=start&&frame+1<=end&&$('video').readyState>=1){const t=(frame+1-start)/activeVideo.fps;if(Math.abs($('video').currentTime-t)>.5/activeVideo.fps)$('video').currentTime=t}}if(emit)emitFrame(source)}
window.workbenchSelectFrame=oneBased=>selectFrame(Number(oneBased)-1);
window.addEventListener('workbench:frame',event=>{if(event.detail?.source==='editor')selectFrame(Number(event.detail.frame)-1,'editor',false)});
function videoNames(j){return j?.video_files||{full:j?.exports?.includes('animation.webm')?'animation.webm':null,preview:j?.exports?.includes('preview.webm')?'preview.webm':null}}
function recipeSummary(recipe){if(!recipe)return '';const parts=[];if(Number(recipe.tone))parts.push('明暗 '+(recipe.tone>0?'+':'')+recipe.tone);if(Number(recipe.contrast))parts.push('對比 '+(recipe.contrast>0?'+':'')+recipe.contrast);if(recipe.closure?.enabled)parts.push('首尾同基準第 '+recipe.closure.reference+' 幀 · 前 '+recipe.closure.head_frames+'／後 '+recipe.closure.tail_frames+' 幀');if(recipe.alignment?.enabled)parts.push('局部對位 '+Number(recipe.alignment.strength??100)+'%');else if(['dx','dy','angle'].some(k=>Number(recipe[k]))||['sx','sy'].some(k=>recipe[k]!=null&&Number(recipe[k])!==1&&Number(recipe[k])!==100))parts.push('含位置／變形修正');return parts.join(' · ')}
function availableVideos(j){
 if(!j)return [];const names=videoNames(j),fps=fpsNumber(j.config.fps),dimensions=j.dimensions||[j.video?.width,j.video?.height],entries=[];
 for(const kind of ['full','preview']){if(!names[kind])continue;const count=kind==='full'?j.frames.length:Math.min(Number(j.config.preview_frames)||48,j.frames.length);entries.push({jobId:j.id,kind,name:names[kind],label:kind==='full'?'原始去背 · 完整結果':'原始去背 · 試跑片段',frames:count,fps,dimensions,sourceRange:[1,count],summary:'',url:file(j,path(j,'output')+'/'+names[kind])+'?v='+encodeURIComponent(j.export_version||'original')})}
 for(const v of versionLists.get(j.id)||[]){if(v.state!=='complete'||!v.name)continue;const report=v.report||{},range=report.source_range||[v.recipe?.start||1,v.recipe?.end||j.frames.length],count=Number(report.frames)||Math.max(0,range[1]-range[0]+1),summary=recipeSummary(v.recipe);entries.push({jobId:j.id,kind:'edit:'+v.name,name:v.name,label:v.name+(summary?' · '+summary:''),frames:count,fps:fpsNumber(report.fps||j.config.fps),dimensions:report.dimensions||dimensions,sourceRange:range,summary,url:file(j,'loop_edits/'+v.name+'/loop_transparent.webm')+'?v='+encodeURIComponent(v.revision||v.generation||'legacy')})}
 return entries;
}
function showVideo(j){
 const entries=availableVideos(j),state=j?viewState(j.id):null,desired=state?.version||'',choice=entries.find(v=>v.kind===desired)||entries.find(v=>v.kind==='full')||entries[0]||null,optionsSig=JSON.stringify(entries.map(v=>[v.kind,v.label]));
 if(optionsSig!==videoOptionsSignature){videoOptionsSignature=optionsSig;$('videoChoice').replaceChildren();for(const item of entries){const o=document.createElement('option');o.value=item.kind;o.textContent=item.label;$('videoChoice').append(o)}if(!entries.length){const o=document.createElement('option');o.value='';o.textContent='尚無影片';$('videoChoice').append(o)}}
 $('videoChoice').disabled=!entries.length;$('videoChoice').value=choice?.kind||'';if(state&&!desired&&choice){state.version=choice.kind;saveViews()}
 const url=choice?.url||'';if(url!==lastVideo){saveVideoPosition();loadingVideo=true;lastVideo=url;$('video').pause();activeVideo=choice;$('video').autoplay=false;if(url){$('video').src=url;$('video').load()}else{$('video').removeAttribute('src');$('video').load();loadingVideo=false}}else activeVideo=choice;
 $('videoEmpty').hidden=!!url;if(!url)$('videoEmpty').textContent='尚無預覽影片；可先試跑或直接處理全部';$('play').disabled=$('restart').disabled=!url;
 $('videoInfo').textContent=choice?`${choice.label} · ${choice.frames} 幀 · ${choice.fps.toFixed(2).replace(/\.00$/,'')} FPS · ${choice.dimensions.filter(Boolean).join(' × ')} · ${(choice.frames/choice.fps).toFixed(2)} 秒（1×）`:'尚無預覽影片；可先試跑或直接處理全部';
 const sig=JSON.stringify(choice);if(sig!==videoEventSignature){videoEventSignature=sig;window.dispatchEvent(new CustomEvent('workbench:video',{detail:choice}))}
}
window.workbenchSetVersions=(jobId,list)=>{versionLists.set(jobId,Array.isArray(list)?list:[]);if(selected===jobId)showVideo(current())};
window.workbenchSelectVersion=(jobId,name)=>{if(!jobs.some(j=>j.id===jobId))return;if(selected!==jobId)selectJob(jobId);saveVideoPosition();viewState(jobId).version=name.startsWith('edit:')?name:'edit:'+name;saveViews();showVideo(current());selectWorkspaceTab('tabPlayback')};
function fpsNumber(v){const a=String(v??24).split('/').map(Number),n=a.length===2?a[0]/a[1]:a[0];return Number.isFinite(n)&&n>0?n:24}
function renderJobs(){const sig=JSON.stringify(jobs.map(j=>[j.id,j.name,j.state]));if(sig!==jobsSignature){jobsSignature=sig;const existing=new Map(Array.from($('jobs').children).map(b=>[b.dataset.job,b]));for(const v of jobs){let b=existing.get(v.id);if(!b){b=document.createElement('button');b.dataset.job=v.id;b.onclick=()=>selectJob(v.id);$('jobs').append(b)}b.textContent=v.name+' · '+(stateNames[v.state]||v.state);existing.delete(v.id)}for(const b of existing.values())b.remove()}for(const b of $('jobs').children){b.className='job'+(b.dataset.job===selected?' selected':'');b.setAttribute('aria-pressed',String(b.dataset.job===selected))}}
function render(){
 const j=current(),anyRunning=jobs.some(v=>v.state==='running');renderJobs();['createPreview','createDirect'].forEach(id=>$(id).disabled=anyRunning||busy);
 if(!j){loadedJob='';$('actions').hidden=$('adjustPreview').hidden=true;if($('tabTransitions')?.getAttribute('aria-selected')!=='true')$('title').textContent='選擇素材開始';$('phase').textContent='建立任務，或從任務紀錄開啟素材';$('stats').textContent=$('eta').textContent=$('error').textContent='';$('progress').value=0;showFrame(null);$('cards').replaceChildren();showVideo(null);if(jobEventSignature!=='empty'){jobEventSignature='empty';window.dispatchEvent(new CustomEvent('workbench:job',{detail:null}))}return}
 const changedJob=loadedJob!==j.id,running=j.state==='running';if(changedJob){loadedJob=j.id;frame=Math.max(0,Math.min(j.frames.length-1,Number(viewState(j.id).frame||1)-1));page=Math.floor(frame/12);$('currentPreview').value=j.config.preview_frames||48;cardSignature='';exportsSignature=''}frame=Math.max(0,Math.min(j.frames.length-1,frame));page=Math.min(page,Math.max(0,Math.ceil(j.frames.length/12)-1));
 $('actions').hidden=false;$('adjustPreview').hidden=false;if($('tabTransitions')?.getAttribute('aria-selected')!=='true')$('title').textContent=j.name;$('phase').textContent=j.phase||'';$('error').textContent=j.error||'';const done=j.frames.filter(f=>f.status==='done').length;$('progress').max=j.frames.length||1;$('progress').value=done;const seconds=j.frames.filter(f=>f.seconds).map(f=>f.seconds),avg=seconds.length?seconds.reduce((a,b)=>a+b,0)/seconds.length:0;$('stats').textContent=`${done} / ${j.frames.length} 幀完成 · ${j.config.fps} FPS`+(avg?` · 已處理平均 ${Math.round(avg)} 秒／幀`:'')+` · 資料夾：${j.folder_name||j.id}`;renderEta(j);$('review').hidden=j.state!=='review';$('pause').hidden=!running;$('resume').hidden=!['paused','attention','ready'].includes(j.state);$('direct').hidden=running||j.state==='complete'||j.state==='review';$('reexport').hidden=j.state!=='complete';$('atlas').hidden=j.state!=='complete';['approve','resume','direct','reexport','atlas','extend'].forEach(id=>$(id).disabled=anyRunning||busy);$('retry').disabled=anyRunning||busy||!j.frames.length;showExports(j);$('alpha').textContent=j.alpha_report?`✓ ${j.alpha_report.file}：已回讀 ${j.alpha_report.verified_frames} 幀，Alpha 與 PNG 最大差值 ${j.alpha_report.alpha_max_error}/255，無音軌。`:'合成完成後會在此顯示逐幀透明度驗證。';showCards(j);showFrame(j);showVideo(j);if(window.loopRefresh)window.loopRefresh(j);
 const signature=JSON.stringify(j);if(signature!==jobEventSignature){jobEventSignature=signature;window.dispatchEvent(new CustomEvent('workbench:job',{detail:j}))}if(changedJob&&j.frames.length)emitFrame('frames')
}
let refreshSequence=0;
async function refresh(){const sequence=++refreshSequence;try{const result=await api('jobs');if(sequence!==refreshSequence)return;jobs=Array.isArray(result)?result.map(j=>({...j,frames:j.frames||[],config:j.config||{},exports:j.exports||[]})):[];if(!jobs.some(j=>j.id===selected)){saveVideoPosition();selected=jobs[0]?.id||null}render()}catch(e){notice(e.message)}}
async function action(name,data={}){if(!selected)return;try{busy=true;render();await api(name,{id:selected,...data});await refresh()}catch(e){notice(e.message)}finally{busy=false;render()}}
function updateEstimate(){const fps=fpsNumber($('fps').value||sourceInfo?.fps||24),n=Number($('preview_frames').value||48);$('estimate').textContent=`連續 ${n} 幀，約 ${(n/fps).toFixed(2)} 秒。完整循環檢查請填入一個循環的幀數。`}
function sourceText(v,name){sourceInfo=v;$('info').textContent=`${name} · ${v.width} × ${v.height} · ${v.duration.toFixed(2)} 秒 · 約 ${Math.round(v.duration*fpsNumber(v.fps))} 幀（來源 ${v.fps} FPS）`;updateEstimate()}
async function create(direct){try{busy=true;render();const config={};['start_frame','frame_count','preview_frames','fps','comfy','steps','seed','prompt'].forEach(k=>config[k]=$(k).value);const source=$('source').value.replace(/^"|"$/g,'');if(source===uploadedPath)config.original_name=uploadedName;const j=await api('create',{source,config});saveVideoPosition();selected=j.id;frame=page=0;await api(direct?'direct':'start',{id:j.id,mode:'preview'});await refresh()}catch(e){notice(e.message)}finally{busy=false;render()}}
$('createPreview').onclick=()=>create(false);$('createDirect').onclick=()=>create(true);
$('upload').onchange=async()=>{const f=$('upload').files[0];if(!f)return;try{busy=true;$('createPreview').disabled=$('createDirect').disabled=true;$('info').textContent='正在複製影片…';const r=await fetch('/api/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'X-Token':window.APP_TOKEN},body:f});const v=await r.json();if(!r.ok)throw Error(v.error);$('source').value=uploadedPath=v.path;uploadedName=f.name;sourceText(v.info,f.name)}catch(e){notice(e.message)}finally{busy=false;render();$('createPreview').disabled=$('createDirect').disabled=jobs.some(j=>j.state==='running')}};
$('probe').onclick=async()=>{try{const source=$('source').value.replace(/^"|"$/g,'');sourceText(await api('probe',{source}),source.split(/[\\/]/).pop())}catch(e){notice(e.message)}};
$('check').onclick=async()=>{try{const v=await api('check?url='+encodeURIComponent($('comfy').value));$('environment').textContent=v.comfy?'環境就緒 · 可用 '+v.free_gb+' GB':'缺少：'+[...v.missing_nodes,...v.missing_models].join(', ')}catch(e){$('environment').textContent=e.message}};
$('approve').onclick=()=>action('approve');$('direct').onclick=()=>action('direct');$('resume').onclick=()=>action('start');$('pause').onclick=()=>action('pause');$('open').onclick=()=>action('open');$('atlas').onclick=()=>action('atlas');$('reexport').onclick=()=>action('start',{mode:'export'});$('extend').onclick=()=>action('preview',{frames:$('currentPreview').value});$('retry').onclick=()=>action('retry',{index:frame});
$('prevPage').onclick=()=>{page=Math.max(0,page-1);showCards(current())};$('nextPage').onclick=()=>{const j=current();if(!j)return;page=Math.min(page+1,Math.max(0,Math.ceil(j.frames.length/12)-1));showCards(j)};$('prevFrame').onclick=()=>selectFrame(frame-1);$('nextFrame').onclick=()=>selectFrame(frame+1);$('jumpGo').onclick=()=>selectFrame(Number($('jump').value)-1);$('scrub').oninput=()=>selectFrame(Number($('scrub').value)-1);
$('videoChoice').onchange=()=>{if(!selected)return;saveVideoPosition();viewState().version=$('videoChoice').value;saveViews();showVideo(current())};$('speed').onchange=()=>$('video').playbackRate=Number($('speed').value);$('loop').onchange=()=>$('video').loop=$('loop').checked;$('play').onclick=()=>{if(!activeVideo)return;$('video').paused?$('video').play().catch(()=>{}):$('video').pause()};$('restart').onclick=()=>{if(!activeVideo)return;$('video').currentTime=0;if(playbackVisible())$('video').play().catch(()=>{})};
$('video').onloadedmetadata=()=>{if(!activeVideo)return;const stored=viewState(activeVideo.jobId).videoTimes?.[activeVideo.kind],time=Number.isFinite(stored)?stored:0;$('video').currentTime=Math.max(0,Math.min(time,Math.max(0,$('video').duration-1/activeVideo.fps)));loadingVideo=false};
$('video').onloadeddata=()=>{$('video').playbackRate=Number($('speed').value);$('video').loop=$('loop').checked;if(playbackVisible())$('video').play().catch(()=>{});else $('video').pause();$('videoEmpty').hidden=true};$('video').onerror=()=>{if(!activeVideo)return;$('videoEmpty').hidden=false;$('videoEmpty').textContent='無法讀取影片：檔案可能已移出，或播放器不支援此格式'};
$('video').addEventListener('timeupdate',()=>{if(loadingVideo||!activeVideo||activeVideo.jobId!==selected)return;saveVideoPosition();if(!playbackVisible())return;const localIndex=Math.min(activeVideo.frames-1,Math.max(0,Math.floor($('video').currentTime*activeVideo.fps+0.0001))),next=activeVideo.sourceRange[0]+localIndex-1;if(next===frame||!current()?.frames[next])return;frame=next;viewState().frame=frame+1;saveViews();emitFrame('playback')});
$('video').addEventListener('pause',saveVideoPosition);window.addEventListener('pagehide',()=>{saveVideoPosition();clearTimeout(saveViews.timer);try{localStorage.setItem(viewStateKey,JSON.stringify(jobViews))}catch{}});
function exportLink(j,n,label){const a=document.createElement('a');a.className='download';a.href=file(j,path(j,'output')+'/'+n);a.download=n;a.textContent=label;a.title=n;return a}
function showExports(j){
 const signature=JSON.stringify([j.id,j.exports,videoNames(j),j.frames.some(f=>f.status==='done')]);if(signature===exportsSignature)return;exportsSignature=signature;
 $('exports').replaceChildren();$('exportRecords').replaceChildren();const names=videoNames(j),chosen=new Set();
 for(const [key,title,desc] of [['full','下載完整透明影片（WebM）','完整動畫，保留透明背景。'],['preview','下載試跑影片（WebM）','只包含試跑片段。']]){const n=names[key];if(!n)continue;chosen.add(n);const box=document.createElement('div');box.className='export-card';box.append(exportLink(j,n,title));const small=document.createElement('small');small.textContent=desc+' 檔名：'+n;box.append(small);$('exports').append(box)}
 if(j.frames.some(f=>f.status==='done')){const box=document.createElement('div');box.className='export-card';const b=document.createElement('button');b.textContent='開啟透明 PNG 圖序資料夾';b.onclick=()=>action('open',{folder:'png'});const s=document.createElement('small');s.textContent='每一幀一張透明 PNG，可逐張檢查或匯入動畫。';box.append(b,s);$('exports').append(box)}
 for(const n of j.exports){if(chosen.has(n)||n.endsWith('.raw'))continue;let label=n;if(n.endsWith('_verification.json'))label='透明度驗證記錄 · '+n;else if(n==='atlas.json')label='圖集位置資料 · '+n;else if(n.endsWith('.json'))label='動畫規格資料 · '+n;else if(n.endsWith('.webm'))label='其他影片版本 · '+n;else if(n.startsWith('atlas'))label='下載圖集 · '+n;$(n.endsWith('.png')?'exports':'exportRecords').append(exportLink(j,n,label))}
}
function resizeStillImages(){resizeComparison();for(const id of ['original','result']){const im=$(id),p=im.parentElement;if(!im.naturalWidth)continue;const v=$('imageZoom').value;const scale=v==='fit'?Math.min(p.clientWidth/im.naturalWidth,p.clientHeight/im.naturalHeight):Number(v);im.style.width=Math.max(1,im.naturalWidth*scale)+'px';im.style.height=Math.max(1,im.naturalHeight*scale)+'px'}}
$('imageZoom').onchange=resizeStillImages;
$('stillHeight').oninput=()=>{document.querySelectorAll('.still,.compare-viewport').forEach(el=>el.style.height=$('stillHeight').value+'px');resizeStillImages()};
for(const id of ['original','result'])$(id).onclick=()=>{$('imageZoom').value=$('imageZoom').value==='fit'?'2':'fit';resizeStillImages()};
$('frameFullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('frameInspector').requestFullscreen()}catch(e){notice('無法開啟全螢幕：'+e.message)}};
document.addEventListener('fullscreenchange',resizeStillImages);
const stillObserver=new ResizeObserver(resizeStillImages);document.querySelectorAll('.still').forEach(el=>stillObserver.observe(el));
let bgurl=null,bgImage=null;
function applyBackground(){
 const stage=$('videoStage');document.querySelectorAll('.backdrop').forEach(el=>{el.style.backgroundImage='';el.style.backgroundSize='';el.style.backgroundPosition='';el.style.backgroundRepeat='';el.classList.toggle('check',$('bg').value==='check');el.style.backgroundColor=$('bg').value==='check'?'':$('bg').value});
 $('backgroundControls').hidden=!bgImage;$('bgDragLayer').hidden=!bgImage||!$('dragBackground').checked;
 if(bgImage){stage.classList.remove('check');const scale=Math.min(stage.clientWidth/bgImage.naturalWidth,stage.clientHeight/bgImage.naturalHeight)*Number($('bgScale').value)/100;stage.style.backgroundImage='url("'+bgurl+'")';stage.style.backgroundRepeat='no-repeat';stage.style.backgroundSize=`${bgImage.naturalWidth*scale}px ${bgImage.naturalHeight*scale}px`;stage.style.backgroundPosition=`calc(50% + ${Number($('bgX').value)||0}px) calc(50% + ${Number($('bgY').value)||0}px)`}
 $('bgScaleValue').textContent=$('bgScale').value+'%';
}
$('bg').onchange=()=>{bgImage=null;if(bgurl){URL.revokeObjectURL(bgurl);bgurl=null}$('bgfile').value='';applyBackground()};
$('bgfile').onchange=()=>{const f=$('bgfile').files[0];if(!f)return;if(bgurl)URL.revokeObjectURL(bgurl);bgurl=URL.createObjectURL(f);const im=new Image();const url=bgurl;im.onload=()=>{if(bgurl!==url)return;bgImage=im;$('bgScale').value=100;$('bgX').value=$('bgY').value=0;applyBackground()};im.onerror=()=>notice('背景圖片無法讀取，請重新選擇');im.src=url};
['bgScale','bgX','bgY','dragBackground'].forEach(id=>$(id).oninput=applyBackground);
$('resetBackground').onclick=()=>{$('bgScale').value=100;$('bgX').value=$('bgY').value=0;applyBackground()};
let drag=null;const layer=$('bgDragLayer');layer.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,bx:Number($('bgX').value)||0,by:Number($('bgY').value)||0};layer.setPointerCapture(e.pointerId)};layer.onpointermove=e=>{if(!drag)return;$('bgX').value=Math.round(drag.bx+e.clientX-drag.x);$('bgY').value=Math.round(drag.by+e.clientY-drag.y);applyBackground()};layer.onpointerup=layer.onpointercancel=()=>drag=null;
function sizePreview(){$('videoStage').style.width=$('previewWidth').value+'px';$('videoStage').style.height=$('previewHeight').value+'px';applyBackground()}
['previewWidth','previewHeight'].forEach(id=>$(id).oninput=sizePreview);$('resetPreview').onclick=()=>{$('videoStage').style.removeProperty('width');$('videoStage').style.removeProperty('height');applyBackground()};
new ResizeObserver(applyBackground).observe($('videoStage'));
['fps','preview_frames'].forEach(id=>$(id).oninput=updateEstimate);
function syncComparison(j,f){
 const original=file(j,path(j,'frames')+'/'+f.file);const result=f.status==='done'?file(j,path(j,'png')+'/'+f.file)+'?v='+(f.seconds||0):'';
 for(const [id,url] of [['compareOriginal',original],['compareResult',result]]){const im=$(id);if(!url){im.removeAttribute('src');im.style.visibility='hidden';continue}if(im.getAttribute('src')!==url){im.style.visibility='hidden';im.onload=()=>{im.style.visibility='visible';resizeComparison()};im.onerror=()=>{im.style.visibility='hidden';$('compareEmpty').hidden=false;$('compareEmpty').textContent='圖片無法讀取'};im.src=url}}
 $('compareEmpty').hidden=f.status==='done';$('compareEmpty').textContent='此幀尚未完成';resizeComparison();
}
function resizeComparison(){const im=$('compareOriginal'),p=$('compareViewport');if(!im?.naturalWidth||p.hidden)return;const v=$('imageZoom').value,scale=v==='fit'?Math.min(p.clientWidth/im.naturalWidth,p.clientHeight/im.naturalHeight):Number(v);$('compareCanvas').style.width=im.naturalWidth*scale+'px';$('compareCanvas').style.height=im.naturalHeight*scale+'px'}
function splitComparison(value){const n=Math.max(0,Math.min(100,Number(value)));$('compareSplit').value=n;$('compareCanvas').style.setProperty('--split',n+'%');$('compareHandle').setAttribute('aria-valuenow',Math.round(n))}
$('compareSplit').oninput=()=>splitComparison($('compareSplit').value);$('compareCenter').onclick=()=>splitComparison(50);
$('compareMode').onchange=()=>{const wipe=$('compareMode').value==='wipe';$('compareViewport').hidden=$('compareTools').hidden=!wipe;$('sideViewer').hidden=wipe;resizeStillImages()};
const handle=$('compareHandle');let comparing=false;function moveSplit(e){const rect=$('compareCanvas').getBoundingClientRect();splitComparison((e.clientX-rect.left)/rect.width*100)}
handle.onpointerdown=e=>{comparing=true;handle.setPointerCapture(e.pointerId);moveSplit(e);e.preventDefault()};handle.onpointermove=e=>{if(comparing)moveSplit(e)};handle.onpointerup=handle.onpointercancel=()=>comparing=false;handle.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();splitComparison(e.key==='Home'?0:e.key==='End'?100:Number($('compareSplit').value)+(e.key==='ArrowLeft'?-1:1))}};
$('compareCanvas').ondblclick=()=>{$('imageZoom').value=$('imageZoom').value==='fit'?'2':'fit';resizeStillImages()};new ResizeObserver(resizeComparison).observe($('compareViewport'));
refresh();setInterval(refresh,2500);

const workspaceTabs=['tabPlayback','tabFrames','tabEdit','tabTransitions'];
function selectWorkspaceTab(id){if(!workspaceTabs.includes(id))return;for(const tid of workspaceTabs){const button=$(tid),active=tid===id;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;$(button.getAttribute('aria-controls')).hidden=!active}if(id!=='tabPlayback')$('video').pause();if(id!=='tabEdit')$('leStop')?.click();if(id==='tabFrames'&&current()){page=Math.floor(frame/12);showCards(current());showFrame(current())}window.dispatchEvent(new CustomEvent('workbench:tab',{detail:{id}}));requestAnimationFrame(()=>{if(id==='tabEdit')window.loopTabShown?.();if(id==='tabTransitions')window.transitionsShow?.();resizeStillImages();applyBackground();window.dispatchEvent(new Event('resize'))})}
window.workbenchSelectTab=selectWorkspaceTab;
workspaceTabs.forEach((id,i)=>{$(id).onclick=()=>selectWorkspaceTab(id);$(id).onkeydown=event=>{const n=workspaceTabs.length;let index=event.key==='ArrowRight'?(i+1)%n:event.key==='ArrowLeft'?(i+n-1)%n:event.key==='Home'?0:event.key==='End'?n-1:null;if(index!==null){event.preventDefault();selectWorkspaceTab(workspaceTabs[index]);$(workspaceTabs[index]).focus()}}});
function durationText(seconds){seconds=Math.max(1,Math.ceil(seconds));if(seconds<60)return seconds+' 秒';if(seconds<3600)return Math.ceil(seconds/60)+' 分鐘';return Math.floor(seconds/3600)+' 小時 '+Math.ceil(seconds%3600/60)+' 分鐘'}
function progressText(p){if(!p)return '';const elapsed=(Date.now()/1000-p.started);let text=p.stage+' · '+p.done+' / '+p.total+' 幀 · 已用 '+durationText(elapsed);if(p.remaining!=null){text+=' · 此階段預估剩餘 '+durationText(p.remaining)}else text+=' · 正在估算剩餘時間';return text+(p.after?'；接著還需'+p.after:'')}
function renderEta(j){if(j.state!=='running'){$('eta').textContent='';return}if(j.export_progress){$('eta').textContent=progressText(j.export_progress);return}const indices=j.run_mode==='preview'?(j.preview_indices||[]):j.run_mode==='single'?[j.retry_index]:j.frames.map((_,i)=>i);const remaining=indices.filter(i=>j.frames[i]?.status!=='done').length;const timings=j.frames.filter(f=>f.seconds>0).slice(-10).map(f=>f.seconds);$('eta').textContent=timings.length&&remaining?'去背預估剩餘約 '+durationText(remaining*timings.reduce((a,b)=>a+b,0)/timings.length)+'；之後還需合成影片與驗證透明度。':'正在準備／估算剩餘時間…'}
