// Focused state tests: comparison sources, task drafts, reference isolation and frame events.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const code=fs.readFileSync(__dirname+'/loop.js','utf8');
const regionScope={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/region.js','utf8'),regionScope,{filename:'region.js'});const Region=regionScope.window.RegionEditor;
function harness(storage=new Map(),quota=false,withRegion=false){
 const nodes=new Map(),listeners=new Map(),calls=[],emitted=[],hooks=[],responses=new Map(),imageLoads=[];let timerId=0;const timers=new Map();
 class Element{
  constructor(id=''){this.id=id;this.value='0';this.checked=false;this.hidden=false;this.disabled=false;this.textContent='';this.files=[];this.children=[];this.options=[];this.dataset={};this.clientWidth=500;this.clientHeight=500;this.scrollLeft=0;this.scrollTop=0;this.style={setProperty(){}}}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=nodes}setAttribute(k,v){this[k]=v}setPointerCapture(){}matches(){return false}
  showModal(){this.open=true}close(){this.open=false}
  getBoundingClientRect(){return{left:0,top:0,width:500,height:500}}
  getContext(){return new Proxy({getImageData(){return{data:new Uint8ClampedArray(64*80*4)}}},{get:(t,k)=>t[k]||(()=>{})})}
 }
 const $=id=>{if(!nodes.has(id))nodes.set(id,new Element(id));return nodes.get(id)};
 for(const[id,values]of Object.entries({Mode:['wipe','onion','contour','diff'],OutputMode:['wipe','diff'],OutputZoom:['fit','1','2','4'],Zoom:['fit','1','2','4'],Backdrop:['#000000','#ffffff','#666666','#204080'],Purpose:['tone','loop','reference']})){const node=$('le'+id);node.value=values[0];node.options=values.map(value=>({value}))}
 $('leSplit').value='50';$('leSpeed').value='1';$('leSeamN').value='2';$('loopEditor').hidden=true;
 const window={addEventListener(name,fn){if(!listeners.has(name))listeners.set(name,[]);listeners.get(name).push(fn)},dispatchEvent(event){emitted.push(event);for(const fn of listeners.get(event.type)||[])fn(event)},workbenchSetVersions(...args){hooks.push(['versions',...args])},workbenchSelectVersion(...args){hooks.push(['select',...args])},workbenchExportStatus(...args){hooks.push(['status',...args])}};
 class Img{constructor(){this.width=64;this.height=80}set src(value){this._src=value;imageLoads.push(value);queueMicrotask(()=>String(value).startsWith('bad:')?this.onerror?.():this.onload?.())}}
 const api=async(action,data)=>{calls.push({action,data});if(responses.has(action))return responses.get(action)(data);if(action==='loop/preview')return{image:'preview:'+data.frame,frame:data.frame,clipped:false,...(data.recipe?.closure?.enabled&&!data.original?{closure:{enabled:true,reference:data.recipe.closure.reference,weight:1}}:{})};if(action==='loop/align')return{alignment:{enabled:true,strength:100,model:{provenance:{scope:'loop',source:{job_id:data.id,version:'original',frame:data.source_frame},reference:{job_id:data.id,version:'original',frame:data.reference_frame}},opaque:{displacement:[1,2,3],algorithm:'test'}}},report:{before:{silhouette_mismatch_pixels:20},after:{silhouette_mismatch_pixels:5}}};if(action==='loop/load')return{recipe:null,versions:[{name:'修整_001',state:'complete',phase:'完成',recipe:{start:1,end:4,tone:10,contrast:0,sx:100,sy:100},report:{frames:4,fps:12}}]};return {}};
 const sandbox={$,api,file:(j,p)=>j.id+'/'+p,current:()=>null,window,document:{createElement:()=>new Element()},localStorage:{getItem:k=>storage.get(k)||null,setItem(k,v){if(quota)throw Error('quota');storage.set(k,v)}},Image:Img,URL:{createObjectURL:f=>'blob:'+f.name,revokeObjectURL(){}},ResizeObserver:class{observe(){}},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init.detail}},setTimeout(fn){const id=++timerId;timers.set(id,fn);return id},clearTimeout(id){timers.delete(id)},fpsNumber:Number,progressText:()=>'',durationText:String,console};
 const editors=[];if(withRegion){class Editor{constructor(options){this.options=options;editors.push(this)}static normalize=Region.normalize;static identity=Region.identity;sync(){this.options.onSync?.(this.options.getValue())}draw(){this.sync()}deactivate(){}}window.RegionEditor=sandbox.RegionEditor=Editor}
 vm.runInNewContext(code,sandbox,{filename:'loop.js'});
 return{$,window,calls,emitted,hooks,storage,editors,responses,imageLoads,async flush(){await new Promise(setImmediate);const pending=[...timers.values()];timers.clear();for(const fn of pending)await fn();await new Promise(setImmediate)}};
}
const makeJob=id=>({id,frames:Array.from({length:4},()=>({status:'done'})),dimensions:[64,80],config:{fps:12}});
const prefix='animation-workbench:draft:v1:';
(async()=>{
 const h=harness(),a=makeJob('a'),b=makeJob('b');h.window.loopRefresh(a);await h.flush();h.$('loopEditor').hidden=false;
 await h.$('lePreview').onclick();
 let last=h.calls.filter(v=>v.action==='loop/preview').slice(-2);assert.deepEqual(last.map(v=>[v.data.frame,v.data.original]),[[4,true],[4,false]]);
 assert.match(h.$('leSourceA').textContent,/原始去背.*4/);assert.match(h.$('leSourceB').textContent,/修整草稿.*4/);
 h.$('leToneRange').value='35';h.$('leToneRange').oninput();assert.equal(h.$('leTone').value,'35');
 h.$('leTone').value='20';h.$('leTone').oninput();assert.equal(h.$('leToneRange').value,'20');
 h.$('leA').value='2';h.$('leA').oninput();h.$('leTimeline').value='3';h.$('leTimeline').oninput();assert.equal(Number(h.$('leB').value),3);assert.equal(Number(h.$('leA').value),2);
 assert.equal(h.emitted.at(-1).detail.source,'editor');assert.equal(h.emitted.at(-1).detail.frame,3);
 const before=h.emitted.filter(event=>event.type==='workbench:frame').length;h.window.dispatchEvent({type:'workbench:frame',detail:{frame:2,source:'frames'}});assert.equal(h.emitted.filter(event=>event.type==='workbench:frame').length,before+1);assert.equal(Number(h.$('leB').value),2);assert.equal(Number(h.$('leA').value),2);
 h.$('leReference').files=[{name:'source.png'}];await h.$('leReference').onchange();await h.flush();assert.equal(h.$('lePurpose').value,'reference');assert.match(h.$('leSourceA').textContent,/source.png/);
 h.window.loopRefresh(b);await h.flush();assert.equal(h.$('lePurpose').value,'tone');assert.equal(h.$('leReferenceName').textContent,'尚未選取參考圖');assert.equal(Number(h.$('leTone').value),0);
 h.window.loopRefresh(a);await h.flush();assert.equal(Number(h.$('leTone').value),20);assert.equal(h.$('lePurpose').value,'reference');assert.equal(h.$('leReferenceName').textContent,'source.png');
 const restored=harness(h.storage);restored.window.loopRefresh(a);await restored.flush();restored.$('loopEditor').hidden=false;await restored.$('lePreview').onclick();assert.match(restored.$('leMessage').textContent,/重新選取/);assert.match(restored.$('leDraftState').textContent,/參考圖需重新選取/);assert.equal(restored.calls.filter(v=>v.action==='loop/preview').length,0);
 restored.$('lePurpose').value='loop';restored.$('lePurpose').onchange();await restored.flush();assert.equal(restored.$('leAControls').hidden,false);last=restored.calls.filter(v=>v.action==='loop/preview').slice(-2);assert.deepEqual(last.map(v=>v.data.original),[false,false]);
 const bad=new Map([[prefix+'bad','{broken']]);const badUi=harness(bad);badUi.window.loopRefresh(makeJob('bad'));await badUi.flush();assert.equal(Number(badUi.$('leSx').value),100);assert.match(badUi.$('leDraftState').textContent,/無法讀取/);
 const quota=harness(new Map(),true);quota.window.loopRefresh(a);await quota.flush();quota.$('leTone').value='15';quota.$('leTone').oninput();assert.match(quota.$('leDraftState').textContent,/本次視窗/);quota.window.loopRefresh(b);await quota.flush();quota.window.loopRefresh(a);await quota.flush();assert.equal(Number(quota.$('leTone').value),15);
 assert.ok(h.hooks.some(v=>v[0]==='versions'&&v[1]==='a'));assert.ok(h.hooks.some(v=>v[0]==='status'));
 const versionCard=h.$('leVersions').children[0];versionCard.children.find(c=>c.textContent==='播放此版本').onclick();assert.ok(h.hooks.some(v=>v[0]==='select'&&v[1]==='a'&&v[2]==='修整_001'));
 h.$('lePurpose').value='tone';h.$('lePurpose').onchange();await h.flush();assert.equal(h.$('editorEmpty').hidden,true);
 h.$('leSx').value='90';h.$('leSx').oninput();h.$('leLockRatio').checked=true;h.$('leLockRatio').onchange();h.$('leSx').value='120';h.$('leSx').oninput();assert.equal(Number(h.$('leSx').value),108);assert.equal(Number(h.$('leSy').value),120);
 h.$('leSy').value='80';h.$('leSy').oninput();assert.equal(Number(h.$('leSx').value),80);assert.ok(Math.abs(Number(h.$('leSy').value)-88.889)<.001);await h.flush();
 h.$('loopEditor').hidden=true;const requests=h.calls.filter(v=>v.action==='loop/preview').length;
 for(const frame of [1,2,3])h.window.dispatchEvent({type:'workbench:frame',detail:{frame,source:'playback'}});await h.flush();assert.equal(h.calls.filter(v=>v.action==='loop/preview').length,requests);assert.equal(Number(h.$('leB').value),3);
 h.$('loopEditor').hidden=false;h.window.loopTabShown();await h.flush();assert.ok(h.calls.filter(v=>v.action==='loop/preview').length>requests);assert.match(h.$('leSourceB').textContent,/第 3 幀/);assert.equal(h.$('editorEmpty').hidden,true);
 const empty=makeJob('empty');empty.frames.forEach(f=>f.status='pending');h.window.loopRefresh(empty);await h.flush();assert.equal(h.$('editorEmpty').hidden,false);assert.match(h.$('editorEmpty').textContent,/尚無完成/);
 const lifecycle=harness(),newJob={...makeJob('new'),frames:[],state:'running'};lifecycle.window.loopRefresh(newJob);await lifecycle.flush();assert.equal(lifecycle.$('leExport').disabled,true);lifecycle.$('leTone').value='23';lifecycle.$('leTone').oninput();
 const allocated={...makeJob('new'),state:'running',frames:Array.from({length:4},()=>({status:'pending'}))};lifecycle.window.loopRefresh(allocated);await lifecycle.flush();assert.equal(Number(lifecycle.$('leEnd').value),4);assert.equal(Number(lifecycle.$('leRamp').value),1);assert.equal(Number(lifecycle.$('leTone').value),23);assert.equal(lifecycle.$('leExport').disabled,true);
 lifecycle.$('loopEditor').hidden=false;lifecycle.window.loopRefresh({...makeJob('new'),state:'complete'});await lifecycle.flush();assert.equal(lifecycle.$('leExport').disabled,false);assert.equal(lifecycle.$('editorEmpty').hidden,true);assert.ok(lifecycle.calls.some(v=>v.action==='loop/preview'&&v.data.recipe.end===4));
 const queuedStorage=new Map([[prefix+'queued',JSON.stringify({version:1,recipe:{start:2,end:3,ramp:2,tone:17},a:2,b:3,purpose:'loop'})]]),queued=harness(queuedStorage);
 queued.window.loopRefresh({...makeJob('queued'),frames:[],state:'running'});await queued.flush();queued.$('leTone').value='19';queued.$('leTone').oninput();assert.equal(JSON.parse(queuedStorage.get(prefix+'queued')).recipe.end,3);
 queued.window.loopRefresh({...makeJob('queued'),state:'complete'});await queued.flush();assert.equal(Number(queued.$('leStart').value),2);assert.equal(Number(queued.$('leEnd').value),3);assert.equal(Number(queued.$('leRamp').value),2);assert.equal(Number(queued.$('leB').value),3);assert.equal(Number(queued.$('leTone').value),19);assert.equal(queued.$('leExport').disabled,false);
 // Split transforms must survive normalization, undo, task switching and the preview/export payload.
 const affine={dx:6,dy:-3,sx:98,sy:102,angle:1,cx:40,cy:60},bounds={mode:'outside',shape:'rect',x:20,y:10,w:60,h:80,feather:8};
 const migrated=Region.changeMode(bounds,'split',affine);assert.equal(migrated.transform.dx,0);assert.equal(migrated.transform.sx,100);assert.equal(migrated.region.outside.dx,6);assert.equal(migrated.region.mode,'split');
 assert.equal(Region.changeMode({...bounds,mode:'inside'},'split',affine).region.outside.dx,0);assert.equal(Region.changeMode({...bounds,mode:'all'},'split',affine).region.outside.dx,6);
 const clean=Region.normalize({...migrated.region,outside:{dx:400,sx:50,cy:200}});assert.equal(clean.outside.dx,100);assert.equal(clean.outside.sx,80);assert.equal(clean.outside.cy,100);assert.equal(clean.outside.dy,0);
 const split=harness(new Map(),false,true),opts=split.editors[0].options;split.window.loopRefresh(makeJob('split'));await split.flush();split.$('loopEditor').hidden=false;await split.$('lePreview').onclick();
 split.$('leDx').value='6';split.$('leDx').oninput();opts.onBegin();opts.onChange(migrated.region,migrated.transform);assert.equal(Number(split.$('leDx').value),0);assert.equal(split.$('leTransformHeading').textContent,'框內變形');
 opts.onBegin();opts.onChange({...opts.getValue(),outside:{...opts.getValue().outside,dx:-4,sx:99}});await split.flush();let payload=split.calls.filter(v=>v.action==='loop/preview').at(-1).data.recipe;assert.equal(payload.region.outside.dx,-4);assert.equal(payload.dx,0);
 opts.onBegin();opts.onChange({...opts.getValue(),outside:{...opts.getValue().outside,dx:-7}});split.$('leUndo').onclick();assert.equal(opts.getValue().outside.dx,-4);
 split.window.loopRefresh(makeJob('other'));await split.flush();split.window.loopRefresh(makeJob('split'));await split.flush();assert.equal(opts.getValue().outside.sx,99);assert.equal(opts.getValue().outside.dx,-4);
 const reloaded=harness(split.storage,false,true);reloaded.window.loopRefresh(makeJob('split'));await reloaded.flush();assert.equal(reloaded.editors[0].options.getValue().outside.dx,-4);await reloaded.$('leExport').onclick();assert.equal(reloaded.calls.find(v=>v.action==='loop/export').data.recipe.region.outside.dx,-4);
 split.$('leReset').onclick();assert.equal(opts.getValue().outside.dx,0);assert.equal(opts.getValue().outside.sx,100);split.$('leUndo').onclick();assert.equal(opts.getValue().outside.dx,-4);
 // Edge widths use displayed-canvas coordinates, not zoom-dependent pixel deltas.
 assert.equal(Region.normalize({mode:'inside'}).edge_left,undefined);const edgeDefaults=Region.normalize({mode:'edge'});assert.equal(edgeDefaults.edges,'both');assert.equal(edgeDefaults.edge_left,12);assert.equal(edgeDefaults.edge_right,12);
 const edgeLimits=Region.normalize({mode:'edge',edges:'invalid',edge_left:0,edge_right:90});assert.equal(edgeLimits.edges,'both');assert.equal(edgeLimits.edge_left,1);assert.equal(edgeLimits.edge_right,45);assert.equal(Region.normalize({mode:'edge',edge_left:null,edge_right:'bad'}).edge_left,12);assert.equal(Region.normalize({mode:'edge',edge_right:'bad'}).edge_right,12);
 const movedToEdge=Region.changeMode({...bounds,mode:'split',outside:affine},'edge',affine);assert.equal(movedToEdge.transform.sx,98);assert.equal(movedToEdge.transform.dx,6);assert.equal(movedToEdge.region.outside.dx,6);assert.equal(movedToEdge.region.x,20);
 const storedEdge=Region.changeMode({...movedToEdge.region,edge_left:18,edge_right:22},'inside',affine);assert.equal(storedEdge.region.edge_left,18);assert.equal(Region.changeMode(storedEdge.region,'edge',affine).region.edge_right,22);
 const point=(clientX,width)=>Region.prototype.point.call({canvas:{getBoundingClientRect:()=>({left:40,top:20,width,height:width})}},{clientX,clientY:100});
 const p1=point(100,500),p2=point(160,1000);assert.equal(p1.x,12);assert.equal(p2.x,12);assert.equal(Region.prototype.hit(p1,edgeDefaults),'edge-left');assert.equal(Region.prototype.hit(p2,edgeDefaults),'edge-left');assert.equal(Region.prototype.hit({...p1,x:88},edgeDefaults),'edge-right');assert.equal(Region.prototype.hit({...p1,x:50},edgeDefaults),null);assert.equal(Region.prototype.hit(p1,{...edgeDefaults,edges:'right'}),null);
 assert.equal(Region.edgeDrag(edgeDefaults,'edge-left',5).edge_left,17);assert.equal(Region.edgeDrag(edgeDefaults,'edge-right',-5).edge_right,17);assert.equal(Region.edgeDrag(edgeDefaults,'edge-left',100).edge_left,45);assert.equal(Region.edgeDrag(edgeDefaults,'edge-right',100).edge_right,1);assert.equal(Region.edgeDrag({...edgeDefaults,edges:'left'},'edge-right',-5).edge_right,12);
 opts.onBegin();opts.onChange({...opts.getValue(),mode:'edge',edges:'left',edge_left:18,edge_right:22},affine);await split.flush();assert.match(split.$('leTransformHeading').textContent,/中間修整/);assert.equal(Number(split.$('leSx').value),98);payload=split.calls.filter(v=>v.action==='loop/preview').at(-1).data.recipe;assert.equal(payload.region.mode,'edge');assert.equal(payload.region.edge_left,18);assert.equal(payload.region.outside.dx,-4);
 const edgeReload=harness(split.storage,false,true);edgeReload.window.loopRefresh(makeJob('split'));await edgeReload.flush();const edgeOpts=edgeReload.editors[0].options;assert.equal(edgeOpts.getValue().edges,'left');assert.equal(edgeOpts.getValue().edge_right,22);await edgeReload.$('leExport').onclick();assert.equal(edgeReload.calls.find(v=>v.action==='loop/export').data.recipe.region.edge_left,18);
 edgeReload.$('leReset').onclick();assert.equal(Number(edgeReload.$('leSx').value),100);assert.equal(edgeOpts.getValue().edge_left,18);edgeReload.$('leUndo').onclick();assert.equal(Number(edgeReload.$('leSx').value),98);assert.equal(edgeOpts.getValue().edges,'left');
 // Alignment always solves the selected tail, preserves its opaque model, and does not follow comparison-only frame changes.
 const align=harness(new Map(),false,true);align.window.loopRefresh(makeJob('aligned'));await align.flush();align.$('loopEditor').hidden=false;align.$('leSx').value='96';align.$('leSx').oninput();align.$('leB').value='2';align.$('leB').oninput();await align.$('leAlign').onclick();await align.flush();
 const solve=align.calls.find(v=>v.action==='loop/align');assert.equal(solve.data.source_frame,4);assert.equal(solve.data.reference_frame,1);assert.equal(Number(align.$('leB').value),4);assert.equal(align.$('lePurpose').value,'loop');assert.equal(align.$('leAlignEnabled').checked,true);assert.equal(align.$('leManualTransform').disabled,true);assert.equal(Number(align.$('leSx').value),96);assert.match(align.$('leAlignReport').textContent,/20 → 5/);
 align.$('leAlignStrength').onfocus();align.$('leAlignStrength').value='70';align.$('leAlignStrength').oninput();await align.flush();payload=align.calls.filter(v=>v.action==='loop/preview').at(-1).data.recipe;assert.equal(payload.alignment.strength,70);assert.equal(payload.alignment.model.opaque.displacement[2],3);assert.equal(payload.sx,96);
 align.$('leA').value='2';align.$('leA').oninput();assert.equal(align.$('leAlignEnabled').checked,true);assert.match(align.$('leAlignStatus').textContent,/計算時第 1 幀/);await align.$('leSave').onclick();await align.$('leExport').onclick();const savedAlignmentRecipe=align.calls.find(v=>v.action==='loop/export').data.recipe;assert.equal(savedAlignmentRecipe.alignment.model.provenance.reference.frame,1);assert.equal(savedAlignmentRecipe.alignment.strength,70);
 const alignRestored=harness(align.storage,false,true);alignRestored.window.loopRefresh(makeJob('aligned'));await alignRestored.flush();assert.equal(alignRestored.$('leAlignEnabled').checked,true);assert.equal(Number(alignRestored.$('leAlignStrength').value),70);assert.equal(alignRestored.$('leManualTransform').disabled,true);
 alignRestored.$('leEnd').value='3';alignRestored.$('leEnd').oninput();assert.equal(alignRestored.$('leAlignEnabled').checked,false);assert.equal(alignRestored.$('leAlignEnabled').disabled,true);assert.equal(alignRestored.$('leManualTransform').disabled,false);assert.match(alignRestored.$('leAlignStatus').textContent,/來源尾幀已變更/);assert.equal(JSON.parse(alignRestored.storage.get(prefix+'aligned')).recipe.alignment.enabled,true);const countExports=alignRestored.calls.filter(v=>v.action==='loop/export'||v.action==='loop/save').length;await alignRestored.$('leExport').onclick();await alignRestored.$('leSave').onclick();assert.equal(alignRestored.calls.filter(v=>v.action==='loop/export'||v.action==='loop/save').length,countExports);assert.match(alignRestored.$('leMessage').textContent,/清除對位.*儲存／輸出/);alignRestored.$('leUndo').onclick();assert.equal(Number(alignRestored.$('leEnd').value),4);assert.equal(alignRestored.$('leAlignEnabled').checked,true);
 alignRestored.$('leAlignClear').onclick();assert.equal(alignRestored.$('leAlignEnabled').checked,false);assert.equal(alignRestored.$('leManualTransform').disabled,false);assert.equal(JSON.parse(alignRestored.storage.get(prefix+'aligned')).recipe.alignment,undefined);alignRestored.$('leUndo').onclick();assert.equal(alignRestored.$('leAlignEnabled').checked,true);
 alignRestored.responses.set('loop/load',()=>({recipe:JSON.parse(JSON.stringify(savedAlignmentRecipe)),versions:[]}));await alignRestored.$('leLoad').onclick();assert.equal(Number(alignRestored.$('leA').value),1);assert.equal(alignRestored.$('leAlignEnabled').checked,true);assert.equal(Number(alignRestored.$('leAlignStrength').value),70);
 let resolveSolve;alignRestored.responses.set('loop/align',()=>new Promise(resolve=>resolveSolve=resolve));const pendingSolve=alignRestored.$('leAlign').onclick();alignRestored.window.loopRefresh(makeJob('different'));await alignRestored.flush();resolveSolve({alignment:savedAlignmentRecipe.alignment});await pendingSolve;assert.equal(alignRestored.$('leAlignEnabled').checked,false);assert.equal(Number(alignRestored.$('leSx').value),100);
 const race=harness();race.window.loopRefresh(makeJob('race'));await race.flush();race.responses.set('loop/align',()=>new Promise(resolve=>resolveSolve=resolve));const changedSolve=race.$('leAlign').onclick();race.$('leTone').value='12';race.$('leTone').oninput();resolveSolve({alignment:{enabled:true,strength:100,model:{provenance:{scope:'loop',source:{job_id:'race',frame:4},reference:{job_id:'race',frame:1}}}}});await changedSolve;assert.equal(race.$('leAlignEnabled').checked,false);assert.match(race.$('leAlignStatus').textContent,/設定已變更/);assert.equal(Number(race.$('leTone').value),12);
 // Retained images retain their own frame/strength labels; they are never presented as the current draft.
 const diagnostics=harness();diagnostics.window.loopRefresh(makeJob('diagnostics'));await diagnostics.flush();diagnostics.$('loopEditor').hidden=false;await diagnostics.$('leAlign').onclick();await diagnostics.flush();
 assert.match(diagnostics.$('lePreviewSnapshot').textContent,/修整草稿（不是已輸出版本）.*首尾銜接.*A 第 1 幀.*B 第 4 幀.*100%/);assert.equal(diagnostics.$('lePreviewBadge').hidden,true);
 diagnostics.$('leAlignStrength').value='65';diagnostics.$('leAlignStrength').oninput();assert.equal(diagnostics.$('lePreviewBadge').hidden,false);assert.match(diagnostics.$('lePreviewBadge').textContent,/舊預覽/);assert.match(diagnostics.$('lePreviewSnapshot').textContent,/100%/);assert.match(diagnostics.$('leAlignReport').textContent,/目前 65%.*不適用/);assert.doesNotMatch(diagnostics.$('leAlignReport').textContent,/20 → 5/);
 await diagnostics.flush();assert.equal(diagnostics.$('lePreviewBadge').hidden,true);assert.match(diagnostics.$('lePreviewSnapshot').textContent,/65%/);
 diagnostics.$('leMode').value='onion';diagnostics.$('leMode').oninput();assert.match(diagnostics.$('leModeHint').textContent,/混合顯示.*不是單張輸出/);diagnostics.$('leMode').value='contour';diagnostics.$('leMode').oninput();assert.match(diagnostics.$('leModeHint').textContent,/紅色.*A.*青色.*B.*不代表內部線條/);
 // API and image decode errors must leave an unmistakable stale badge and block export.
 diagnostics.responses.set('loop/preview',async()=>{throw Error('synthetic preview failure')});diagnostics.$('leTone').value='8';diagnostics.$('leTone').oninput();await diagnostics.flush();assert.match(diagnostics.$('lePreviewBadge').textContent,/更新失敗/);assert.match(diagnostics.$('lePreviewSnapshot').textContent,/65%/);await diagnostics.$('leExport').onclick();assert.equal(diagnostics.calls.filter(x=>x.action==='loop/export').length,0);assert.match(diagnostics.$('leMessage').textContent,/預覽未更新成功.*未輸出/);
 diagnostics.responses.set('loop/preview',async data=>({frame:data.frame,image:'bad:decode'}));await diagnostics.$('leExport').onclick();assert.equal(diagnostics.calls.filter(x=>x.action==='loop/export').length,0);assert.match(diagnostics.$('leMessage').textContent,/圖片載入失敗/);assert.match(diagnostics.$('lePreviewBadge').textContent,/更新失敗/);
 diagnostics.responses.delete('loop/preview');await diagnostics.$('lePreview').onclick();assert.equal(diagnostics.$('lePreviewBadge').hidden,true);
 // Export waits for both decoded corrected images, even when a prior comparison is already pending.
 const deferred=harness();deferred.window.loopRefresh(makeJob('deferred'));await deferred.flush();deferred.$('loopEditor').hidden=false;await deferred.$('lePreview').onclick();deferred.$('leTone').value='9';deferred.$('leTone').oninput();let releaseFirst;let held=true;deferred.responses.set('loop/preview',data=>{if(held){held=false;return new Promise(resolve=>releaseFirst=()=>resolve({frame:data.frame,image:'preview:'+data.frame}))}return{frame:data.frame,image:'preview:'+data.frame}});
 const pendingPreview=deferred.$('lePreview').onclick();await new Promise(setImmediate);const waitingExport=deferred.$('leExport').onclick();await new Promise(setImmediate);assert.equal(deferred.calls.filter(x=>x.action==='loop/export').length,0);assert.equal(deferred.$('leExport').disabled,true);await deferred.$('leExport').onclick();deferred.window.loopRefresh(makeJob('deferred'));await new Promise(setImmediate);assert.equal(deferred.$('leExport').disabled,true);releaseFirst();await pendingPreview;await waitingExport;assert.equal(deferred.calls.filter(x=>x.action==='loop/export').length,1);assert.equal(deferred.calls.find(x=>x.action==='loop/export').data.recipe.tone,9);assert.equal(deferred.$('lePreviewBadge').hidden,true);
 // A changed frame or job during validation aborts export; a previous A/B request cannot be mislabeled as the new pair.
 const changed=harness();changed.window.loopRefresh(makeJob('changed'));await changed.flush();changed.$('loopEditor').hidden=false;await changed.$('lePreview').onclick();changed.$('leTone').value='10';changed.$('leTone').oninput();held=true;changed.responses.set('loop/preview',data=>{if(held){held=false;return new Promise(resolve=>releaseFirst=()=>resolve({frame:data.frame,image:'preview:'+data.frame}))}return{frame:data.frame,image:'preview:'+data.frame}});const changedExport=changed.$('leExport').onclick();await new Promise(setImmediate);changed.$('leB').value='2';changed.$('leB').oninput();releaseFirst();await changedExport;assert.equal(changed.calls.filter(x=>x.action==='loop/export').length,0);assert.match(changed.$('lePreviewBadge').textContent,/舊預覽/);assert.match(changed.$('lePreviewSnapshot').textContent,/B 第 4 幀/);await changed.flush();assert.match(changed.$('lePreviewSnapshot').textContent,/B 第 2 幀/);
 held=true;const jobExport=changed.$('leExport').onclick();await jobExport; // Fresh current non-endpoint B is a valid export check.
 assert.equal(changed.calls.filter(x=>x.action==='loop/export').length,1);
 const jobRace=harness();jobRace.window.loopRefresh(makeJob('job-race'));await jobRace.flush();jobRace.$('loopEditor').hidden=false;await jobRace.$('lePreview').onclick();jobRace.$('leTone').value='4';jobRace.$('leTone').oninput();jobRace.responses.set('loop/preview',data=>new Promise(resolve=>releaseFirst=()=>resolve({frame:data.frame,image:'preview:'+data.frame})));const acrossJob=jobRace.$('leExport').onclick();await new Promise(setImmediate);jobRace.window.loopRefresh(makeJob('other-job'));jobRace.window.loopRefresh(makeJob('job-race'));releaseFirst();await acrossJob;assert.equal(jobRace.calls.filter(x=>x.action==='loop/export').length,0);
 const endpointsRace=harness();endpointsRace.window.loopRefresh(makeJob('endpoints'));await endpointsRace.flush();endpointsRace.$('loopEditor').hidden=false;endpointsRace.$('lePurpose').value='loop';endpointsRace.$('leA').value='2';endpointsRace.$('leB').value='3';await endpointsRace.$('lePreview').onclick();held=true;endpointsRace.responses.set('loop/preview',data=>{if(held){held=false;return new Promise(resolve=>releaseFirst=()=>resolve({frame:data.frame,image:'preview:'+data.frame}))}return{frame:data.frame,image:'preview:'+data.frame}});const oldPair=endpointsRace.$('lePreview').onclick();endpointsRace.$('leEndpoints').onclick();releaseFirst();await oldPair;assert.equal(endpointsRace.$('lePreviewBadge').hidden,false);assert.match(endpointsRace.$('lePreviewSnapshot').textContent,/A 第 2 幀.*B 第 3 幀/);await endpointsRace.flush();assert.match(endpointsRace.$('lePreviewSnapshot').textContent,/A 第 1 幀.*B 第 4 幀/);
 // Original-only inspection is explicitly switched to the corrected draft before export; missing references cannot bypass validation.
 const original=harness();original.window.loopRefresh(makeJob('original'));await original.flush();original.$('leOriginal').checked=true;await original.$('leExport').onclick();assert.equal(original.$('leOriginal').checked,false);assert.equal(original.calls.filter(x=>x.action==='loop/export').length,1);assert.equal(original.calls.filter(x=>x.action==='loop/preview').at(-1).data.original,false);assert.match(original.$('lePreviewSnapshot').textContent,/修整草稿/);
 const missing=harness();missing.window.loopRefresh(makeJob('missing'));await missing.flush();missing.$('lePurpose').value='reference';await missing.$('leExport').onclick();assert.equal(missing.calls.filter(x=>x.action==='loop/export').length,0);assert.match(missing.$('leMessage').textContent,/參考圖/);
 const metrics=harness();metrics.window.loopRefresh(makeJob('metrics'));await metrics.flush();metrics.$('loopEditor').hidden=false;await metrics.$('leAlign').onclick();await metrics.flush();metrics.$('leA').value='2';metrics.$('leA').oninput();assert.match(metrics.$('leAlignReport').textContent,/參考幀.*不同/);assert.doesNotMatch(metrics.$('leAlignReport').textContent,/20 → 5/);metrics.$('leAlignEnabled').checked=false;metrics.$('leAlignEnabled').onchange();assert.match(metrics.$('leAlignReport').textContent,/未啟用/);
 metrics.responses.set('loop/load',()=>({recipe:null,versions:[{name:'aligned65',state:'complete',phase:'完成',recipe:{start:1,end:4,tone:0,contrast:0,sx:100,sy:100,alignment:{enabled:true,strength:65}}}]}));await metrics.$('leLoad').onclick();assert.match(metrics.$('leVersions').children[0].children[1].textContent,/局部對位 65%/);
 // Shared-reference closure is opt-in, persists independently of alignment, and preserves draft/export guards.
 const closure=harness(),closureJob={...makeJob('closure'),frames:Array.from({length:24},()=>({status:'done'}))};closure.window.loopRefresh(closureJob);await closure.flush();closure.$('loopEditor').hidden=false;await closure.$('lePreview').onclick();assert.equal(closure.calls.filter(x=>x.action==='loop/preview').at(-1).data.recipe.closure,undefined);assert.equal(Number(closure.$('leClosureHead').value),12);
 closure.$('lePurpose').value='tone';closure.$('leOriginal').checked=true;closure.$('leClosureEnabled').checked=true;closure.$('leClosureEnabled').onchange();await closure.flush();assert.equal(closure.$('lePurpose').value,'loop');assert.equal(closure.$('leOriginal').checked,false);assert.equal(Number(closure.$('leA').value),1);assert.equal(Number(closure.$('leB').value),24);assert.equal(Number(closure.$('leSeamN').value),12);assert.equal(closure.$('leClosureHeadTrack').hidden,false);assert.match(closure.$('leTimelineInfo').textContent,/頭段 1–12.*尾段 13–24/);assert.match(closure.$('lePreviewSnapshot').textContent,/共同基準 第 1 幀/);
 closure.$('leClosureReference').value='20';closure.$('leClosureReference').oninput();closure.$('leClosureHead').value='18';closure.$('leClosureHead').oninput();assert.equal(Number(closure.$('leClosureTail').value),6);closure.$('leClosureTail').value='22';closure.$('leClosureTail').oninput();assert.equal(Number(closure.$('leClosureHead').value),2);closure.$('leEnd').value='12';closure.$('leEnd').oninput();assert.equal(Number(closure.$('leClosureReference').value),12);assert.equal(Number(closure.$('leClosureTail').value),10);await closure.flush();
 await closure.$('leSave').onclick();const closureRecipe=closure.calls.find(x=>x.action==='loop/save').data.recipe;assert.deepEqual(JSON.parse(JSON.stringify(closureRecipe.closure)),{enabled:true,reference:12,head_frames:2,tail_frames:10});closure.$('leClosureEnabled').checked=false;closure.$('leClosureEnabled').onchange();assert.equal(closure.$('leClosureHeadTrack').hidden,true);closure.$('leUndo').onclick();assert.equal(closure.$('leClosureEnabled').checked,true);assert.equal(Number(closure.$('leClosureReference').value),12);
 const closureReload=harness(closure.storage);closureReload.window.loopRefresh(closureJob);await closureReload.flush();assert.equal(closureReload.$('leClosureEnabled').checked,true);assert.equal(Number(closureReload.$('leClosureHead').value),2);await closureReload.$('leExport').onclick();assert.equal(closureReload.calls.find(x=>x.action==='loop/export').data.recipe.closure.reference,12);closureReload.window.loopRefresh(makeJob('unrelated'));await closureReload.flush();assert.equal(closureReload.$('leClosureEnabled').checked,false);closureReload.window.loopRefresh(closureJob);await closureReload.flush();assert.equal(closureReload.$('leClosureEnabled').checked,true);
 closureReload.$('leEnd').value='3';closureReload.$('leEnd').oninput();assert.match(closureReload.$('leClosureStatus').textContent,/至少 4 幀/);assert.equal(closureReload.$('leClosureEnabled').disabled,false);const invalidCalls=closureReload.calls.filter(x=>x.action==='loop/save'||x.action==='loop/export').length;await closureReload.$('leSave').onclick();await closureReload.$('leExport').onclick();assert.equal(closureReload.calls.filter(x=>x.action==='loop/save'||x.action==='loop/export').length,invalidCalls);closureReload.$('leClosureEnabled').checked=false;closureReload.$('leClosureEnabled').onchange();assert.equal(closureReload.$('leClosureEnabled').disabled,true);
 const pendingClosure=harness();pendingClosure.window.loopRefresh({...makeJob('unfinished'),frames:[{status:'done'},{status:'done'},{status:'pending'},{status:'done'}]});await pendingClosure.flush();assert.equal(pendingClosure.$('leClosureEnabled').disabled,true);assert.match(pendingClosure.$('leClosureStatus').textContent,/完成.*去背/);
 const queuedClosureStorage=new Map([[prefix+'queued-closure',JSON.stringify({version:1,recipe:{start:2,end:20,ramp:10,closure:{enabled:true,reference:9,head_frames:8,tail_frames:9}},a:2,b:20,purpose:'loop'})]]),queuedClosure=harness(queuedClosureStorage);queuedClosure.window.loopRefresh({...closureJob,id:'queued-closure',frames:[],state:'running'});await queuedClosure.flush();queuedClosure.$('leTone').value='7';queuedClosure.$('leTone').oninput();assert.equal(JSON.parse(queuedClosureStorage.get(prefix+'queued-closure')).recipe.closure.reference,9);queuedClosure.window.loopRefresh({...closureJob,id:'queued-closure',state:'complete'});await queuedClosure.flush();assert.equal(Number(queuedClosure.$('leClosureReference').value),9);assert.equal(Number(queuedClosure.$('leClosureHead').value),8);
 const oldServer=harness();oldServer.window.loopRefresh(makeJob('old-server'));await oldServer.flush();oldServer.$('leClosureEnabled').checked=true;oldServer.$('leClosureEnabled').onchange();oldServer.responses.set('loop/preview',data=>({image:'preview:'+data.frame,frame:data.frame}));await oldServer.$('leExport').onclick();assert.equal(oldServer.calls.filter(x=>x.action==='loop/export').length,0);assert.match(oldServer.$('leMessage').textContent,/尚未支援首尾共同基準.*重新啟動/);
 const closureAlignment=harness();closureAlignment.window.loopRefresh(makeJob('closure-align'));await closureAlignment.flush();closureAlignment.$('loopEditor').hidden=false;await closureAlignment.$('leAlign').onclick();closureAlignment.$('leAlignStrength').value='65';closureAlignment.$('leAlignStrength').oninput();closureAlignment.$('leClosureEnabled').checked=true;closureAlignment.$('leClosureEnabled').onchange();await closureAlignment.flush();assert.match(closureAlignment.$('leAlignReport').textContent,/首尾共同基準.*不適用/);assert.doesNotMatch(closureAlignment.$('leAlignReport').textContent,/20 → 5/);assert.equal(closureAlignment.calls.filter(x=>x.action==='loop/preview').at(-1).data.recipe.alignment.strength,65);
 // Exported-PNG checks use exact version files and cache identity in an isolated read-only dialog.
 const output=harness();output.window.loopRefresh(makeJob('output'));await output.flush();output.$('loopEditor').hidden=false;await output.$('lePreview').onclick();const originalSnapshot=output.$('lePreviewSnapshot').textContent,version={name:'修整_002',state:'complete',phase:'完成',revision:'generation-one',recipe:{...closureRecipe,start:3,end:14},report:{frames:12,loop_closure:{enabled:true,endpoints_equal:true,max_channel_error:0,changed_pixels:0}}};output.responses.set('loop/load',()=>({recipe:null,versions:[version]}));await output.$('leLoad').onclick();let card=output.$('leVersions').children[0];assert.match(card.children[1].textContent,/共同基準 12.*頭 2／尾 10/);assert.match(card.children.find(x=>x.className==='closure-verification').textContent,/已回讀.*像素相同/);await card.children.find(x=>x.textContent==='核對輸出首尾').onclick();assert.equal(output.$('leOutputDialog').open,true);assert.match(output.$('leOutputSource').textContent,/修整_002.*1 幀.*12 幀.*不套用目前草稿/);assert.ok(output.imageLoads.some(x=>x.endsWith('frame_00000001.png?revision=generation-one')));assert.ok(output.imageLoads.some(x=>x.endsWith('frame_00000012.png?revision=generation-one')));assert.equal(output.$('lePreviewSnapshot').textContent,originalSnapshot);output.$('leOutputMode').value='diff';output.$('leOutputMode').oninput();assert.match(output.$('leOutputHint').textContent,/RGB 差異/);output.$('leOutputClose').onclick();assert.equal(output.$('leOutputDialog').open,false);
 version.revision='generation-two';version.report.loop_closure.endpoints_equal=false;version.report.loop_closure.changed_pixels=1;await output.$('leLoad').onclick();card=output.$('leVersions').children[0];assert.match(card.children.find(x=>x.className==='closure-verification').textContent,/仍有差異/);const outputPending=card.children.find(x=>x.textContent==='核對輸出首尾').onclick();output.window.loopRefresh(makeJob('new-output-job'));await outputPending;assert.equal(output.$('leOutputDialog').open,false);assert.ok(output.imageLoads.some(x=>x.endsWith('frame_00000012.png?revision=generation-two')));
 // Synthetic alpha pixels: RGB differences with equal alpha stay neutral; A-only/B-only contour becomes red/cyan.
 const contour=vm.runInNewContext('('+code.match(/function contourPixels\(a,b,background\)\{[\s\S]*?\n\}/)[0]+')');const opaqueA=new Uint8ClampedArray([0,0,0,255,255,255,255,255,0,0,0,0]),opaqueB=new Uint8ClampedArray([255,255,255,255,0,0,0,0,255,255,255,255]),pixels=contour(opaqueA,opaqueB,new Uint8ClampedArray(12));assert.equal(pixels[0],pixels[1]);assert.equal(pixels[1],pixels[2]);assert.ok(pixels[4]>pixels[5]&&pixels[4]>pixels[6]);assert.ok(pixels[9]>pixels[8]&&pixels[10]>pixels[8]);
 console.log('PASS: comparison sources, slider sync, frame events, task drafts, reference isolation, storage fallback, version hooks, ratio limits, hidden preview deferral, empty state, new-job extraction lifecycle and preserved draft range');
 console.log('PASS: split transform migration, normalization, undo, reset, task isolation, draft restoration and preview/export payloads');
 console.log('PASS: edge normalization, preserved mode-switch values, zoom-independent boundary dragging, one-sided guards, clamping and saved/exported edge recipes');
 console.log('PASS: alignment direction, opaque model persistence, comparison isolation, strength, stale tail guard, undo, clear, load/export, and async task/recipe race guards');
 console.log('PASS: committed preview labels, stale/error badges, current-strength report gating, pending/failed/decode export checks, duplicate/poll/frame/job/endpoint races, original/reference/hidden compatibility and synthetic alpha contour colors');
 console.log('PASS: opt-in shared reference, integer range/count clamping, disable/undo, save/export, task/queued draft persistence, unfinished/short-range guards, alignment coexistence, old-server rejection and isolated actual-version PNG inspection');
})().catch(error=>{console.error(error);process.exitCode=1});
