// Re-created output URLs must trigger a real media reload, and source refresh
// must invalidate dependent previews/reviews rather than only rebuild a menu.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const app=fs.readFileSync(__dirname+'/app.js','utf8'),transitions=fs.readFileSync(__dirname+'/transitions.js','utf8');
const take=(text,start,end)=>text.slice(text.indexOf(start),text.indexOf(end,text.indexOf(start)));

// Navigation changes visibility/focus only; every existing draft control remains mounted.
{
 const fields=new Map(),doc={activeElement:null},keys=['sources','tone','seams','output'],sections=keys.map(key=>({dataset:{trStepPanel:key},hidden:key!=='sources'}));
 function field(id){if(!fields.has(id))fields.set(id,{value:'',textContent:'',hidden:false,open:false,dataset:{},style:{},disabled:false,focus(){doc.activeElement=this},setAttribute(key,value){this[key]=value}});return fields.get(id)}
 const buttons=keys.map(key=>({dataset:{trStep:key},focus(){doc.activeElement=this},setAttribute(k,v){this[k]=v}})),events=[],navigation={el:field,document:doc,panel:{hidden:false,dataset:{},querySelectorAll(selector){return selector==='[data-tr-step]'?buttons:sections},querySelector(selector){return buttons.find(b=>selector.includes('"'+b.dataset.trStep+'"'))}},workflowSteps:keys.map((key,index)=>({key,label:['素材與順序','統一明暗','修好接點','預覽與輸出'][index],title:key})),workflowStep:'sources',projectManageAutoOpened:false,project:{id:'synthetic',clips:[{key:'a',label:'A',start:1,end:8,head:{dx:3},tail:{}},{key:'b',label:'B',start:1,end:8,head:{},tail:{}}],sequence:['a','b'],shared_tone:{tone:7,contrast:0}},identity:()=>({dx:0,dy:0,sx:100,sy:100,angle:0,cx:50,cy:50}),sourceOf:()=>({frames:8}),catalog:[{}],exportStatus:{},outputClips:[],completeVersions:()=>[],loadingProject:false,operation:false,toneBusy:false,seamBusy:false,comparison:{left:{},valid:false},compareState:'error',compareFailure:'synthetic load failure',previewRunning:false,inView:()=>true,regionEditor:{deactivate(){}},setMode(value){navigation.mode=value},queueCompare(){navigation.queued=true},window:{dispatchEvent:event=>events.push(event)},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail}}};
 vm.createContext(navigation);vm.runInContext(take(transitions,' function advancedTypes(',' function routeKeys('),navigation);const original=JSON.stringify(navigation.project);field('AdvancedSettings').open=true;field('GroupTone').value='7';doc.activeElement=field('GroupTone');navigation.renderWorkflow();assert.match(field('AppliedAdvanced').textContent,/手動變形/);assert.equal(field('AppliedAdvanced').hidden,false);assert.match(field('ManualToneBadge').textContent,/已套用/);
 for(const key of ['tone','seams','output','sources']){assert.equal(navigation.setWorkflowStep(key),true);assert.deepEqual(sections.filter(s=>!s.hidden).map(s=>s.dataset.trStepPanel),[key]);assert.equal(doc.activeElement.dataset.trStep,key,'focus is on the visible step button, never a hidden editor');assert.equal(navigation.mode,key==='output'?'output':'check')}
 assert.equal(JSON.stringify(navigation.project),original);assert.equal(field('GroupTone').value,'7');assert.equal(field('AdvancedSettings').open,true,'advanced disclosure state survives back/next');assert.equal(navigation.setWorkflowStep('invalid'),false);assert.equal(navigation.workflowStep,'sources');assert.ok(events.every(e=>e.type==='workbench:transition-step'));assert.equal(field('CompareStatus').hidden,false);assert.match(field('CompareStatus').textContent,/更新失敗/);navigation.comparison.valid=true;navigation.renderCompareStatus();assert.equal(field('CompareStatus').hidden,true);
 navigation.project=null;navigation.renderWorkflow();assert.equal(field('ProjectManage').open,true);assert.match(field('StageAction').textContent,/建立/);navigation.project={clips:[]};navigation.renderWorkflow();assert.match(field('StageAction').textContent,/選擇動畫/);navigation.project={clips:[{key:'only'}]};navigation.renderWorkflow();assert.match(field('StageAction').textContent,/第二段/);
 const markup=fs.readFileSync(__dirname+'/transitions_panel.html','utf8');for(const key of keys)assert.match(markup,new RegExp('data-tr-step-panel="'+key+'"'));assert.doesNotMatch(markup,/<details id="trAdvancedSettings"[^>]*\bopen\b/);assert.ok(markup.indexOf('id="trAlign"')>markup.indexOf('id="trAdvancedSettings"'));assert.ok(markup.indexOf('id="trMetrics"')>markup.indexOf('id="trAdvancedSettings"'));assert.ok(markup.indexOf('id="trExport"')>markup.indexOf('data-tr-step-panel="output"'));
 console.log('PASS: four-step progressive disclosure, visible keyboard focus, unchanged draft/inputs, active advanced summary, explicit zero-state actions and persistent stale-preview warning');
}
const state={version:'edit:修整'},elements=new Map();let loads=0,saved=0;
function $(id){if(!elements.has(id))elements.set(id,{value:'',children:[],replaceChildren(){this.children=[]},append(v){this.children.push(v)},pause(){},load(){loads++},removeAttribute(){}});return elements.get(id)}
const job={id:'a',frames:[{},{},{},{}],config:{fps:12},dimensions:[32,40]},versionLists=new Map([['a',[{name:'修整',state:'complete',revision:'first',report:{frames:4,fps:12,dimensions:[32,40]}}]]]);
const box={$ ,versionLists,videoNames:()=>({}),fpsNumber:Number,recipeSummary:()=>'',file:(j,p)=>j.id+'/'+p,path:()=>'',viewState:()=>state,saveViews(){},saveVideoPosition(){saved++},lastVideo:'',videoOptionsSignature:'',videoEventSignature:'',loadingVideo:false,activeVideo:null,document:{createElement:()=>({})},window:{dispatchEvent(){}},CustomEvent:class{}};
vm.createContext(box);vm.runInContext(take(app,'function availableVideos(','window.workbenchSetVersions='),box);
box.showVideo(job);const firstUrl=$('video').src;
box.showVideo(job);assert.equal(loads,1);
versionLists.get('a')[0].revision='recreated';box.showVideo(job);
assert.equal(loads,2);assert.notEqual($('video').src,firstUrl);assert.equal(box.activeVideo.frames,4);

(async()=>{
 const source={job_id:'a',version:'修整',revision:'first',frames:8,dimensions:[32,40],fps:12},clip={key:'clip',job_id:'a',version:'修整',label:'A-1',start:2,end:8,head_frames:3,tail_frames:3};
 const log=[],refresh={catalog:[source],project:{id:'p',clips:[clip],reviews:{'clip>clip':{verdict:'pass'}}},comparison:{valid:true},compareEpoch:0,compareTimer:0,pairResults:new Map([['clip>clip',{}]]),el:()=>({value:'0'}),call:async()=>({sources:[{...source,revision:'recreated',frames:3}]}),renderSources:previous=>log.push(['selected',previous]),sourceOf:c=>refresh.catalog.find(s=>s.job_id===c.job_id&&s.version===c.version),clearPreview:()=>log.push('clearPreview'),releaseOutput:()=>log.push('releaseOutput'),drawComparison(){},clearTimeout(){},pushHistory(){},markDirty:()=>log.push('dirty'),renderClips(){},renderPairs(){},message:(...v)=>log.push(v),queueCompare:()=>log.push('compare'),reloadVersions:async()=>log.push('versions')};
 vm.createContext(refresh);vm.runInContext(take(transitions,' let catalogEpoch=',' async function refreshProjects('),refresh);
 await refresh.refreshCatalog();
 assert.equal(refresh.comparison,null);assert.equal(clip.end,3);assert.equal(clip.head_frames+clip.tail_frames,2);assert.equal(Object.keys(refresh.project.reviews).length,0);assert.equal(refresh.pairResults.size,0);
 assert.ok(log.includes('releaseOutput'));assert.ok(log.includes('compare'));assert.ok(log.includes('versions'));assert.equal(log.find(Array.isArray)[1].revision,'first');
 // Unchanged sources still retry a previously failed comparison.
 log.length=0;await refresh.refreshCatalog();assert.ok(log.includes('compare'));assert.ok(!log.includes('dirty'));
 const apiBox={fetch:async()=>{throw new TypeError('Failed to fetch')},window:{APP_TOKEN:'token'}};vm.createContext(apiBox);vm.runInContext(take(app,'async function api(','function file('),apiBox);
 await assert.rejects(apiBox.api('jobs'),/無法連線到工作台/);
 // Endpoint alignment belongs to its source clip/side, not the currently inspected pair.
 const clone=v=>JSON.parse(JSON.stringify(v)),identity=()=>({dx:0,dy:0,sx:100,sy:100,angle:0,cx:50,cy:50});
 const clipA={key:'a',job_id:'job-a',version:'original',label:'A',start:1,end:8,head:identity(),tail:identity()},clipB={key:'b',job_id:'job-b',version:'original',label:'B',start:2,end:9,head:identity(),tail:identity()};
 const fields=new Map(),alignmentLog=[],alignmentBox={project:{id:'group',clips:[clipA,clipB]},loadEpoch:1,revision:0,aKey:'a',bKey:'b',alignmentBusy:false,alignmentEpoch:0,alignmentOwner:'',alignmentNotice:'',alignmentError:false,alignmentStrengthSnapshot:null,alignmentInvalid:new Map(),alignmentReports:new Map(),clone,
  el(id){if(!fields.has(id))fields.set(id,{value:id==='EditSide'?'tail':'',checked:false});return fields.get(id)},currentClip(){return alignmentBox.project.clips.find(c=>c.key===(alignmentBox.el('EditSide').value==='tail'?alignmentBox.aKey:alignmentBox.bKey))},renderAlignment(){},pushHistory(){},invalidateClip:key=>alignmentLog.push(['invalid',key]),markDirty(){alignmentBox.revision++},renderEditor(){},queueCompare(){},
  async call(action,data){alignmentLog.push([action,data]);const a=data.project.clips.find(c=>c.key===data.a),b=data.project.clips.find(c=>c.key===data.b),s=data.side==='tail'?a:b,r=data.side==='tail'?b:a,sourceSide=data.side,referenceSide=data.side==='tail'?'head':'tail';return{alignment:{enabled:true,strength:100,model:{opaque:{field:[2,4]},provenance:{scope:'transition',source:{job_id:s.job_id,version:s.version,clip_key:s.key,side:sourceSide,frame:sourceSide==='tail'?s.end:s.start},reference:{job_id:r.job_id,version:r.version,clip_key:r.key,side:referenceSide,frame:referenceSide==='tail'?r.end:r.start}}}}}}};
 vm.createContext(alignmentBox);vm.runInContext(take(transitions,' function alignmentKey(',' function alignmentReportText('),alignmentBox);vm.runInContext(take(transitions," el('Align').onclick="," el('ResetTransform').onclick="),alignmentBox);
 await alignmentBox.el('Align').onclick();assert.equal(alignmentLog.find(v=>v[0]==='align')[1].side,'tail');assert.equal(clipA.tail.alignment.model.provenance.source.frame,8);assert.equal(clipA.tail.alignment.model.provenance.reference.frame,2);assert.equal(clipB.head.alignment,undefined);
 alignmentBox.el('EditSide').value='head';await alignmentBox.el('Align').onclick();assert.equal(clipB.head.alignment.model.provenance.source.frame,2);assert.equal(clipB.head.alignment.model.provenance.reference.frame,8);assert.equal(clipA.tail.alignment.enabled,true);
 alignmentBox.aKey='b';alignmentBox.bKey='a';assert.equal(alignmentBox.alignmentReason(clipA,'tail'),'');clipB.tone=15;clipB.head.dx=4;assert.equal(alignmentBox.alignmentReason(clipA,'tail'),'');alignmentBox.assertAlignmentSources();clipA.end=7;assert.match(alignmentBox.alignmentReason(clipA,'tail'),/來源或首尾幀/);assert.throws(()=>alignmentBox.assertAlignmentSources(),/重新計算或清除對位/);assert.equal(clipA.tail.alignment.enabled,true);clipA.end=8;
 alignmentBox.aKey='a';alignmentBox.bKey='b';alignmentBox.el('EditSide').value='head';alignmentBox.el('AlignClear').onclick();assert.equal(clipB.head.alignment,undefined);assert.equal(clipA.tail.alignment.enabled,true);
 let solve;alignmentBox.call=()=>new Promise(resolve=>solve=resolve);const pending=alignmentBox.el('Align').onclick();alignmentBox.revision++;solve({alignment:{enabled:true,strength:100,model:{unexpected:true}}});await pending;assert.equal(clipB.head.alignment,undefined);assert.match(alignmentBox.alignmentNotice,/設定或檢查位置已變更/);
 console.log('PASS: regenerated media reload; refreshed source pixels invalidate previews/reviews and ranges; clear connection failure message');
 console.log('PASS: independent transition tail/head alignment, endpoint direction, pair-inspection isolation, reference snapshot, explicit stale-source guard, clear and async revision protection');
})().catch(error=>{console.error(error);process.exitCode=1});

(async()=>{
 const plain=v=>JSON.parse(JSON.stringify(v)),baseClip=key=>({key,label:key.toUpperCase(),job_id:'synthetic-'+key,version:'original',start:1,end:8,head_frames:2,tail_frames:2,tone:0,contrast:0,head:{dx:0},tail:{dx:0}}),clips=[baseClip('a'),baseClip('b')],model={enabled:true,schema:1,sequence:['a','b'],binding:'synthetic-binding',links:[{a:'a',b:'b',reference:'b_head',anchor_id:'anchor-ab',sha256:'sha-ab',dimensions:[16,32]},{a:'b',b:'a',reference:'b_head',anchor_id:'anchor-ba',sha256:'sha-ba',dimensions:[16,32]}]};let sourceRevision='first';
 const seam={project:{id:'p',clips,sequence:['a','b'],shared_tone:{tone:0,contrast:0},seam_closure:plain(model)},seamReferences:{},seamSnapshots:new Map(),seamServerError:'',seamServerErrorKey:'',pairKey:(a,b)=>a+'>'+b,sourceOf:()=>({revision:sourceRevision})};vm.createContext(seam);vm.runInContext(take(transitions,' function routeKeys(',' function renderLayout('),seam);vm.runInContext(take(transitions,' function seamModelKey(',' function renderSeams('),seam);seam.rememberSeamSnapshot();seam.assertSeamsReady();clips[0].label='Renamed';clips[0].head_frames=3;seam.assertSeamsReady();clips[0].tone=5;assert.throws(()=>seam.assertSeamsReady(),/重新建立/);clips[0].tone=0;clips[0].tail.dx=1;assert.throws(()=>seam.assertSeamsReady(),/重新建立/);clips[0].tail.dx=0;sourceRevision='recreated';assert.throws(()=>seam.assertSeamsReady(),/來源/);sourceRevision='first';seam.seamReferences['a>b']='a_tail';assert.throws(()=>seam.assertSeamsReady(),/參考選擇/);delete seam.seamReferences['a>b'];seam.project.sequence=['b','a'];assert.throws(()=>seam.assertSeamsReady(),/順序/);seam.project.sequence=['a','b'];clips[0].head_frames=1;assert.throws(()=>seam.assertSeamsReady(),/至少 2 幀/);assert.equal(clips[0].head_frames,1,'invalid windows are never silently changed');clips[0].head_frames=7;assert.throws(()=>seam.assertSeamsReady(),/不可超過/);clips[0].head_frames=2;seam.assertSeamsReady();seam.project.seam_closure.enabled=false;clips[0].tone=5;seam.assertSeamsReady();clips[0].tone=0;seam.project.seam_closure.enabled=true;
 vm.runInContext(take(transitions,' function seamContractSignature(',' function contourPixels('),seam);const reordered=plain(seam.project);reordered.seam_closure={links:reordered.seam_closure.links,binding:model.binding,schema:1,enabled:true,sequence:['a','b']};seam.assertFeatureRoundTrip(seam.project,reordered);reordered.seam_closure.links[0].sha256='lost';assert.throws(()=>seam.assertFeatureRoundTrip(seam.project,reordered),/完整保留共用接點/);
 let resolveBuild;const elements=new Map();Object.assign(seam,{operation:false,toneBusy:false,seamBusy:false,loadingProject:false,revision:1,loadEpoch:1,seamEpoch:0,seamNotice:'',clone:plain,normalizeProject:plain,el(id){if(!elements.has(id))elements.set(id,{value:'',dataset:{},checked:false});return elements.get(id)},renderProjectState(){},renderClips(){},renderEditor(){},message(){},invalidateAll(){},markDirty(){seam.revision++},pushHistory(){seam.undo=plain(seam.project)},call:()=>new Promise(resolve=>resolveBuild=resolve)});vm.runInContext(take(transitions," el('BuildSeams').onclick="," el('SeamEnabled').onchange="),seam);
 delete seam.project.seam_closure;let build=seam.el('BuildSeams').onclick();seam.revision++;resolveBuild({project:{...plain(seam.project),seam_closure:plain(model)}});await build;assert.equal(seam.project.seam_closure,undefined);assert.match(seam.seamNotice,/未套用舊基準/);build=seam.el('BuildSeams').onclick();resolveBuild({project:{...plain(seam.project),seam_closure:plain(model)}});await build;assert.equal(seam.project.seam_closure.enabled,true);assert.equal(seam.undo.seam_closure,undefined);assert.equal(seam.seamBusy,false);seam.assertSeamsReady();
 const skipFields=new Map(),play={outputClips:[{key:'a',frames:3,fps:24},{key:'b',frames:3,fps:24}],outputSequence:['a','b'],outputSequenceIndex:0,outputKey:'a',outputFrame:2,queuedKey:'',outputSeamVerification:{enabled:true,pairs:[{a:'a',b:'b',endpoints_equal:true,same_fps:true,can_skip_duplicate_head:true}]},fps:Number,el(id){if(!skipFields.has(id))skipFields.set(id,{value:id==='PlaybackMode'?'sequence':'',checked:id==='SkipSeam'});return skipFields.get(id)}};vm.createContext(play);vm.runInContext(take(transitions,' function verifiedSkipPair(',' function renderOutputSeams('),play);vm.runInContext(take(transitions,' function nextOutputKey(',' function outputTick('),play);play.advanceOutput();assert.equal(play.outputKey,'b');assert.equal(play.outputFrame,1,'verified matching FPS auto route skips exactly one head frame');play.outputFrame=2;play.advanceOutput();assert.equal(play.outputKey,'a');assert.equal(play.outputFrame,0,'unverified wrap never skips');play.outputFrame=2;play.queuedKey='b';play.advanceOutput();assert.equal(play.outputFrame,0,'manual queued switch retains head');play.outputClips[1].fps=30;assert.equal(play.verifiedSkipPair('a','b'),false);play.outputClips[1].fps=24;play.outputSeamVerification.pairs[0].endpoints_equal=false;assert.equal(play.verifiedSkipPair('a','b'),false);play.outputSeamVerification=null;assert.equal(play.verifiedSkipPair('a','b'),false);
 const old={assertSeamsReady(){},api:async()=>({features:{transition_tone:1,transition_sequence:2}})};vm.createContext(old);vm.runInContext(take(transitions,' const call=',' const pairKey='),old);await assert.rejects(vm.runInContext("call('compare',{project:{seam_closure:{enabled:true}}})",old),/尚未支援共用接點/);
 console.log('PASS: shared seam snapshot invalidation, adjustable nonoverlapping windows, literal closure round-trip, stale build rejection/undo, verified immutable-output-only duplicate skip and old-server guard');
})().catch(error=>{console.error(error);process.exitCode=1});

// Multi-expression workflow uses only synthetic clips/pixels. No user image is opened.
(async()=>{
 const plain=v=>JSON.parse(JSON.stringify(v)),clipList=[{key:'aa',label:'AA → AB',frames:2,fps:10,dimensions:[4,8],png_pattern:'aa/%02d.png'},{key:'bb',label:'AB → BB',frames:3,fps:20,dimensions:[4,8],png_pattern:'bb/%02d.png'},{key:'cc',label:'BB → AA',frames:2,fps:10,dimensions:[4,8],png_pattern:'cc/%02d.png'}];
 const fields=new Map(),field=id=>{if(!fields.has(id))fields.set(id,{value:id==='PlaybackMode'?'sequence':id==='OutputSpeed'?'0.1':'',checked:false,textContent:'',dataset:{},style:{},children:[],replaceChildren(){this.children=[]},append(v){this.children.push(v)}});return fields.get(id)};
 const flow={project:{id:'synthetic',clips:clipList,sequence:['cc','aa','bb']},el:field,outputClips:clipList,outputSequence:['bb','cc','aa'],outputSequenceIndex:0,outputKey:'bb',outputFrame:0,queuedKey:'',operation:false,toneBusy:false,seamBusy:false,history:[],pushHistory(){flow.history.push(plain(flow.project))},markDirty(){},renderClips(){},message(){},Math};
 vm.createContext(flow);vm.runInContext(take(transitions,' function routeKeys(',' function renderLayout('),flow);vm.runInContext(take(transitions,' function moveClip(',' function renderTone('),flow);vm.runInContext(take(transitions,' function nextOutputKey(',' function outputTick('),flow);
 assert.deepEqual(plain(flow.routeKeys(clipList,[])),['aa','bb','cc']);assert.deepEqual(plain(flow.routeKeys(clipList,['bb','aa','bb'])),['bb','aa','bb'],'legacy repeat/subset route is preserved');
 assert.equal(flow.fullRoute(clipList,['bb','aa','bb']),false);flow.moveClip('aa',-1);assert.deepEqual(flow.project.sequence,['aa','cc','bb']);assert.equal(flow.project.sequence_version,2);assert.equal(flow.history.length,1);
 const chainBefore=flow.routeText(clipList,flow.project.sequence);clipList[0].label='Renamed';assert.match(flow.routeText(clipList,flow.project.sequence),/1\. Renamed/);assert.notEqual(chainBefore,flow.routeText(clipList,flow.project.sequence));
 assert.deepEqual(plain(flow.sequencePairs()),[{a:'aa',b:'cc'},{a:'cc',b:'bb'},{a:'bb',b:'aa'}]);
 flow.outputFrame=2;flow.advanceOutput();assert.equal(flow.outputKey,'cc','saved output route wins over draft sequence');assert.equal(flow.outputFrame,0);flow.outputFrame=1;flow.advanceOutput();assert.equal(flow.outputKey,'aa');flow.outputFrame=1;flow.advanceOutput();assert.equal(flow.outputKey,'bb','last wraps to first');
 flow.outputSequence=['aa','bb','aa'];flow.outputKey='aa';flow.outputSequenceIndex=0;flow.outputFrame=1;flow.advanceOutput();assert.equal(flow.outputKey,'bb');flow.outputFrame=2;flow.advanceOutput();assert.equal(flow.outputKey,'aa');assert.equal(flow.outputSequenceIndex,2);flow.outputFrame=1;flow.advanceOutput();assert.equal(flow.outputSequenceIndex,0,'legacy duplicate route keeps its index');
 flow.queuedKey='cc';flow.outputFrame=0;flow.advanceOutput();assert.equal(flow.outputKey,'aa','queued switch waits for final frame');flow.advanceOutput();assert.equal(flow.outputKey,'cc');assert.equal(flow.queuedKey,'');
 field('PlaybackMode').value='single';flow.outputFrame=1;flow.advanceOutput();assert.equal(flow.outputKey,'cc');field('PlaybackMode').value='sequence';
 flow.outputRunning=true;flow.outputClock=100;flow.outputElapsed=0;flow.mode='output';flow.inView=()=>true;flow.requestAnimationFrame=()=>1;flow.drawOutput=()=>{};vm.runInContext(take(transitions,' function outputTick(',' function startOutput('),flow);flow.outputTick(200);assert.equal(flow.outputElapsed,10,'0.1× accrues exactly one tenth of elapsed time');

 const version={name:'vSynthetic',clips:clipList,sequence:['cc','bb','aa']},preload={project:{id:'synthetic',sequence:['aa','bb','cc']},loadingProject:false,loadEpoch:2,outputEpoch:0,outputCache:new Map(),pendingOutputCache:null,outputClips:[],outputSequence:[],outputSequenceIndex:0,memoryLimit:384*1024*1024,el:field,selectedOutput:()=>version,releaseOutput(){},versionName:v=>v.name,fps:Number,createImageBitmap:async(blob,options)=>({width:options.resizeWidth,height:options.resizeHeight,close(){}}),fetch:async()=>({ok:true,blob:async()=>({synthetic:true})}),AbortController,renderVersions(){},renderEmotionButtons(){},renderOutputSeams(){},renderWorkflow(){},drawOutput(){},message(){},startOutput(){preload.started=true}};
 vm.createContext(preload);vm.runInContext(take(transitions,' function routeKeys(',' function renderLayout('),preload);vm.runInContext(take(transitions,' function transitionFile(',' function pauseOutput('),preload);vm.runInContext(take(transitions,' async function preloadOutput(',' function renderEmotionButtons('),preload);await preload.preloadOutput();assert.deepEqual(plain(preload.outputSequence),version.sequence);assert.equal(preload.outputKey,'cc');assert.equal(preload.outputReadyVersion,'vSynthetic');assert.equal(preload.started,true);assert.match(field('OutputSequence').textContent,/1\. BB → AA/);

 const pixels={Uint8ClampedArray};vm.createContext(pixels);vm.runInContext(take(transitions,' function contourPixels(',' function drawContour('),pixels);
 const contour=pixels.contourPixels(new Uint8ClampedArray([7,8,9,255,1,2,3,0,255,255,255,255,255,0,0,0]),new Uint8ClampedArray([1,2,3,0,7,8,9,255,255,255,255,255,0,255,0,0]),new Uint8ClampedArray(16));assert.deepEqual([...contour.slice(0,3)],[255,65,85]);assert.deepEqual([...contour.slice(4,7)],[30,220,255]);assert.equal(contour[8],contour[9]);assert.deepEqual([...contour.slice(12,15)],[0,0,0],'hidden RGB cannot create false contour');

 let listener,saveCount=0,visible=true;const keyboard={document:{addEventListener:(name,fn)=>listener=fn},inView:()=>visible,el:()=>({disabled:false,onclick:()=>saveCount++})};vm.createContext(keyboard);vm.runInContext(take(transitions," document.addEventListener('keydown'"," el('Layout').onchange="),keyboard);let prevented=0;listener({ctrlKey:true,key:'s',preventDefault:()=>prevented++});assert.equal(saveCount,1);visible=false;listener({ctrlKey:true,key:'s',preventDefault:()=>prevented++});assert.equal(saveCount,1);assert.equal(prevented,1,'Ctrl+S only intercepts active transition workspace');

 let apiCalls=0;const guard={api:async action=>{if(action==='version')return{features:{transitions:1}};apiCalls++;return{}}};vm.createContext(guard);vm.runInContext(take(transitions,' const call=',' const pairKey='),guard);await assert.rejects(vm.runInContext("call('analyze',{scope:'sequence'})",guard),/重新啟動/);await assert.rejects(vm.runInContext("call('compare',{project:{shared_tone:{tone:8,contrast:0}}})",guard),/重新啟動/);assert.equal(apiCalls,0,'old service never receives an unsupported edit');

 let resolveTone;const toneFields=new Map(),tone={project:{id:'p',clips:[{key:'a'},{key:'b'}],shared_tone:{tone:0,contrast:0}},toneBusy:false,seamBusy:false,operation:false,revision:3,loadEpoch:1,toneEpoch:0,toneNotice:'',clone:plain,normalizeProject:plain,el(id){if(!toneFields.has(id))toneFields.set(id,{value:id==='ToneReference'?'a':''});return toneFields.get(id)},renderProjectState(){},renderClips(){},renderEditor(){},pushHistory(){tone.savedUndo=plain(tone.project)},invalidateAll(){},markDirty(){tone.revision++},message(){},call:()=>new Promise(resolve=>resolveTone=resolve)};vm.createContext(tone);vm.runInContext(take(transitions," el('MatchTone').onclick="," el('ClearToneMatch').onclick="),tone);
 const pending=tone.el('MatchTone').onclick();tone.revision++;resolveTone({project:{...tone.project,tone_match:{enabled:true,adjustments:{a:{tone:0}}}}});await pending;assert.equal(tone.project.tone_match,undefined);assert.match(tone.toneNotice,/未套用/);
 const successful=tone.el('MatchTone').onclick();resolveTone({project:{...tone.project,tone_match:{enabled:true,reference:'a',adjustments:{a:{tone:0},b:{tone:12}}}}});await successful;assert.equal(tone.project.tone_match.enabled,true);assert.equal(tone.savedUndo.tone_match,undefined);assert.equal(tone.toneBusy,false);
 const switching=tone.el('MatchTone').onclick();tone.loadEpoch++;tone.toneEpoch++;tone.project={id:'other',clips:[]};resolveTone({project:{id:'p',clips:[],tone_match:{enabled:true,adjustments:{}}}});await switching;assert.equal(tone.project.id,'other','calibration cannot overwrite another project');

 const html=fs.readFileSync(__dirname+'/transitions_panel.html','utf8');assert.match(html,/id="trPreviewSpeed"><option value="0\.1"/);assert.match(html,/id="trOutputSpeed"><option value="0\.1"/);assert.match(html,/<details id="trMatrixSection"[^>]*>/);assert.doesNotMatch(html,/<details id="trMatrixSection"[^>]*\bopen\b/);assert.match(html,/value="contour"/);
 const reportBox={el:field,project:{clips:[]},toneBusy:false,seamBusy:false,document:{createElement:()=>({dataset:{}})}};vm.createContext(reportBox);vm.runInContext(take(transitions,' function renderToneReport(',' function renderTone('),reportBox);const reportWarning=reportBox.renderToneReport({clips:[{label:'Flat sample <b>',before:{error:8},after:{error:8},warnings:['層次不足，保留原設定']},{label:'Normal',before:{error:9},after:{error:1.5},warnings:[]}]});assert.match(reportWarning,/1 段需檢查.*層次不足/);assert.equal(field('ToneResults').hidden,false);assert.match(field('ToneResultRows').children[0].textContent,/Flat sample <b> · 明暗誤差 8.00 → 8.00/);assert.equal(field('ToneResultRows').children[0].innerHTML,undefined);assert.match(field('ToneResultsSummary').textContent,/1 段需檢查/);reportBox.renderToneReport(null);assert.equal(field('ToneResults').hidden,true);
 field('OutputInfo').textContent='Old version 672 × 1216';field('OutputInfo').dataset.warning='true';field('OutputEmpty').textContent='正在預載…';field('OutputViewport').style.maxWidth='250px';field('OutputCanvas').style.width='200px';const released={el:field,pauseOutput(){},outputEpoch:1,outputAbort:null,outputCache:new Map(),pendingOutputCache:null,disposeCache:cache=>cache.clear(),renderOutputSeams(){}};vm.createContext(released);vm.runInContext(take(transitions,' function releaseOutput(',' function selectedOutput('),released);released.releaseOutput();assert.match(field('OutputInfo').textContent,/請選擇版本/);assert.equal(field('OutputInfo').dataset.warning,'false');assert.doesNotMatch(field('OutputEmpty').textContent,/正在預載/);assert.equal(field('OutputViewport').style.maxWidth,'');assert.equal(field('OutputCanvas').style.width,'');assert.equal(field('OutputSequence').textContent,'');
 const scheduled=[],initialLoad={project:null,loadEpoch:0,loadingProject:false,toneEpoch:0,toneBusy:false,seamBusy:false,seamEpoch:0,rememberSeamSnapshot(){},seamModelKey:()=>'',compareEpoch:0,compareTimer:0,pairResults:new Map(),localStorage:{getItem:()=>null},call:async()=>({project:{id:'loaded',clips:clipList,sequence:clipList.map(c=>c.key)},versions:[]}),normalizeProject:plain,rememberDraft(){},clearPreview(){},releaseOutput(){},renderVersions(){},drawComparison(){},clearTimeout(){},renderProjectState(){},message(){},renderProjectList(){},renderClips(){},renderPairs(){},pollStatus(){},queueCompare(){scheduled.push(initialLoad.loadingProject)},notify(){}};vm.createContext(initialLoad);vm.runInContext(take(transitions,' async function loadProject(',' async function saveProject('),initialLoad);await initialLoad.loadProject('loaded');assert.equal(initialLoad.project.id,'loaded');assert.equal(scheduled.at(-1),false,'loaded project queues automatic comparison after loading guard is cleared');
 const rows=clipList.map(c=>({dataset:{key:c.key},buttons:[{dataset:{move:'-1'}},{dataset:{move:'1'}},{dataset:{}}],querySelectorAll(){return this.buttons}})),controls={project:{clips:clipList,sequence:clipList.map(c=>c.key)},operation:true,toneBusy:false,seamBusy:false,loadingProject:true,el:()=>({children:rows})};vm.createContext(controls);vm.runInContext(take(transitions,' function routeKeys(',' function renderLayout('),controls);vm.runInContext(take(transitions,' function renderClipControls(',' function renderClips('),controls);controls.renderClipControls();assert.ok(rows.every(r=>r.buttons.every(b=>b.disabled)));controls.operation=controls.loadingProject=false;controls.renderClipControls();assert.equal(rows[0].buttons[0].disabled,true);assert.equal(rows[0].buttons[1].disabled,false);assert.equal(rows[0].buttons[2].disabled,false);assert.ok(rows[1].buttons.every(b=>!b.disabled));assert.equal(rows[2].buttons[1].disabled,true);controls.operation=true;controls.renderClipControls();controls.operation=false;controls.renderClipControls();assert.ok(rows[1].buttons.every(b=>!b.disabled),'finishing save restores ordering controls without rebuilding focused inputs');
 console.log('PASS: editable numbered route, saved-version autoplay/wrap, legacy routes, queued switches, 0.1× timing, signed-alpha contour, scoped Ctrl+S, old-server guard, tone-match undo and async race protection');
})().catch(error=>{console.error(error);process.exitCode=1});
