// Synthetic state-machine regressions for the consolidated boundary editor.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const source=fs.readFileSync(__dirname+'/transitions.js','utf8'),take=(start,end)=>{const a=source.indexOf(start),b=source.indexOf(end,a);assert.ok(a>=0&&b>a,start);return source.slice(a,b)},plain=v=>JSON.parse(JSON.stringify(v));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}},tick=()=>new Promise(r=>setImmediate(r));
const identity=()=>({dx:0,dy:0,sx:100,sy:100,angle:0,cx:50,cy:50}),clip=key=>({key,label:key,job_id:key,version:'original',start:1,end:12,head_frames:3,tail_frames:3,tone:0,contrast:0,head:identity(),tail:identity()});
const element=tag=>({tag,dataset:{},textContent:'',children:[],replaceChildren(){this.children=[]},append(...nodes){this.children.push(...nodes)}});
function context(extra={}){const fields=new Map(),s={project:{id:'synthetic',name:'Synthetic',clips:[clip('a'),clip('b'),clip('c')],sequence:['a','b','c'],route_mode:'loop',reviews:{},shared_tone:{tone:0,contrast:0}},catalog:[],revision:0,loadEpoch:1,loadingProject:false,operation:false,toneBusy:false,seamBusy:false,finishBusy:false,finishEpoch:0,finishApplied:false,finishPlan:null,finishPlanRevision:-1,finishReviewItems:[],finishInspection:null,history:[],redoHistory:[],seamReferences:{},seamHistoryReferences:new WeakMap(),seamSnapshots:new Map(),aKey:'a',bKey:'b',compareEpoch:0,comparison:null,pairResults:new Map(),dirty:false,previewPreparing:false,previewRunning:false,previewOwner:null,previewIdentity:()=>'',draftRouteIdentity:'',outputRecipeIdentity:p=>JSON.stringify(p),outputKind:'export',outputRouteMode:'loop',autosaveTimer:null,autosaveBusy:false,autosaveError:'',saveQueues:new Map(),clone:plain,identity,crypto,
  el(id){if(!fields.has(id))fields.set(id,{value:id==='PlaybackMode'?'sequence':'',checked:false,textContent:'',disabled:false,dataset:{},children:[],replaceChildren(){this.children=[]},append(x){this.children.push(x)},querySelectorAll(){return[]}});return fields.get(id)},
  sourceOf:c=>({frames:12,dimensions:[20,40],fps:12,revision:'source'}),renderProjectState(){},renderProjectList(){},renderClips(){},renderPairs(){},renderEditor(){},renderVersions(){},rememberDraft(){},notify(){},message(text,error){s.lastMessage={text,error}},clearPreview(){},drawComparison(){},queueCompare(){},invalidateAll(){},pauseOutput(){s.outputRunning=false},updatePlaybackLabels(){},rememberSeamSnapshot(){},assertAlignmentSources(){},assertSeamsReady(){},assertFeatureRoundTrip(){},setTimeout(){return 1},clearTimeout(){},...extra};vm.createContext(s);vm.runInContext(take(' function routeKeys(',' function renderLayout('),s);vm.runInContext(take(' function normalizeProject(',' function renderFinish('),s);vm.runInContext(take(' function pushHistory(',' function renderProjectState('),s);return s}
(async()=>{
 // Required topology is identical for single-loop and multi-transition editing.
 const routes=context();assert.deepEqual(plain(routes.sequencePairs()),[{a:'a',b:'b'},{a:'b',b:'c'},{a:'c',b:'a'}]);routes.project.route_mode='open';assert.deepEqual(plain(routes.sequencePairs()),[{a:'a',b:'b'},{a:'b',b:'c'}]);routes.project.clips=[clip('a')];routes.project.sequence=['a'];assert.deepEqual(plain(routes.sequencePairs()),[]);routes.project.route_mode='loop';assert.deepEqual(plain(routes.sequencePairs()),[{a:'a',b:'a'}]);
 const play=context({outputClips:[{key:'a',frames:2,fps:12},{key:'b',frames:2,fps:12}],outputSequence:['a','b'],outputSequenceIndex:0,outputKey:'a',outputFrame:1,outputElapsed:200,outputRunning:true,queuedKey:'',outputRouteMode:'open'});vm.runInContext(take(' function nextOutputKey(',' function outputTick('),play);play.advanceOutput();assert.equal(play.outputKey,'b');play.outputFrame=1;play.advanceOutput();assert.equal(play.outputKey,'b');assert.equal(play.outputFrame,1);assert.equal(play.outputRunning,false,'open route pauses on actual final frame');assert.equal(play.nextOutputKey(),'');play.outputRouteMode='loop';play.outputRunning=true;play.advanceOutput();assert.equal(play.outputKey,'a');
 // A batch import is one recoverable operation; incompatible dimensions add nothing.
 const batch=context({project:{id:'p',clips:[],sequence:[],route_mode:'loop'}});vm.runInContext(take(' function addSources(',' window.boundaryOpenSource='),batch);const sources=['x','y'].map(key=>({job_id:key,version:'original',label:key,frames:12,dimensions:[20,40]}));assert.equal(batch.addSources([sources[0],{...sources[1],dimensions:[40,20]}]),false);assert.equal(batch.project.clips.length,0);assert.equal(batch.addSources(sources),true);assert.equal(batch.project.clips.length,2);assert.equal(batch.history.length,1);batch.restoreHistory(batch.history,batch.redoHistory);assert.equal(batch.project.clips.length,0);batch.restoreHistory(batch.redoHistory,batch.history);assert.equal(batch.project.clips.length,2);assert.equal(batch.addSources(sources),false,'duplicates are not silently added');
 // Every save path is serialized, so an older autosave cannot overwrite a newer manual save.
 const requests=[],saves=context({call(action,data){const task=deferred();requests.push({...task,data});return task.promise}});vm.runInContext(take(' async function saveProject(',' function metricText('),saves);saves.project.shared_tone.tone=1;saves.revision=1;saves.dirty=true;const first=saves.saveProject(true);await tick();saves.project.shared_tone.tone=2;saves.revision=2;const second=saves.saveProject(true);await tick();assert.equal(requests.length,1,'new write waits for older write');requests[0].resolve({project:requests[0].data.project});await first;await tick();assert.equal(saves.dirty,true);assert.equal(requests.length,2);assert.equal(requests[1].data.project.shared_tone.tone,2);requests[1].resolve({project:requests[1].data.project});await second;assert.equal(saves.dirty,false);assert.equal(saves.project.shared_tone.tone,2);assert.equal(saves.saveQueues.size,0);
 // Analysis/apply ignore stale responses. Apply and Undo/Redo form one transaction.
 const pending=[],finish=context({call(action,data){const task=deferred();pending.push({...task,action,data});return task.promise}});vm.runInContext(take(' async function analyzeFinish(',' async function loadProject('),finish);let request=finish.analyzeFinish();finish.revision++;pending[0].resolve({plan:{id:'old',signature:'old',summary:{}}});await request;assert.equal(finish.finishPlan,null);assert.match(finish.lastMessage.text,/未套用/);
 request=finish.analyzeFinish();const plan={id:'candidate',signature:'signature',summary:{appearance_fixes:1,seam_fixes:0,needs_review:1},review_items:[{kind:'hand',reason:'review'}]};pending[1].resolve({plan});await request;assert.equal(finish.finishPlan.id,'candidate');const original=plain(finish.project);request=finish.applyFinish();const repaired=plain(original);repaired.shared_tone.tone=5;pending[2].resolve({project:repaired,review_items:plan.review_items,applied:{appearance:1,seams:0}});await request;assert.equal(finish.project.shared_tone.tone,5);assert.equal(finish.history.length,1);assert.equal(finish.finishApplied,true);finish.restoreHistory(finish.history,finish.redoHistory);assert.equal(finish.project.shared_tone.tone,0);assert.equal(finish.finishApplied,false,'undo must not claim that fixes remain applied');finish.restoreHistory(finish.redoHistory,finish.history);assert.equal(finish.project.shared_tone.tone,5);assert.equal(finish.finishApplied,false,'redo conservatively requires reanalysis for inspector status');
 // Source entry saves an unrelated in-progress group and reuses its dedicated single-clip project.
 const stored=new Map(),projects=new Map(),entry=context({window:{},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},refreshCatalog:async()=>{},refreshProjects:async()=>{},catalog:[sources[0]],rememberDraft(){if(entry.project.shared_tone?.tone===9)entry.savedOldDraft=plain(entry.project)},call:async()=>({project:{id:'single'}}),async loadProject(id){entry.project=plain(projects.get(id)||{id,clips:[],sequence:[],route_mode:'loop'});entry.aKey=entry.bKey=''},async saveProject(){projects.set(entry.project.id,plain(entry.project))},setWorkflowStep(){}});vm.runInContext(take(' function addSources(',' function renderProjectList('),entry);entry.project.shared_tone.tone=9;assert.equal(await entry.window.boundaryOpenSource({jobId:'x'}),true);assert.equal(entry.savedOldDraft.shared_tone.tone,9);assert.equal(entry.project.clips.length,1);assert.equal(entry.project.clips[0].job_id,'x');assert.equal(await entry.window.boundaryOpenSource({jobId:'x'}),true);assert.equal(projects.size,1);
 // Refreshing metadata never substitutes different pixels into an already loaded immutable output.
 const meta=context({outputReadyVersion:'v001',outputVersionMeta:{signature:'first',source_freshness:{state:'current'}},outputLoading:false,exportStatus:{},versions:[],call:async()=>({versions:[{name:'v001',signature:'second',source_freshness:{state:'current'}}]}),completeVersions(){return meta.versions},versionName:v=>v.name,renderLoadedOutputState(){}});vm.runInContext(take(' async function reloadVersions(',' async function pollStatus('),meta);await meta.reloadVersions(meta.project.id);assert.equal(meta.outputVersionMeta.signature,'first');assert.equal(meta.outputVersionMeta.source_freshness.state,'unknown');
 const html=fs.readFileSync(__dirname+'/transitions_panel.html','utf8');assert.match(html,/id="trStepTone"[^>]*hidden/);for(const id of ['FinishAnalyze','FinishApply','PreviewRoute','RouteMode','SourceChoices','Redo'])assert.ok(html.includes('id="tr'+id+'"'));assert.equal((html.match(/id="trFinishAnalyze"/g)||[]).length,1);assert.ok(html.indexOf('id="trBuildSeams"')>html.indexOf('id="trAdvancedSettings"'),'old auto controls belong to advanced overrides');
 // Old running servers must reject new topology before receiving any save/export.
 const legacy={assertSeamsReady(){},api:async()=>({features:{transition_sequence:2,transition_tone:1,transition_seams:1}})};vm.createContext(legacy);vm.runInContext(take(' const call=',' const pairKey='),legacy);await assert.rejects(vm.runInContext("call('save',{project:{route_mode:'open',clips:[{},{}]}})",legacy),/重新啟動/);await assert.rejects(vm.runInContext("call('save',{project:{route_mode:'loop',clips:[{}]}})",legacy),/重新啟動/);legacy.api=async()=>({features:{boundary_routes:1}});await assert.rejects(vm.runInContext("call('finish_analyze',{project:{clips:[{}]}})",legacy),/整批修正/);
 vm.runInContext(take(' function seamContractSignature(',' function contourPixels('),routes);assert.throws(()=>routes.assertFeatureRoundTrip({route_mode:'open',sequence:['a']},{sequence:['a']}),/播放方式/);
 // Whole-route draft playback uses every returned frame, with no export/version creation.
 const calls=[],draft=context({fps:Number,outputClips:[],outputCache:new Map(),outputEpoch:0,draftRouteEpoch:0,draftRouteIdentity:'',outputLoading:false,outputReadyVersion:'',outputVersionMeta:null,memoryLimit:384*1024*1024,outputSequence:[],outputSequenceIndex:0,outputKey:'',outputFrame:0,outputElapsed:0,setWorkflowStep(key){draft.mode=key},releaseOutput(){draft.draftRouteEpoch++;draft.outputClips=[];draft.outputCache=new Map()},call(action,data){calls.push({action,data});return Promise.resolve({clips:[{key:'a',label:'A',fps:'12',dimensions:[20,40],preview_dimensions:[10,20],frames:[{image:'synthetic-1'},{image:'synthetic-2'}]},{key:'b',label:'B',fps:'12',dimensions:[20,40],preview_dimensions:[10,20],frames:[{image:'synthetic-3'},{image:'synthetic-4'}]}],sequence:['a','b'],route_mode:'open'})},loadImage:async url=>({url,width:10,height:20}),renderEmotionButtons(){},renderOutputSeams(){},renderLoadedOutputState(){},drawOutput(){},startOutput(){draft.outputRunning=true},disposeCache(cache){cache.clear()}});vm.runInContext(take(' function outputRecipeIdentity(',' function outputDraftState('),draft);vm.runInContext(take(' async function previewDraftRoute(',' async function preloadOutput('),draft);await draft.previewDraftRoute();assert.deepEqual(calls.map(c=>c.action),['render_route_preview']);assert.equal(draft.outputKind,'draft');assert.equal(draft.outputRouteMode,'open');assert.equal(draft.outputCache.get('a').length+draft.outputCache.get('b').length,4);assert.equal(draft.outputRunning,true);assert.equal(draft.outputReadyVersion,'');
 let routeTask;draft.call=()=>{routeTask=deferred();return routeTask.promise};const preview=draft.previewDraftRoute();draft.revision++;routeTask.resolve({clips:[]});await preview;assert.equal(draft.outputClips.length,0);assert.match(draft.el('OutputEmpty').textContent,/草稿已變更/);
 // A later failed/expired apply cannot change any edit or undo entry.
 request=finish.analyzeFinish();pending[3].resolve({plan});await request;const historyBefore=finish.history.length;request=finish.applyFinish();finish.project.shared_tone.tone=8;finish.revision++;pending[4].resolve({project:repaired,review_items:[]});await request;assert.equal(finish.project.shared_tone.tone,8);assert.equal(finish.history.length,historyBefore);assert.match(finish.lastMessage.text,/未寫回/);
 const repair=context({document:{createElement:element},finishPlan:{summary:{appearance_fixes:0,seam_fixes:0,repair_count:1,needs_review:0},repairs:[{kind:'seam_closure',status:'FIX',reason:'停用過期基準並重新分析'}]},finishPlanRevision:0});vm.runInContext(take(' function renderFinish(',' async function analyzeFinish('),repair);repair.renderFinish();assert.equal(repair.el('FinishApply').disabled,false,'repair-only plans have an actionable Apply');assert.match(repair.el('FinishFixList').children[0].children[0].textContent,/停用過期基準/);repair.finishPlan=null;repair.renderFinish();assert.equal(repair.el('FinishReviewSummary').hidden,true,'no-analysis state cannot imply zero exceptions');
 console.log('PASS: unified boundary topology; open-route final-frame stop; atomic multi-source add; undo/redo; serialized saves; stale analysis/apply rejection; single source entry preserves drafts; immutable metadata refresh; consolidated controls');
 console.log('PASS: legacy-server topology/automation guard; route-mode round trip; full-frame draft route playback without export; stale draft preview and apply rejection');
})().catch(error=>{console.error(error);process.exitCode=1});

// Attempt-scoped diagnostics must never attribute similarity residuals to a local preflight rejection.
{
 const h=candidateHarness(),s=h.s,copy=v=>plain(v),content=node=>(node.textContent||'')+(node.children||[]).map(content).join(' '),nodes=(node,cls)=>[...(node.className===cls?[node]:[]),...(node.children||[]).flatMap(child=>nodes(child,cls))];
 const similarity={kind:'similarity',rendered:true,selected:false,status:'review',before:copy(h.seam.candidate.before),after:copy(h.seam.candidate.after),failed_checks:[{code:'similarity_detail',label:'整體對位內容差異',value:.4,limit:.01,stage:'registration',description:'整體試算仍有差異'}]};
 const blocked={kind:'local',strength:100,rendered:false,selected:false,status:'rejected',before:copy(similarity.before),after:null,failed_checks:[{code:'local_displacement',label:'前景位移範圍',value:8,limit:3,stage:'preflight',description:'超出目前允許的角色位移'}],displacement:{support_max_px:8,canvas_max_px:99,limit_px:3}};
 h.seam.attempts=[similarity,blocked];h.seam.candidate=null;h.seam.candidate_available=false;h.seam.apply_scope='none';h.seam.failed_checks=[];
 vm.runInContext(take(' function renderFinish(',' async function analyzeFinish('),s);s.renderFinish();const first=s.el('FinishReviewList').children[0],groups=nodes(first,'tr-attempt-group');assert.equal(groups.length,2,'similarity and local diagnostics need separate algorithm groups');assert.match(content(groups[0]),/整體位移／縮放.*整體對位內容差異/);assert.match(content(groups[1]),/局部對位.*100%.*未產生候選.*前景位移範圍/);assert.doesNotMatch(content(groups[1]),/整體對位內容差異|首尾幀量測/,'unrendered local attempt cannot inherit any similarity residuals');assert.doesNotMatch(first.children[0].textContent,/整體對位內容差異/);assert.match(content(groups[1]),/含透明區域.*99/);assert.equal(s.el('FinishApply').disabled,true);
 const local={kind:'local',strength:55,rendered:true,selected:true,status:'safe_geometry',before:copy(similarity.before),after:copy(similarity.after),failed_checks:[{code:'content_remaining',label:'局部內容仍不同',value:.02,limit:.005,description:'保留角色正常動作，接點仍需檢查'}],displacement:{support_max_px:2.25,canvas_max_px:60,limit_px:3}};local.failed_checks.push(copy(local.failed_checks[0]));h.seam.attempts=[similarity,blocked,local];h.seam.candidate={...copy(local),transform:{support_max_px:2.25}};h.seam.candidate_available=true;h.seam.apply_scope='geometry';h.seam.failed_checks=copy(local.failed_checks);s.finishPlan.summary.geometry_fixes=1;s.renderFinish();const second=s.el('FinishReviewList').children[0],text=second.children[0].textContent;assert.match(text,/55%.*接點仍需檢查/);assert.doesNotMatch(text,/100%|整體對位內容差異|99/);assert.equal(s.el('FinishApply').disabled,false,'backend-verified geometry is actionable without claiming closure');assert.match(s.el('FinishStatus').textContent,/1 個局部對位.*仍需檢查/);const locals=nodes(second,'tr-attempt-group')[1];assert.match(content(locals),/55%.*2\.25/);assert.equal((content(locals).match(/局部內容仍不同/g)||[]).length,1,'identical failures within an attempt are not repeated');assert.equal(s.el('FinishFixList').children.length,0,'geometry-only repair appears once in Needs Review, not a duplicate closure card');assert.match(content(s.el('FinishReviewList')),/局部對位.*仍需檢查/);
 const summaryFixes=s.finishPlan.summary.geometry_fixes;s.finishPlan.summary.geometry_fixes=0;s.renderFinish();assert.equal(s.el('FinishApply').disabled,true,'a preview candidate alone never authorizes Apply');s.finishPlan.summary.geometry_fixes=summaryFixes;
 const ratios=[{code:'detail_residual',stage:'registration',value:.4,limit:.01,label:'不同量測的原始細節',description:'raw'}, {code:'registered_detail_ratio',stage:'registration',value:.03,limit:.005,label:'精確細節差異',description:'sampled'},{code:'registered_local_ratio',stage:'registration',value:.8039,limit:.12,label:'局部內容差異'},{code:'registered_unsupported_alpha_pixels',stage:'registration',value:8,limit:3,label:'新增或缺失的輪廓像素'}];assert.equal(s.finishCheckValue({code:'silhouette_iou'},.9747),'97.47%');assert.equal(s.finishCheckValue(ratios[2],.8039),'80.39%');assert.equal(s.finishCheckValue({code:'area_ratio'},[.96,1.04]),'96.00%～104.00%');local.failed_checks=ratios;const compact=s.finishReason(h.seam);assert.match(compact,/精確細節差異/);assert.match(compact,/不同量測的原始細節/,'different measurements are not duplicate failures');s.renderFinish();const ratioText=content(s.el('FinishReviewList'));assert.match(ratioText,/80\.39%.*12\.00%/);assert.match(ratioText,/最差局部視窗.*不代表整個角色/);assert.match(ratioText,/尚未對上的輪廓像素.*位置、形狀或透明度.*不能.*判定缺件/);assert.doesNotMatch(ratioText,/新增或缺失的輪廓像素/);
 const inspection={planId:s.finishPlan.id,a:'a',b:'b',revision:s.revision,candidate:copy(h.seam.candidate),attempt:copy(local),note:'readonly',before:{left:{},right:{}},after:{left:{},right:{}}};s.finishInspection=inspection;vm.runInContext(take(' function renderCompareStatus(',' function routeKeys('),s);s.showCandidateComparison(inspection,'after');s.renderCompareStatus();assert.match(s.el('CompareStatus').textContent,/55%.*2\.25 px.*尚未套用/);assert.doesNotMatch(s.el('CompareStatus').textContent,/60|99/);assert.match(s.comparison.leftLabel,/55%/);s.showCandidateComparison(inspection,'before');s.renderCompareStatus();assert.match(s.el('CompareStatus').textContent,/對位前試算/);assert.doesNotMatch(s.el('CompareStatus').textContent,/55%.*對位候選/);
 console.log('PASS: algorithm-scoped diagnostics; unrendered local attempts own only preflight reasons; lower-strength candidate and foreground displacement; duplicate failures removed; geometry-only apply remains Needs Review; readonly candidate labels show actual strength');
}

{
 const s=candidateHarness().s,clip={code:'clipped',stage:'registration',value:true,limit:false,label:'畫布裁切',description:'first'},raw={code:'detail_residual',stage:'registration',value:.03,limit:.005,label:'原始細節比例',description:'raw'},registered={...raw,code:'registered_detail_ratio',label:'對位後細節差異',description:'幾何搬移已扣除，剩餘內容差異不應自動抹平'};
 assert.equal(s.finishChecks([clip,{...clip,description:'second'}]).length,1,'same clipping measurement is one failure even if wording differs');assert.equal(s.finishChecks([raw,registered]).length,1);assert.equal(s.finishChecks([raw,registered])[0].code,'registered_detail_ratio');assert.equal(s.finishChecks([registered,raw]).length,1,'alias dedup is order independent');
 for(const variant of [{stage:'window'},{value:.031},{limit:.006},{frame:4}])assert.equal(s.finishChecks([raw,{...registered,...variant}]).length,2,'different stage/value/limit/frame remains visible');assert.equal(s.finishChecks([clip,{...clip,stage:'window'}]).length,2);
 const item={candidate:{kind:'similarity'},failed_checks:[raw,registered]},card=element('div');s.appendFinishDetails(card,item);const details=card.children[0];assert.match(details.children[0].textContent,/（1）/);assert.equal(details.children[1].children.length,1,'details use the same dedup as the main reason');assert.doesNotMatch(s.finishReason(item),/原始細節比例/);assert.match(s.finishReason(item),/對位後細節差異/);const description=s.finishCheckDescription(registered);assert.match(description,/此次對位後仍有差異.*不能單憑此值判斷.*形變、正常動作或缺損/);assert.doesNotMatch(description,/幾何搬移已扣除/);
 console.log('PASS: shared normal/details dedup merges only same-stage/value/threshold alias failures; distinct stages and measurements stay visible; neutral residual explanation');
}

(async()=>{
 const pending=[],s=context({document:{createElement:element},call(action,data){const task=deferred();pending.push({action,data,...task});return task.promise},reviewFor:()=>null});s.finishPlan={id:'geometry-only',signature:'checked-source-and-draft',summary:{appearance_fixes:0,seam_fixes:0,geometry_fixes:1,needs_review:1},seams:[{a:'a',b:'b',a_label:'A',b_label:'B',status:'REVIEW',apply_scope:'geometry',candidate_available:true,attempts:[{kind:'local',strength:40,rendered:true,selected:true,status:'safe_geometry',failed_checks:[],displacement:{support_max_px:1.5,canvas_max_px:50,limit_px:3}}]}],review_items:[{a:'a',b:'b',a_label:'A',b_label:'B',kind:'seam',reason:'仍需播放驗收'}]};s.finishPlanRevision=0;
 vm.runInContext(take(' async function analyzeFinish(',' async function loadProject('),s);vm.runInContext(take(' function renderFinish(',' async function analyzeFinish('),s);s.renderFinish();assert.equal(s.el('FinishApply').disabled,false);const original=plain(s.project),request=s.applyFinish(),corrected=plain(original);corrected.clips[0].tail.alignment={enabled:true,strength:40,model:{synthetic:'foreground-verified-local'}};pending[0].resolve({project:corrected,review_items:plain(s.finishPlan.review_items),applied:{appearance:0,seams:0,geometry:1}});await request;assert.equal(s.project.clips[0].tail.alignment.strength,40);assert.equal(s.finishReviewItems.length,1);assert.equal(Object.keys(s.project.reviews).length,0,'partial geometry never records human acceptance');assert.equal(s.history.length,1);assert.match(s.lastMessage.text,/1 個局部對位仍需檢查接點/);s.renderFinish();assert.match(s.el('FinishReviewList').children[0].children[0].textContent,/已套用局部對位 40%.*接點仍需檢查/);s.restoreHistory(s.history,s.redoHistory);assert.equal(s.project.clips[0].tail.alignment,undefined);assert.equal(s.finishApplied,false);s.restoreHistory(s.redoHistory,s.history);assert.equal(s.project.clips[0].tail.alignment.strength,40);assert.equal(s.finishApplied,false);console.log('PASS: backend-verified geometry-only Apply is one undo/redo transaction and retains Needs Review without recording acceptance');
})().catch(error=>{console.error(error);process.exitCode=1});

// Schema 3 keeps per-frame registration metadata and binds its inspected fade range.
(async()=>{
 const closure={enabled:true,schema:3,route_mode:'loop',sequence:['a','b','c'],binding:'synthetic-registration-binding',created:123,links:[{a:'a',b:'b',reference:'b_head',anchor_id:'synthetic-anchor',sha256:'synthetic-sha',dimensions:[20,40],registration:{kind:'similarity',tail:[{frame:11,dx:1,dy:0,scale:1},{frame:12,dx:2,dy:0,scale:1}],head:[{frame:1,dx:0,dy:0,scale:1},{frame:2,dx:-1,dy:0,scale:1}]}}]};
 const captured=[],s=context({pairKey:(a,b)=>a+'>'+b,seamServerError:'',seamServerErrorKey:'',call:async(action,data)=>{captured.push({action,data:plain(data)});return{project:plain(data.project)}}});s.project.seam_closure=plain(closure);
 vm.runInContext(take(' function seamModelKey(',' function renderSeams('),s);vm.runInContext(take(' function seamContractSignature(',' function contourPixels('),s);s.rememberSeamSnapshot();s.assertSeamsReady();assert.deepEqual(plain(s.normalizeProject(s.project).seam_closure),closure);
 const saved=plain(s.project);saved.seam_closure.links[0].registration.tail[0].dx=99;assert.throws(()=>s.assertFeatureRoundTrip(s.project,saved),/完整保留共用接點/);delete saved.seam_closure.links[0].registration;assert.throws(()=>s.assertFeatureRoundTrip(s.project,saved),/完整保留共用接點/);const reordered=plain(s.project);reordered.seam_closure.links[0].registration={head:reordered.seam_closure.links[0].registration.head,tail:reordered.seam_closure.links[0].registration.tail,kind:'similarity'};s.assertFeatureRoundTrip(s.project,reordered);
 vm.runInContext(take(' async function saveProject(',' function metricText('),s);await s.saveProject(true);assert.equal(captured[0].action,'save');assert.deepEqual(captured[0].data.project.seam_closure,closure);assert.deepEqual(plain(s.project.seam_closure),closure);assert.equal(s.project.clips[0].tail.dx,0,'registration must not become a second affine edit');
 s.project.clips[0].tail_frames=4;assert.throws(()=>s.assertSeamsReady(),/過渡範圍.*重新分析/);s.project.clips[0].tail_frames=3;s.project.clips[1].head_frames=4;assert.throws(()=>s.assertSeamsReady(),/過渡範圍.*重新分析/);s.project.clips[1].head_frames=3;s.assertSeamsReady();
 for(const schema of [1,2]){s.project.seam_closure.schema=schema;s.rememberSeamSnapshot();s.project.clips[0].tail_frames=4;s.assertSeamsReady();s.project.clips[0].tail_frames=3}
 const apiCalls=[],cap={assertSeamsReady(){},api:async(action,data)=>{if(action==='version')return{features:{transition_seams:1}};apiCalls.push({action,data});return{}}};vm.createContext(cap);vm.runInContext(take(' const call=',' const pairKey='),cap);for(const action of ['save','compare','render_preview','export'])await assert.rejects(vm.runInContext(`call('${action}',{project:{clips:[{},{}],seam_closure:{enabled:true,schema:3}}})`,cap),/逐幀對位/);assert.equal(apiCalls.length,0,'old service never gets schema-3 render/save payload');cap.api=async action=>action==='version'?{features:{transition_seams:2}}:{accepted:true};assert.equal((await vm.runInContext("call('save',{project:{clips:[{},{}],seam_closure:{enabled:true,schema:3}}})",cap)).accepted,true);
 console.log('PASS: schema-3 registration metadata survives normalize/save/roundtrip; dropped or changed transforms reject; fade ranges invalidate only schema 3; old service rejects before save/render/export');
})().catch(error=>{console.error(error);process.exitCode=1});

// Candidate inspection is a read-only view with the same latest-command ownership as draft playback.
function candidateHarness(){
 const calls=[],images=[],timers=new Map(),draws=[];let timerId=0;
 const seam={a:'a',b:'b',a_label:'A',b_label:'B',status:'REVIEW',candidate_available:true,failed_checks:[{code:'detail',label:'局部內容差異',value:.09,limit:.04,description:'對位後仍有局部內容變化'},{code:'edge',label:'畫布邊緣',value:3,limit:0,description:'候選超出畫布'},{code:'third',label:'第三個檢查',value:1,limit:0}],candidate:{kind:'similarity',status:'review',transform:{dx:3,dy:1,scale:1.02},before:{metrics:{silhouette:2},geometry:{iou:.85,changed_detail_ratio:.12}},after:{metrics:{silhouette:.2},geometry:{iou:.98,changed_detail_ratio:.09}}}};
 const s=context({document:{createElement:element},mode:'check',inView:()=>true,finishPlan:{id:'plan',signature:'plan-signature',seams:[seam],review_items:[seam],summary:{appearance_fixes:0,seam_fixes:0,needs_review:1}},finishPlanRevision:0,compareTimer:null,compareState:'empty',compareFailure:'',previewFrames:[],previewIndex:0,previewTimer:null,previewEpoch:0,regionEditor:null,remembered:0,rememberDraft(){s.remembered++},renderFinish(){},renderCompareStatus(){},renderReview(){},renderMatrix(){},renderAlignment(){},renderPairs(){},reviewFor:()=>null,pairKey:(a=s.aKey,b=s.bKey)=>a+'>'+b,metricText:()=> 'candidate metric',setWorkflowStep(){},drawComparison(image){draws.push(image||s.comparison)},call(action,data){const task=deferred();calls.push({action,data,...task});return task.promise},loadImage(url){const task=deferred();images.push({url,...task});return task.promise},setTimeout(fn,delay){const id=++timerId;timers.set(id,{fn,delay});return id},clearTimeout(id){timers.delete(id)}});
 s.el('Span').value='6';s.el('PreviewSpeed').value='0.1';
 vm.runInContext(take(' function queueCompare(',' function drawComparison('),s);vm.runInContext(take(' function stopPreview(',' function renderVersions('),s);vm.runInContext(take(' function selectPair(',' function setMode('),s);
 const response={before:{left:'before-left',right:'before-right',signature:'before',metrics:{silhouette:2}},after:{left:'after-left',right:'after-right',signature:'candidate-not-a-draft',metrics:{silhouette:.2}},note:'兩份試算均包含計畫內的明暗校準，尚未套用。'};
 async function decodeCandidate(task){task.resolve(plain(response));await tick();for(const image of images.filter(i=>!i.done)){image.done=true;image.resolve({url:image.url,width:20,height:40})}await tick();for(const image of images.filter(i=>!i.done)){image.done=true;image.resolve({url:image.url,width:20,height:40})}await tick()}
 return{s,seam,calls,images,timers,draws,response,decodeCandidate};
}
(async()=>{
 const h=candidateHarness(),s=h.s,original=JSON.stringify(s.project),load=s.inspectFinishCandidate(h.seam);
 await h.decodeCandidate(h.calls[0]);await load;
 vm.runInContext(take(' function renderReview(',' const loadImage='),s);s.renderReview();
 assert.equal(s.el('SeamSlowPlay').disabled,false,'ready candidate can be played');
 assert.match(s.el('SeamSlowPlay').textContent,/修正預覽（未套用）/);
 vm.runInContext(take(' function renderFinish(',' async function analyzeFinish('),s);s.renderFinish();
 const card=s.el('FinishReviewList').children[0];assert.equal(card.children[0].tag,'p');assert.equal(card.children[0].onclick,undefined,'notification is passive');
 assert.equal(card.children.at(-1).tag,'button');assert.equal(card.children.at(-1).textContent,'查看修正預覽 →');
 for(const view of ['after','before']){
  s.stopPreview();s.showCandidateComparison(s.finishInspection,view);
  const play=s.preparePreview(),request=h.calls.at(-1);
  assert.equal(request.action,'finish_candidate_playback');assert.equal(request.data.view,view);
  request.resolve({candidate_view:view,applied:false,frames:[{image:view+'-motion',duration_ms:100}]});await tick();
  h.images.at(-1).resolve({url:view+'-motion'});await play;
  assert.equal(s.previewRunning,true);assert.equal(s.comparison.candidatePreview,view);
  assert.equal(h.draws.at(-1).url,view+'-motion');assert.match(s.el('RightLabel').textContent,/未套用/);
  assert.equal([...h.timers.values()].at(-1).delay,1000,'0.1x uses actual frame duration');
  s.stopPreview();assert.equal(s.comparison.candidatePreview,view,'stop retains inspected version');
 }
 assert.equal(JSON.stringify(s.project),original);assert.equal(s.history.length,0);assert.equal(s.dirty,false);
 const broken=s.preparePreview();h.calls.at(-1).reject(Error('計畫過期'));await broken;
 assert.equal(s.previewRunning,false);assert.equal(s.comparison.candidatePreview,'before');
 assert.match(s.lastMessage.text,/短播未開始.*計畫過期/);assert.ok(h.calls.every(c=>c.action!=='render_preview'),'no silent draft fallback');
 for(const phase of ['api','decode'])for(const change of ['view','pair','edit','project','stop']){
  const x=candidateHarness(),r=x.s,loading=r.inspectFinishCandidate(x.seam);await x.decodeCandidate(x.calls[0]);await loading;
  const request=r.preparePreview(),pending=x.calls.at(-1),result={candidate_view:'after',applied:false,frames:[{image:'late-motion'}]};
  if(phase==='decode'){pending.resolve(result);await tick()}
  if(change==='view'){r.stopPreview();r.showCandidateComparison(r.finishInspection,'before')}
  if(change==='pair')r.selectPair('b','c');if(change==='edit'){r.project.clips[0].tone=8;r.markDirty()}
  if(change==='project'){r.project={id:'new'};r.loadEpoch++}if(change==='stop')r.stopPreview();
  if(phase==='api')pending.resolve(result);else x.images.at(-1).resolve({url:'stale-motion'});
  await request;assert.equal(r.previewRunning,false,phase+'/'+change+' discards stale candidate playback');
 }
 const calls=[],cap={api:async action=>action==='version'?{features:{boundary_routes:1,finish_plan:3}}:(calls.push(action),{})};vm.createContext(cap);vm.runInContext(take(' const call=',' const pairKey='),cap);
 await assert.rejects(vm.runInContext("call('finish_candidate_playback',{project:{clips:[{}]}})",cap),/3\.10\.3/);assert.equal(calls.length,0);
 console.log('PASS: explicit preview button; current candidate before/after 0.1x playback is readonly; no draft fallback; stop/view/pair/edit/project/API/decode ownership and capability guard');
})().catch(error=>{console.error(error);process.exitCode=1});
(async()=>{
 // Earlier capability levels cannot provide attempt-scoped local diagnostics.
 const apiCalls=[],cap={api:async(action,data)=>{if(action==='version')return{features:{boundary_routes:1,finish_plan:2}};apiCalls.push(action);return{}}};vm.createContext(cap);vm.runInContext(take(' const call=',' const pairKey='),cap);
 for(const action of ['finish_analyze','finish_apply','finish_candidate_preview','render_route_preview'])await assert.rejects(vm.runInContext(`call('${action}',{project:{clips:[{}]}})`,cap),/3\.10\.2/);
 assert.equal(apiCalls.length,0,'incompatible service never receives a candidate/apply request');cap.api=async action=>action==='version'?{features:{boundary_routes:1,finish_plan:3}}:{ok:true};assert.equal((await vm.runInContext("call('finish_candidate_preview',{project:{clips:[{}]}})",cap)).ok,true);
 const h=candidateHarness(),s=h.s,original=JSON.stringify(s.project);s.queueCompare();const request=s.inspectFinishCandidate(h.seam);
 assert.equal(h.calls[0].action,'finish_candidate_preview');assert.equal(h.calls[0].data.plan_id,'plan');assert.equal([...h.timers.values()].filter(t=>t.delay===400).length,0,'pending regular compare cannot steal candidate canvas');
 await h.decodeCandidate(h.calls[0]);await request;assert.equal(s.comparison.candidatePreview,'after');assert.match(s.comparison.leftLabel,/未套用/);assert.equal(JSON.stringify(s.project),original);assert.equal(s.dirty,false);assert.equal(s.history.length,0);assert.equal(s.remembered,0,'candidate inspection never persists a draft');assert.equal(s.pairResults.size,0,'candidate signature never becomes a real pair result');assert.equal(s.el('CandidateTools').hidden,false);await s.inspectFinishCandidate(h.seam);assert.equal(h.calls.length,1,'reselecting the same fresh candidate does not fetch or save again');
  vm.runInContext(take(' function renderReview(',' const loadImage='),s);s.renderReview();assert.equal(s.el('Pass').disabled,true);assert.equal(s.el('NeedsWork').disabled,true);assert.equal(s.el('ReviewNote').disabled,true);s.setReview('pass');s.setReview('needs_work');assert.equal(JSON.stringify(s.project),original);assert.equal(s.history.length,0);
 vm.runInContext(take(" el('CandidateView').onchange="," el('FinishAnalyze').onclick="),s);s.el('CandidateView').value='before';s.el('CandidateView').onchange();assert.equal(s.comparison.left.url,'before-left');assert.equal(s.comparison.candidatePreview,'before');assert.equal(h.calls.length,1,'before/after switch reuses decoded read-only frames');s.el('CandidateView').value='after';s.el('CandidateView').onchange();assert.equal(s.comparison.left.url,'after-left');
 vm.runInContext(take(' function renderFinish(',' async function analyzeFinish('),s);s.renderFinish();const card=s.el('FinishReviewList').children[0];assert.match(card.children[0].textContent,/已試算位移與縮放.*局部內容差異.*畫布邊緣/);assert.doesNotMatch(card.children[0].textContent,/第三個檢查|0\.09/);assert.equal(card.children[1].tag,'details');assert.notEqual(card.children[1].open,true);assert.match(card.children[1].children[1].textContent,/85\.00% → 98\.00%/);assert.equal(card.children[1].children[2].children.length,3,'all measurements remain available in one collapsed details');
 h.seam.failed_checks[0].stage='window';h.seam.failed_checks[1].stage='window';h.seam.window={frame:9,label:'A'};s.renderFinish();const windowCard=s.el('FinishReviewList').children[0];assert.match(windowCard.children[0].textContent,/過渡第 9 幀 仍需檢查/);assert.match(windowCard.children[1].children[1].textContent,/首尾幀量測/);assert.match(windowCard.children[1].children[2].children[0].textContent,/過渡第 9 幀（A）.*量測 0\.09/);
 h.seam.candidate.before.residual={detail_ratio:.07};h.seam.candidate.after.residual={detail_ratio:.02};assert.match(s.candidateNumbers(h.seam.candidate),/內容差異比例 7\.00% → 2\.00%/);assert.doesNotMatch(s.candidateNumbers(h.seam.candidate),/12\.00% → 9\.00%/,'incompatible geometry-detail statistics must not be compared');
 h.seam.status='FIX';s.finishPlan.summary.seam_fixes=1;s.renderFinish();assert.equal(s.el('FinishFixList').children[0].children[0].tag,'p');assert.equal(s.el('FinishFixList').children[0].children.at(-1).tag,'button');s.finishPlanRevision=-1;assert.equal(s.canInspectCandidate(h.seam),false);s.finishPlanRevision=0;s.finishApplied=true;assert.equal(s.canInspectCandidate(h.seam),false);s.finishApplied=false;
 s.el('CandidateView').value='draft';s.el('CandidateView').onchange();assert.equal(s.finishInspection,null);assert.equal(s.el('CandidateTools').hidden,true);assert.equal(h.calls.at(-1).action,'compare','return to draft gets an actual comparison');h.calls.at(-1).resolve({left:'draft-left',right:'draft-right'});await tick();for(const image of h.images.filter(i=>!i.done)){image.done=true;image.resolve({url:image.url})}await tick();assert.ok(s.comparison,JSON.stringify(s.lastMessage));assert.equal(s.comparison.candidatePreview,undefined);assert.equal(s.comparison.left.url,'draft-left');
 // Every invalidation is tested while the endpoint is pending, then again during image decoding.
 for(const phase of ['api','decode'])for(const change of ['pair','edit','project','source','plan','stop']){
  const x=candidateHarness(),state=x.s,pending=state.inspectFinishCandidate(x.seam);
  if(phase==='decode'){x.calls[0].resolve(plain(x.response));await tick()}
  if(change==='pair')state.selectPair('b','c');if(change==='edit'){state.project.clips[0].tone=7;state.markDirty()}if(change==='project'){state.loadEpoch++;state.project={id:'other',clips:[],reviews:{}}}if(change==='source'){state.compareEpoch++;state.clearPreview()}if(change==='plan')state.finishPlan={id:'new',seams:[]};if(change==='stop')state.stopPreview();
  if(phase==='api')x.calls[0].resolve(plain(x.response));else{for(const image of x.images){image.done=true;image.resolve({stale:true})}await tick();for(const image of x.images.filter(i=>!i.done)){image.done=true;image.resolve({stale:true})}}
  await pending;assert.equal(!!state.comparison?.candidatePreview,false,phase+' / '+change+' must discard old candidate');assert.equal(state.el('CandidateTools').hidden,true);
 }
 // Failed/expired candidate loading is visible and never changes the project.
 for(const cause of ['api','decode']){const broken=candidateHarness(),pending=broken.s.inspectFinishCandidate(broken.seam),draftBefore=JSON.stringify(broken.s.project);if(cause==='api')broken.calls[0].reject(Error('分析計畫已過期'));else{broken.calls[0].resolve(plain(broken.response));await tick();broken.images[0].reject(Error('試算圖片無法讀取'))}await pending;assert.equal(broken.s.finishInspection,null);assert.equal(broken.s.el('CandidateTools').hidden,true);assert.equal(JSON.stringify(broken.s.project),draftBefore);assert.match(broken.s.lastMessage.text,/對位試算無法載入/);assert.equal(broken.s.lastMessage.error,true)}
 // A late candidate decode cannot overwrite newly started actual draft playback.
 const race=candidateHarness(),r=race.s,candidate=r.inspectFinishCandidate(race.seam);race.calls[0].resolve(plain(race.response));await tick();r.clearFinishInspection();const playing=r.preparePreview();race.calls[1].resolve({frames:[{image:'draft-frame',duration_ms:100}]});await tick();race.images.find(i=>i.url==='draft-frame').resolve({url:'draft-frame'});await playing;assert.equal(r.previewRunning,true);for(const image of race.images.filter(i=>i.url!=='draft-frame')){image.done=true;image.resolve({stale:true})}await tick();for(const image of race.images.filter(i=>!i.done&&i.url!=='draft-frame')){image.done=true;image.resolve({stale:true})}await candidate;assert.equal(r.previewRunning,true);assert.equal(r.comparison?.candidatePreview,undefined);assert.equal(race.draws.at(-1).url,'draft-frame');
 const html=fs.readFileSync(__dirname+'/transitions_panel.html','utf8');assert.match(html,/id="trCandidateTools" hidden/);assert.match(html,/value="draft">返回目前草稿/);assert.match(html,/value="before">對位前試算 · 未套用/);assert.match(html,/value="after">對位候選 · 未套用/);
 console.log('PASS: finish-plan v3 guard; compact reasons and collapsed complete measurements; safe/review candidate inspection; immutable draft/history/reviews; explicit before/after/draft selector; pending timer and API/decode invalidation across edit, pair, project, source, plan, stop and new draft playback');
})().catch(error=>{console.error(error);process.exitCode=1});
