// Synthetic metadata only: no image, video, job directory, or model access.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const app=fs.readFileSync(__dirname+'/app.js','utf8'),chrome=fs.readFileSync(__dirname+'/workspace.js','utf8');
const take=(text,start,end)=>{const a=text.indexOf(start),b=text.indexOf(end,a);assert.ok(a>=0&&b>a,start);return text.slice(a,b)};
const job={id:'synthetic',state:'complete',frames:[{status:'done'},{status:'done'}],config:{fps:12},dimensions:[16,32],media_revision:3,video_files:{full:'old.webm'},export_freshness:{full:{state:'stale',reason:'第 2 幀已重跑，需重新合成'}},alpha_report:{file:'old.webm',verified_frames:2,alpha_max_error:0}};
const media={versionLists:new Map([['synthetic',[{name:'vOld',state:'complete',source_freshness:{state:'stale',reason:'來源已更新'},report:{frames:2,fps:12}}]]]),videoNames:j=>j.video_files,fpsNumber:Number,recipeSummary:()=>'',file:(j,p)=>p,path:()=>'',encodeURIComponent};
vm.createContext(media);
if(app.includes('function mediaFreshness('))vm.runInContext(take(app,'function mediaFreshness(','function availableVideos('),media);
vm.runInContext(take(app,'function availableVideos(','function showVideo('),media);
const videos=media.availableVideos(job);
assert.equal(videos.length,2,'historical exports remain available');
assert.match(videos[0].label,/來源已更新/,'regenerated PNG must not leave old WebM labelled current');
assert.equal(videos[0].freshness.state,'stale');
assert.match(videos[1].label,/來源已更新/,'immutable old edit remains available with provenance warning');
delete job.export_freshness;
assert.match(media.availableVideos(job)[0].label,/未核對/,'legacy export is not silently promoted to current');
job.export_freshness={full:{state:'current'}};
assert.doesNotMatch(media.availableVideos(job)[0].label,/未核對|來源已更新/);
assert.match(media.alphaVerificationText(job),/已回讀/);
job.export_freshness.full.state='stale';
assert.doesNotMatch(media.alphaVerificationText(job),/✓|已回讀/,'old verification must not bless regenerated source');
assert.match(media.alphaVerificationText(job),/重新合成/);
job.export_freshness.full.state='unknown';
assert.match(media.alphaVerificationText(job),/未核對/);
media.versionLists.get('synthetic')[0].source_freshness={state:'current'};
const failedRetry={...job,frames:[{status:'done'},{status:'pending'}]};
assert.equal(media.availableVideos(failedRetry).find(v=>v.kind==='edit:vOld').freshness.state,'stale','failed retry before a new PNG must not retain a cached current label');
const resizedPreview={...job,config:{fps:12,preview_frames:96},frames:Array.from({length:120},()=>({status:'done'})),video_files:{preview:'old-preview.webm'},export_freshness:{preview:{state:'current',report:{verified_frames:48}}}};
assert.equal(media.availableVideos(resizedPreview)[0].frames,48,'old artifact frame count wins over changed preview setting');

const imageFields=new Map(),imageField=id=>{if(!imageFields.has(id))imageFields.set(id,{style:{},src:'',getAttribute(){return this.src},removeAttribute(){this.src=''}});return imageFields.get(id)};
const comparison={$:imageField,file:(j,p)=>p,path:(j,k)=>k,resizeComparison(){},encodeURIComponent};
vm.createContext(comparison);vm.runInContext(take(app,'function frameMediaVersion(','function showFrame('),comparison);vm.runInContext(take(app,'function syncComparison(','function resizeComparison('),comparison);
const f={file:'0001.png',status:'done',seconds:30};comparison.syncComparison({media_revision:1},f);const firstImage=imageField('compareResult').src;
comparison.syncComparison({media_revision:2},f);assert.notEqual(imageField('compareResult').src,firstImage,'same filename and processing duration must reload regenerated pixels');

const fields=new Map(),field=id=>{if(!fields.has(id))fields.set(id,{hidden:false,disabled:false,dataset:{},textContent:'',getAttribute:()=>id==='tabEdit'?'true':'false'});return fields.get(id)};
const ui={currentJob:job,currentVideo:null,editStatuses:new Map([['synthetic',{state:'complete',version:'v1',recipeSignature:'old',sourceRevision:3}]]),draftStates:new Map([['synthetic',{recipeSignature:'new'}]]),transitionContext:{status:{},dirty:false},byId:field,setText:(id,text)=>field(id).textContent=text,setProgress(){},updateContext(){},transitionVisible:()=>false,stateNames:{complete:'去背完成'},Number};
vm.createContext(ui);
if(chrome.includes(' function singleArtifactStatus('))vm.runInContext(take(chrome,' function singleArtifactStatus(',' function renderStatus('),ui);
vm.runInContext(take(chrome,' function renderStatus(',' window.workbenchExportStatus='),ui);
ui.renderStatus();assert.match(field('globalStatus').textContent,/草稿已變更/);assert.doesNotMatch(field('globalStatus').textContent,/✓/);
ui.draftStates.get('synthetic').recipeSignature='old';ui.renderStatus();assert.match(field('globalStatus').textContent,/目前草稿/);
ui.currentJob={...job,media_revision:4};ui.renderStatus();assert.match(field('globalStatus').textContent,/來源已更新/);
ui.currentJob=job;delete ui.editStatuses.get('synthetic').recipeSignature;ui.renderStatus();assert.match(field('globalStatus').textContent,/尚未核對/);
ui.editStatuses.get('synthetic').state='error';ui.editStatuses.get('synthetic').phase='synthetic error';ui.renderStatus();assert.match(field('globalStatus').textContent,/synthetic error/);
const listeners=new Map();ui.window={addEventListener:(name,fn)=>listeners.set(name,fn)};ui.closeDialog=()=>{};
vm.runInContext(take(chrome,' window.workbenchExportStatus='," window.addEventListener('workbench:transitions'"),ui);
ui.window.workbenchExportStatus({jobId:'synthetic',version:'v2',generation:'g2',source_revision:4,state:'running',recipeSignature:'submitted'});
ui.window.workbenchExportStatus({jobId:'synthetic',version:'v2',generation:'g2',source_revision:4,state:'complete'});
assert.equal(ui.editStatuses.get('synthetic').recipeSignature,'submitted','status polling retains the submitted immutable recipe identity');
assert.equal(ui.editStatuses.get('synthetic').sourceRevision,4,'server source revision wins over stale job polling');ui.currentJob={...job,media_revision:4};
listeners.get('workbench:draft')({detail:{jobId:'synthetic',recipeSignature:'edited'}});assert.match(field('globalStatus').textContent,/草稿已變更/);
ui.window.workbenchExportStatus({jobId:'synthetic',version:'v2',generation:'g3',source_revision:4,state:'complete'});assert.equal(ui.editStatuses.get('synthetic').recipeSignature,undefined,'recreated same-name version cannot inherit another generation recipe');
let playCount=0;const selection={window:{},jobs:[job],selected:job.id,loadingVideo:false,$:()=>({readyState:2,play:()=>{playCount++;return Promise.resolve()}}),selectJob(){},saveVideoPosition(){},viewState:()=>({}),saveViews(){},showVideo(){},current:()=>job,selectWorkspaceTab(){},notice(){}};
vm.createContext(selection);vm.runInContext(take(app,'window.workbenchSelectVersion=','function fpsNumber('),selection);
selection.window.workbenchSelectVersion(job.id,'v2');assert.equal(playCount,1,'explicitly selecting an already-loaded version starts playback');
selection.loadingVideo=true;selection.window.workbenchSelectVersion(job.id,'v3');assert.equal(playCount,1,'loading a new URL waits for the normal ready handler');
ui.transitionVisible=()=>true;ui.transitionContext={status:{state:'complete'},dirty:false,completionText:'草稿與 v001 不同；成品未包含目前修改'};ui.renderStatus();assert.match(field('globalStatus').textContent,/草稿與 v001 不同/);assert.doesNotMatch(field('globalStatus').textContent,/✓/);
delete ui.transitionContext.completionText;ui.renderStatus();assert.match(field('globalStatus').textContent,/尚未核對/,'completion without immutable recipe metadata must stay unverified');
console.log('PASS: historical media freshness, legacy unknown, Alpha report scope, draft/export identity, existing-version playback and visible errors');
