// Synthetic DOM/network races only: no services, real media or external packages.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const turn=()=>new Promise(setImmediate);
function harness(){
 const nodes=new Map(),listeners=new Map(),calls=[],timers=new Map(),responses=new Map(),events=[],exportStatuses=[],versionLists=[];let timer=0;
 class Element{
  constructor(id=''){Object.assign(this,{id,value:'0',checked:false,hidden:false,disabled:false,textContent:'',files:[],children:[],options:[],dataset:{},clientWidth:500,clientHeight:500,style:{setProperty(){}},listeners:new Map(),classList:{contains(){return false}}})}
  append(...items){this.children.push(...items)} replaceChildren(...items){this.children=items} before(){} setAttribute(k,v){this[k]=v} focus(){} scrollIntoView(){} setPointerCapture(){} matches(){return false} showModal(){this.open=true} close(){this.open=false}
  addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,[]);this.listeners.get(type).push(fn)}
  dispatchEvent(event){const result=this['on'+event.type]?.(event);for(const fn of this.listeners.get(event.type)||[])fn(event);return result}
  click(){if(!this.disabled)return this.dispatchEvent({type:'click',target:this})}
  querySelector(){return node('summary:'+this.id)} getBoundingClientRect(){return{left:0,top:0,width:500,height:500}}
  getContext(){return new Proxy({getImageData(){return{data:new Uint8ClampedArray(64*80*4)}}},{get:(t,k)=>t[k]||(()=>{})})}
 }
 const node=id=>{if(!nodes.has(id))nodes.set(id,new Element(id));return nodes.get(id)};
 for(const[k,values]of Object.entries({Purpose:['tone','loop','reference'],Mode:['wipe','onion','contour','diff'],Zoom:['fit','1'],Backdrop:['#000000'],OutputMode:['wipe'],OutputZoom:['fit']})){node('le'+k).value=values[0];node('le'+k).options=values.map(value=>({value}))}
 node('leSeamN').value='2';node('leSpeed').value='1';node('leSplit').value='50';node('loopEditor').hidden=true;
 class Event{constructor(type,init={}){this.type=type;Object.assign(this,init)}}
 const window={addEventListener(type,fn){if(!listeners.has(type))listeners.set(type,[]);listeners.get(type).push(fn)},dispatchEvent(event){events.push(event);for(const fn of listeners.get(event.type)||[])fn(event)},workbenchExportStatus:status=>exportStatuses.push(status),workbenchSetVersions:(id,versions)=>versionLists.push({id,versions})};
 const document={getElementById:node,createElement:()=>new Element(),querySelector:node,querySelectorAll:()=>[],documentElement:node('html'),body:node('body')};
 class Image{constructor(){this.width=64;this.height=80}set src(value){queueMicrotask(()=>value.startsWith('bad:')?this.onerror?.():this.onload?.())}}
 const api=async(action,data)=>{calls.push({action,data});if(responses.has(action))return responses.get(action)(data);if(action==='loop/preview')return{frame:data.frame,image:'synthetic:'+data.frame};if(action==='loop/load')return{versions:[]};return{}};
 const context={window,document,$:node,current:()=>null,api,file:()=>'',Image,Event,CustomEvent:Event,ResizeObserver:class{observe(){}},MutationObserver:class{observe(){}},localStorage:{getItem(){return null},setItem(){}},URL:{},fpsNumber:Number,progressText:()=>'',durationText:String,requestAnimationFrame:fn=>fn(),setTimeout(fn,delay){const id=++timer;timers.set(id,{fn,delay});return id},clearTimeout:id=>timers.delete(id),console};
 vm.runInNewContext(fs.readFileSync(__dirname+'/loop.js','utf8'),context,{filename:'loop.js'});
 vm.runInNewContext(fs.readFileSync(__dirname+'/beginner.js','utf8'),context,{filename:'beginner.js'});
 return{node,window,calls,responses,timers,events,exportStatuses,versionLists,async ready(){window.loopRefresh(job('one'));await turn();node('loopEditor').hidden=false},holdNext(){let release,once=true;responses.set('loop/preview',data=>{if(once){once=false;return new Promise(resolve=>release=()=>resolve({frame:data.frame,image:'synthetic:'+data.frame}))}return{frame:data.frame,image:'synthetic:'+data.frame}});return()=>release()},async flushCompare(){const pending=[...timers.entries()].filter(([,t])=>t.delay===300);for(const[id,t]of pending){timers.delete(id);await t.fn()}await turn()}};
}
const job=id=>({id,state:'complete',frames:Array.from({length:4},()=>({status:'done'})),dimensions:[64,80],config:{fps:12}});
const tests=[];function test(name,fn){tests.push([name,fn])}
for(const mode of ['tone','loop'])test('one slow action starts at 0.1x from '+mode,async()=>{const h=harness();await h.ready();h.node('lePurpose').value=mode;await h.node('singleSlowPreview').click();await turn();assert.equal(h.node('leSpeed').value,'0.1');assert.equal(h.node('lePurpose').value,'loop');assert.match(h.node('lePlayback').textContent,/檢查片段/);assert.deepEqual(h.calls.filter(x=>x.action==='loop/preview').map(x=>x.data.frame),[3,4,1,2]);assert.equal(h.timers.size,1)});
test('normal play waits for an in-flight compare and starts once',async()=>{const h=harness();await h.ready();const release=h.holdNext(),comparison=h.node('lePreview').click();await turn();const play=h.node('lePlay').click();assert.match(h.node('lePlayback').textContent,/準備|等待/);release();await comparison;await play;assert.match(h.node('lePlayback').textContent,/檢查片段/);assert.equal(h.timers.size,1)});
test('latest play supersedes an older preparation',async()=>{const h=harness();await h.ready();const release=h.holdNext(),first=h.node('lePlay').click();await turn();const last=h.node('singleSlowPreview').click();release();await first;await last;assert.match(h.node('lePlayback').textContent,/檢查片段/);assert.equal(h.node('leSpeed').value,'0.1');assert.equal(h.timers.size,1)});
for(const phase of ['comparison','seam'])test('Stop cancels pending playback during '+phase,async()=>{const h=harness();await h.ready();const release=h.holdNext();let compare;if(phase==='comparison')compare=h.node('lePreview').click();const play=h.node('singleSlowPreview').click();await turn();h.node('leStop').click();release();await compare;await play;assert.match(h.node('lePlayback').textContent,/已停止/);assert.equal(h.timers.size,0)});
test('switching jobs away and back cannot restore pending playback',async()=>{const h=harness();await h.ready();const release=h.holdNext(),play=h.node('singleSlowPreview').click();await turn();h.window.loopRefresh(job('two'));h.window.loopRefresh(job('one'));release();await play;await h.flushCompare();assert.doesNotMatch(h.node('lePlayback').textContent,/檢查片段/);assert.equal([...h.timers.values()].filter(t=>t.delay!==300).length,0)});
test('changing purpose away and back cancels pending playback',async()=>{const h=harness();await h.ready();const release=h.holdNext(),play=h.node('singleSlowPreview').click();await turn();h.node('lePurpose').value='tone';h.node('lePurpose').dispatchEvent({type:'change'});h.node('lePurpose').value='loop';h.node('lePurpose').dispatchEvent({type:'change'});release();await play;await h.flushCompare();assert.doesNotMatch(h.node('lePlayback').textContent,/檢查片段/)});
test('decode failure is visible and a retry can play',async()=>{const h=harness();await h.ready();h.responses.set('loop/preview',data=>({frame:data.frame,image:'bad:image'}));await h.node('singleSlowPreview').click();assert.match(h.node('lePlayback').textContent,/失敗/);assert.match(h.node('leMessage').textContent,/圖片載入失敗/);h.responses.delete('loop/preview');await h.node('singleSlowPreview').click();assert.match(h.node('lePlayback').textContent,/檢查片段/)});
test('original playback bypasses a stale alignment that still blocks corrected playback',async()=>{const h=harness();await h.ready();h.responses.set('loop/load',()=>({versions:[],recipe:{alignment:{enabled:true,strength:100,model:{provenance:{scope:'loop',source:{job_id:'old-source',frame:4},reference:{job_id:'one',frame:1}}}}}}));await h.node('leLoad').click();await turn();h.node('leOriginal').checked=true;await h.node('lePlay').click();assert.match(h.node('lePlayback').textContent,/檢查片段/);assert.ok(h.calls.filter(c=>c.action==='loop/preview').slice(-4).every(c=>c.data.original===true));h.node('leOriginal').checked=false;await h.node('lePlay').click();assert.match(h.node('lePlayback').textContent,/失敗/);assert.match(h.node('leMessage').textContent,/來源尾幀已變更/)});
test('a frame selection stops old playback and discards its frames',async()=>{const h=harness();await h.ready();await h.node('lePlay').click();h.node('leA').value='2';h.node('leA').dispatchEvent({type:'input'});assert.equal([...h.timers.values()].filter(t=>t.delay!==300).length,0);h.node('leNext').click();assert.equal(Number(h.node('leB').value),4)});
test('leaving the editor cancels a pending play',async()=>{const h=harness();await h.ready();const release=h.holdNext(),play=h.node('singleSlowPreview').click();await turn();h.node('loopEditor').hidden=true;h.window.dispatchEvent({type:'workbench:tab',detail:{id:'tabPlayback'}});release();await play;assert.match(h.node('lePlayback').textContent,/已停止/);assert.equal(h.timers.size,0)});
test('same job media regeneration invalidates pending playback and reloads versions',async()=>{const h=harness();await h.ready();const loads=h.calls.filter(c=>c.action==='loop/load').length,release=h.holdNext(),play=h.node('singleSlowPreview').click();await turn();h.window.loopRefresh({...job('one'),media_revision:1});release();await play;await h.flushCompare();assert.match(h.node('lePlayback').textContent,/來源影格已更新/);assert.equal(h.calls.filter(c=>c.action==='loop/load').length,loads+1);assert.equal([...h.timers.values()].filter(t=>t.delay!==300).length,0)});
test('same job media regeneration makes a previously successful comparison stale',async()=>{const h=harness();await h.ready();await h.node('lePreview').click();assert.equal(h.node('lePreviewBadge').hidden,true);h.window.loopRefresh({...job('one'),media_revision:1});assert.equal(h.node('lePreviewBadge').hidden,false);await h.flushCompare();assert.equal(h.node('lePreviewBadge').hidden,true)});
test('failed retry before PNG replacement refreshes versions only when availability changes',async()=>{const h=harness();await h.ready();const loads=()=>h.calls.filter(c=>c.action==='loop/load').length,initial=loads(),source=job('one');source.frames[1].status='pending';source.state='running';let freshness='stale';h.responses.set('loop/load',()=>({versions:[{name:'v1',source_freshness:{state:freshness}}]}));await h.node('lePlay').click();h.window.loopRefresh(source);await turn();assert.equal(loads(),initial+1);assert.equal(h.versionLists.at(-1).versions[0].source_freshness.state,'stale');assert.equal([...h.timers.values()].filter(t=>t.delay!==300).length,0);h.window.loopRefresh({...source,state:'attention'});await turn();h.window.loopRefresh({...source,state:'attention'});await turn();assert.equal(loads(),initial+1,'identical unavailable polls must not reload');freshness='current';h.window.loopRefresh(job('one'));await turn();assert.equal(loads(),initial+2);assert.equal(h.versionLists.at(-1).versions[0].source_freshness.state,'current')});
test('a version response from an earlier source state cannot restore current labels',async()=>{const h=harness();let release;h.responses.set('loop/load',()=>new Promise(resolve=>release=()=>resolve({versions:[{name:'v1',source_freshness:{state:'current'}}]})));await h.ready();h.responses.set('loop/load',()=>({versions:[{name:'v1',source_freshness:{state:'stale'}}]}));const retry=job('one');retry.frames[1].status='pending';retry.state='attention';h.window.loopRefresh(retry);await turn();release();await turn();assert.equal(h.versionLists.at(-1).versions[0].source_freshness.state,'stale');assert.equal(h.versionLists.length,1)});
test('draft events distinguish recipe changes from comparison-only choices',async()=>{const h=harness();await h.ready();const draft=()=>h.events.filter(e=>e.type==='workbench:draft').at(-1).detail;const initial=draft();assert.equal(initial.jobId,'one');assert.equal(JSON.parse(initial.recipeSignature).tone,0);h.node('leA').value='2';h.node('leA').dispatchEvent({type:'input'});h.node('lePurpose').value='loop';h.node('lePurpose').dispatchEvent({type:'change'});assert.equal(draft().recipeSignature,initial.recipeSignature);h.node('leTone').value='9';h.node('leTone').dispatchEvent({type:'input'});assert.notEqual(draft().recipeSignature,initial.recipeSignature);assert.equal(JSON.parse(draft().recipeSignature).tone,9)});
test('submitted export publishes its captured recipe even if editing continues',async()=>{const h=harness();await h.ready();let release;h.responses.set('loop/export',()=>new Promise(resolve=>release=()=>resolve({state:'running',version:'synthetic-v1'})));const output=h.node('leExport').click();await turn();assert.equal(typeof release,'function');h.node('leTone').value='9';h.node('leTone').dispatchEvent({type:'input'});release();await output;const submitted=h.exportStatuses.find(s=>s.recipeSignature);assert.equal(submitted.jobId,'one');assert.equal(JSON.parse(submitted.recipeSignature).tone,0);assert.equal(JSON.parse(h.events.filter(e=>e.type==='workbench:draft').at(-1).detail.recipeSignature).tone,9)});
(async()=>{let failed=0;for(const[name,fn]of tests){try{await fn();console.log('PASS '+name)}catch(error){failed++;console.error('FAIL '+name+'\n'+error.stack)}}console.log(`${tests.length-failed}/${tests.length} playback regressions passed`);if(failed)process.exitCode=1})().catch(error=>{console.error(error);process.exitCode=1});
