/* Directed animation joins. Draft previews and immutable exported PNG playback stay separate. */
(()=>{
 'use strict';
 const el=name=>document.getElementById('tr'+name),panel=document.getElementById('transitionPanel');
 if(!panel)return;
 const clone=value=>JSON.parse(JSON.stringify(value)),identity=()=>({dx:0,dy:0,sx:100,sy:100,angle:0,cx:50,cy:50});
 const draftPrefix='animation-workbench:transition-draft:v1:',memoryLimit=384*1024*1024;
 const numeric={Start:'start',End:'end',HeadFrames:'head_frames',TailFrames:'tail_frames',Tone:'tone',Contrast:'contrast'};
 const transformFields={Dx:'dx',Dy:'dy',Sx:'sx',Sy:'sy',Angle:'angle',Cx:'cx',Cy:'cy'};
 let project=null,catalog=[],projectList=[],versions=[],dirty=false,history=[],revision=0,loadEpoch=0,loadingProject=false;
 let aKey='',bKey='',mode='check',comparison=null,pairResults=new Map(),compareEpoch=0,compareTimer=null,analyzing=false,operation=false;
 let previewFrames=[],previewIndex=0,previewTimer=null,previewRunning=false,previewEpoch=0,previewOwner=null;
 let outputClips=[],outputCache=new Map(),pendingOutputCache=null,outputEpoch=0,outputAbort=null,outputLoading=false,outputReadyVersion='';
 let outputRunning=false,outputRAF=0,outputClock=0,outputElapsed=0,outputKey='',outputFrame=0,queuedKey='';
 let exportStatus={},statusTimer=null,statusProject='',matrixSignature='',projectListSignature='',initialized=false,focusedSnapshot=null;
 let regionEditor=null;
 let outputSequence=[],outputSequenceIndex=0,toneBusy=false,toneEpoch=0,toneNotice='',toneSnapshot=null;
 let seamBusy=false,seamEpoch=0,seamNotice='',seamServerError='',seamServerErrorKey='',seamReferences={},outputSeamVerification=null;const seamSnapshots=new Map(),seamHistoryReferences=new WeakMap();
 let workflowStep='sources',projectManageAutoOpened=false,compareState='empty',compareFailure='';
 const workflowSteps=[{key:'sources',label:'素材與順序',title:'安排動畫順序'},{key:'tone',label:'統一明暗',title:'檢查切換時的明暗'},{key:'seams',label:'修好接點',title:'檢查上一段與下一段'},{key:'output',label:'預覽與輸出',title:'檢查實際成品'}];
 let alignmentBusy=false,alignmentEpoch=0,alignmentOwner='',alignmentNotice='',alignmentError=false,alignmentStrengthSnapshot=null;const alignmentReports=new Map(),alignmentInvalid=new Map();

 const call=async(action,data={})=>{const p=data.project,usesSeams=p?.seam_closure?.enabled,usesTone=p&&(Number(p.shared_tone?.tone)||Number(p.shared_tone?.contrast)||p.tone_match?.enabled);if(usesSeams&&['compare','render_preview','analyze','save','export'].includes(action))assertSeamsReady(p);if(usesTone||usesSeams||action==='build_seams'||action==='match_tone'||data.scope==='sequence'||p?.sequence_version===2){const version=await api('version');if((usesSeams||action==='build_seams')&&!version.features?.transition_seams)throw Error('目前服務尚未支援共用接點。請重新啟動工作台並重新整理；尚未送出這次修改。');if((usesTone||action==='match_tone')&&!version.features?.transition_tone||data.scope==='sequence'&&(Number(version.features?.transition_sequence)||0)<2||p?.sequence_version===2&&(Number(version.features?.transition_sequence)||0)<2)throw Error('目前服務尚未支援整組明暗／循環順序。請重新啟動工作台並重新整理；尚未送出這次修改。')}try{return await api('transitions/'+action,data)}catch(error){if(usesSeams&&p.id===project?.id&&/共用接點|共同接點/.test(error.message)&&/來源|變更|過期|失效|缺少|損壞/.test(error.message)){seamServerError=error.message;seamServerErrorKey=seamModelKey(p);renderSeams()}throw error}};
 const pairKey=(a=aKey,b=bKey)=>a+'>'+b;
 const currentClip=()=>project?.clips.find(c=>c.key===(el('EditSide').value==='tail'?aKey:bKey));
 const sourceOf=clip=>catalog.find(s=>s.job_id===clip.job_id&&s.version===clip.version);
 const fps=value=>{const parts=String(value||24).split('/').map(Number),n=parts.length===2?parts[0]/parts[1]:parts[0];return Number.isFinite(n)&&n>0?n:24};
 const completeVersions=()=>versions.filter(v=>v.state==='complete'&&Array.isArray(v.clips)&&v.clips.length);
 const versionName=v=>String(v?.name||v?.version||'');
 const inView=()=>!panel.hidden;
 function advancedTypes(p=project){
  const types=new Set(),different=t=>t&&Object.entries(identity()).some(([key,value])=>!['cx','cy'].includes(key)&&Number(t[key]??value)!==value);
  for(const clip of p?.clips||[]){for(const side of ['head','tail']){const transform=clip[side];if(transform?.alignment?.enabled)types.add('局部對位');if(different(transform)||different(transform?.region?.outside))types.add('手動變形');if(transform?.region&&transform.region.mode!=='all')types.add('局部範圍')}if(Number(clip.tone)||Number(clip.contrast))types.add('單段明暗');if(clip.start>1||clip.end<(sourceOf(clip)?.frames||clip.end))types.add('裁切範圍')}
  return [...types];
 }
 function renderAdvancedSummary(){const types=advancedTypes(),text=types.length?'已套用：'+types.join('、'):'未套用';el('AdvancedBadge').textContent=text;el('AppliedAdvanced').hidden=!types.length;el('AppliedAdvanced').textContent=text+' · 查看';el('AppliedAdvanced').title=text;const shared=project?.shared_tone||{};el('ManualToneBadge').textContent=Number(shared.tone)||Number(shared.contrast)?'已套用整組微調':''}
 function renderWorkflow(){
  const index=workflowSteps.findIndex(s=>s.key===workflowStep),step=workflowSteps[index];panel.dataset.step=workflowStep;el('StageTitle').textContent=step.title;
  for(const button of panel.querySelectorAll('[data-tr-step]')){const selected=button.dataset.trStep===workflowStep;button.setAttribute('aria-current',selected?'step':'false')}
  for(const section of panel.querySelectorAll('[data-tr-step-panel]'))section.hidden=section.dataset.trStepPanel!==workflowStep;
  el('StepBack').hidden=index===0;el('StepNext').hidden=index===workflowSteps.length-1;el('StepBack').textContent=index?'← '+workflowSteps[index-1].label:'上一步';el('StepNext').textContent=index<workflowSteps.length-1?'下一步：'+workflowSteps[index+1].label+' →':'下一步';el('PairSelectors').hidden=workflowStep==='sources';el('SeamTransport').hidden=workflowStep!=='seams';
  if(!project){el('ProjectManage').open=true;projectManageAutoOpened=true}else if(projectManageAutoOpened){el('ProjectManage').open=false;projectManageAutoOpened=false}
  const count=project?.clips.length||0;let hint='',action='';
  if(!project){hint='先建立一個表情組，再加入已去背的動畫。';action='建立表情組'}else if(!count){hint=catalog.length?'這組還沒有動畫。從右側選擇素材加入。':'還沒有完成去背的動畫。先匯入影片並完成去背，再回來加入。';action=catalog.length?'選擇動畫':'更新素材來源'}else if(count<2){hint='已加入一段動畫，再加一段就能檢查切換。';action='加入第二段'}else if(workflowStep==='output'&&!outputClips.length){hint=exportStatus.state==='running'?'正在輸出。完成後載入新版，檢查實際播放結果。':completeVersions().length?'可以載入已輸出的版本；草稿調整要重新輸出才會出現在成品。':'先輸出整組動畫，再載入實際成品檢查。';action=exportStatus.state==='running'?'':completeVersions().length?'載入成品':'輸出整組動畫'}
  el('StageGuide').hidden=!hint;el('StageHint').textContent=hint;el('StageAction').hidden=!action;el('StageAction').textContent=action;el('StageAction').disabled=loadingProject||operation||toneBusy||seamBusy;renderAdvancedSummary();renderCompareStatus();
 }
 function setWorkflowStep(key,{focus=true}={}){
  if(!workflowSteps.some(s=>s.key===key))return false;const old=workflowStep;workflowStep=key;regionEditor?.deactivate(false);setMode(key==='output'?'output':'check');renderWorkflow();
  if(focus&&inView()){const button=panel.querySelector('[data-tr-step="'+key+'"]');button?.focus({preventScroll:true})}
  if(key!=='output'&&project&&!comparison?.valid)queueCompare();if(old!==key)window.dispatchEvent(new CustomEvent('workbench:transition-step',{detail:{key}}));return true;
 }
 function renderCompareStatus(){const badge=el('CompareStatus');if(!badge)return;const stale=!!comparison?.left&&!comparison.valid;badge.hidden=!stale||previewRunning;badge.dataset.error=String(compareState==='error');badge.textContent=compareState==='error'?'更新失敗 · 目前仍是上次預覽':compareState==='updating'?'正在更新 · 暫時顯示上次預覽':'舊預覽 · 設定已變更';badge.title=compareFailure||'最新畫面完成前，請勿用這張圖判斷效果。'}
 function routeKeys(clips,sequence){const keys=new Set((clips||[]).map(c=>c.key)),valid=Array.isArray(sequence)?sequence.filter(k=>keys.has(k)):[];return valid.length?valid:(clips||[]).map(c=>c.key)}
 function fullRoute(clips,sequence){return sequence.length===clips.length&&new Set(sequence).size===clips.length&&clips.every(c=>sequence.includes(c.key))}
 function sequencePairs(p=project){const keys=routeKeys(p?.clips,p?.sequence);return keys.map((a,i)=>({a,b:keys[(i+1)%keys.length]}))}
 function routeText(clips,sequence){const names=new Map(clips.map(c=>[c.key,c.label]));return sequence.map((key,i)=>(i+1)+'. '+names.get(key)).join(' → ')+(sequence.length?' ↻':'')}
 function renderLayout(dimensions){const dims=dimensions||project?.dimensions||sourceOf(project?.clips?.[0]||{})?.dimensions||[16,9],choice=el('Layout').value;panel.dataset.layout=choice==='auto'?(dims[1]>dims[0]?'portrait':'landscape'):choice}
 function invalidateAll(){compareEpoch++;clearPreview();if(comparison)comparison.valid=false;pairResults.clear();renderMatrix();renderReview();queueCompare()}
 function renderSequence(){
  const clips=project?.clips||[],sequence=routeKeys(clips,project?.sequence),ordinary=fullRoute(clips,sequence);el('SequenceChain').textContent=routeText(clips,sequence);el('ResetSequence').hidden=!clips.length||ordinary;el('SequenceSeams').replaceChildren();
  for(const [i,pair]of sequencePairs().entries()){const a=clips.find(c=>c.key===pair.a),b=clips.find(c=>c.key===pair.b),review=reviewFor(pair.a,pair.b),button=document.createElement('button');button.className='tr-seam-button';button.textContent=(review?.verdict==='pass'?'✓ ':review?.verdict==='needs_work'?'! ':'○ ')+(i+1)+'. '+a.label+' → '+b.label;button.title=button.textContent;button.dataset.verdict=review?.verdict||'unchecked';button.setAttribute('aria-pressed',String(pair.a===aKey&&pair.b===bKey));button.onclick=()=>selectPair(pair.a,pair.b);el('SequenceSeams').append(button)}
  el('AnalyzeSequence').disabled=!clips.length||analyzing||operation||toneBusy||seamBusy;
 }
 function moveClip(key,direction){if(!project||operation||toneBusy||seamBusy)return;const sequence=routeKeys(project.clips,project.sequence);if(!fullRoute(project.clips,sequence))return;const from=sequence.indexOf(key),to=from+direction;if(from<0||to<0||to>=sequence.length)return;pushHistory();[sequence[from],sequence[to]]=[sequence[to],sequence[from]];project.sequence=sequence;project.sequence_version=2;markDirty();renderClips();message('已調整草稿播放順序；儲存後另存輸出，成品版本才會使用新順序。')}
 function seamModelKey(p=project){const closure=p?.seam_closure;return closure?JSON.stringify([p.id,closure.binding,(closure.links||[]).map(l=>[l.a,l.b,l.reference,l.anchor_id,l.sha256])]):''}
 function seamReferenceValues(p=project){return Object.fromEntries(sequencePairs(p).map(({a,b})=>{const key=pairKey(a,b),link=p?.seam_closure?.links?.find(l=>l.a===a&&l.b===b);return[key,seamReferences[key]||link?.reference||'b_head']}))}
 function seamEditSignature(p=project){return JSON.stringify({sequence:routeKeys(p?.clips,p?.sequence),references:seamReferenceValues(p),shared_tone:p?.shared_tone||{tone:0,contrast:0},tone_match:p?.tone_match?{enabled:p.tone_match.enabled,reference:p.tone_match.reference,bindings:p.tone_match.bindings,adjustments:p.tone_match.adjustments}:null,clips:(p?.clips||[]).map(c=>({key:c.key,job_id:c.job_id,version:c.version,source_revision:sourceOf(c)?.revision,start:c.start,end:c.end,tone:c.tone||0,contrast:c.contrast||0,head:c.head,tail:c.tail}))})}
 function rememberSeamSnapshot(p=project){const key=seamModelKey(p);if(key)seamSnapshots.set(key,seamEditSignature(p))}
 function seamWindowReason(p=project){for(const clip of p?.clips||[]){const n=Number(clip.end)-Number(clip.start)+1,h=Number(clip.head_frames),t=Number(clip.tail_frames);if(!Number.isInteger(h)||!Number.isInteger(t)||h<2||t<2||h+t>n)return clip.label+'：頭／尾過渡各至少 2 幀，合計不可超過保留的 '+n+' 幀。'}return ''}
 function seamStaleReason(p=project){if(!p?.seam_closure)return '';if(seamServerError&&p.id===project?.id&&(!seamServerErrorKey||seamServerErrorKey===seamModelKey(p)))return seamServerError;const baseline=seamSnapshots.get(seamModelKey(p));if(!baseline||baseline!==seamEditSignature(p))return '來源、順序、參考選擇、首尾幀、明暗或變形已變更，請重新建立共用接點，或停用此功能。';return ''}
 function assertSeamsReady(p=project){if(!p?.seam_closure?.enabled)return;const reason=seamWindowReason(p)||seamStaleReason(p);if(reason)throw Error('共用接點尚不可用：'+reason)}
 function renderSeams(){
  const closure=project?.seam_closure,clips=project?.clips||[],route=routeKeys(clips,project?.sequence),busy=operation||toneBusy||seamBusy||loadingProject,refs=seamReferenceValues(),box=el('SeamReferenceList');box.replaceChildren();
  for(const [index,{a,b}]of sequencePairs().entries()){const ca=clips.find(c=>c.key===a),cb=clips.find(c=>c.key===b),row=document.createElement('label'),text=document.createElement('span'),select=document.createElement('select');row.className='tr-seam-reference';text.textContent=(index+1)+'. '+ca.label+' → '+cb.label;select.setAttribute('aria-label',ca.label+' → '+cb.label+' 的共同基準');fillSelect(select,[{value:'b_head',label:'B 首幀為基準'},{value:'a_tail',label:'A 尾幀為基準'}],refs[pairKey(a,b)],'');select.disabled=busy;select.onchange=()=>{if(busy)return;pushHistory();seamReferences[pairKey(a,b)]=select.value;seamNotice='共同基準選擇已變更，按「重新建立全部接點」套用。';invalidateAll();markDirty()};row.append(text,select);box.append(row)}
  const reason=closure?(seamWindowReason()||seamStaleReason()):'',ordinary=fullRoute(clips,route);el('BuildSeams').disabled=clips.length<2||!ordinary||busy;el('BuildSeams').textContent=seamBusy?'正在建立接點…':closure?'重新建立全部接點':'建立全部共用接點';el('SeamEnabled').checked=!!closure?.enabled;el('SeamEnabled').disabled=!closure||busy;el('ClearSeams').disabled=!closure||busy;el('SeamSlowPlay').disabled=!project||!aKey||!bKey||busy||!!(closure?.enabled&&reason);el('SeamClosureStatus').dataset.error=String(!!reason);el('SeamClosureStatus').textContent=seamBusy?'正在以最終明暗與變形建立共同基準，請稍候。':!ordinary&&clips.length?'此功能需要每段一次的固定循環，請先調整播放順序。':closure?.enabled?(reason||'已建立 '+closure.links.length+' 個共同接點。接著慢播檢查，確認動作是否自然。'):closure?'已停用共同接點，方案仍保留。':seamNotice||'按上方按鈕，讓相鄰兩段使用共同畫面。';
  el('HeadFramesLabel').textContent=closure?.enabled?'開頭過渡幀數':'開頭過渡幀數';el('TailFramesLabel').textContent=closure?.enabled?'結尾過渡幀數':'結尾過渡幀數';el('HeadFrames').min=el('TailFrames').min=closure?.enabled?'2':'0';
 }
 function renderToneReport(report){
  const rows=Array.isArray(report?.clips)?report.clips:[],warnings=[],box=el('ToneResultRows');box.replaceChildren();el('ToneResults').hidden=!rows.length;
  const number=value=>typeof value==='number'&&Number.isFinite(value)?value.toFixed(2):'—';
  for(const result of rows){const row=document.createElement('p'),notes=(Array.isArray(result.warnings)?result.warnings:[]).filter(v=>typeof v==='string'&&v.trim());row.className='tr-tone-result';row.dataset.warning=String(!!notes.length);row.textContent=(result.label||project?.clips.find(c=>c.key===result.key)?.label||result.key)+' · 明暗誤差 '+number(result.before?.error)+' → '+number(result.after?.error)+(notes.length?' · ⚠ '+notes.join('；'):'');box.append(row);if(notes.length)warnings.push(...notes)}
  const count=rows.filter(r=>Array.isArray(r.warnings)&&r.warnings.some(v=>typeof v==='string'&&v.trim())).length;el('ToneResultsSummary').textContent='各段校準結果'+(toneBusy?'（上次）':'')+(count?' · '+count+' 段需檢查':'');
  if(report?.note){const note=document.createElement('p');note.className='hint';note.textContent=report.note;box.append(note)}
  return count?'⚠ '+count+' 段需檢查：'+[...new Set(warnings)].join('；'):'';
 }
 function renderTone(){
  const clips=project?.clips||[],match=project?.tone_match;fillSelect(el('ToneReference'),clips.map(c=>({value:c.key,label:c.label})),el('ToneReference').value||match?.reference,'先加入動畫');el('ToneReference').disabled=!clips.length||toneBusy;el('MatchTone').disabled=clips.length<2||operation||toneBusy||seamBusy;el('MatchTone').textContent=toneBusy?'正在調整明暗…':'統一整組明暗';el('ClearToneMatch').disabled=!match||operation||toneBusy||seamBusy;el('ResetGroupTone').disabled=!project||operation||toneBusy||seamBusy;
  for(const[suffix,key]of [['GroupTone','tone'],['GroupContrast','contrast']]){el(suffix).disabled=!project||operation||toneBusy||seamBusy;if(document.activeElement!==el(suffix))el(suffix).value=project?.shared_tone?.[key]||0}
  const report=match?.report,warning=renderToneReport(report),reference=clips.find(c=>c.key===match?.reference);el('ToneMatchStatus').textContent=toneBusy?'正在分析各段不透明內容，完成後可復原。':toneNotice||(match?.enabled?'已調整 '+(report?.clips?.length||clips.length)+' 段，以 '+(reference?.label||match.reference)+' 為準。請播放確認。'+(warning?'\n'+warning:''):match?'自動校準已停用。':'尚未自動校準。');el('ToneMatchStatus').dataset.state=match?.enabled?(warning?'warning':'ready'):'none';
 }
 function seamContractSignature(p){const c=p?.seam_closure;return c?JSON.stringify([c.enabled,c.schema,c.sequence,c.binding,(c.links||[]).map(l=>[l.a,l.b,l.reference,l.anchor_id,l.sha256,l.dimensions])]):''}
 function assertFeatureRoundTrip(submitted,saved){if(submitted.seam_closure&&seamContractSignature(submitted)!==seamContractSignature(saved))throw Error('服務未完整保留共用接點基準，草稿仍保留；請更新工作台後重試。');if(JSON.stringify(submitted.sequence)!==JSON.stringify(saved.sequence))throw Error('服務回傳的播放順序不一致，草稿仍保留；請更新工作台後重試。');if((Number(submitted.shared_tone?.tone)||Number(submitted.shared_tone?.contrast))&&['tone','contrast'].some(k=>Number(submitted.shared_tone[k]||0)!==Number(saved.shared_tone?.[k]||0))||submitted.tone_match?.enabled&&!saved.tone_match?.enabled)throw Error('服務未完整保留整組明暗設定，草稿仍保留；請更新工作台後重試。')}
 function contourPixels(a,b,background){const out=new Uint8ClampedArray(a.length);for(let i=0;i<a.length;i+=4){const aa=a[i+3]/255,ba=b[i+3]/255,common=Math.min(aa,ba),difference=Math.min(1,Math.abs(aa-ba)*4),color=aa>ba?[255,65,85]:[30,220,255],gray=150+(a[i]+a[i+1]+a[i+2]+b[i]+b[i+1]+b[i+2])/30;for(let k=0;k<3;k++)out[i+k]=(background[i+k]*(1-common)+gray*common)*(1-difference)+color[k]*difference;out[i+3]=255}return out}
 function drawContour(ctx,left,right,w,h){const temp=document.createElement('canvas');temp.width=w;temp.height=h;const tc=temp.getContext('2d',{willReadFrequently:true});tc.drawImage(left,0,0,w,h);const a=tc.getImageData(0,0,w,h);tc.clearRect(0,0,w,h);tc.drawImage(right,0,0,w,h);const b=tc.getImageData(0,0,w,h),out=ctx.getImageData(0,0,w,h);out.data.set(contourPixels(a.data,b.data,out.data));ctx.putImageData(out,0,0)}
 function message(text,error=false){el('Message').textContent=text;el('Message').dataset.error=String(error)}
 function notify(){window.dispatchEvent(new CustomEvent('workbench:transitions',{detail:{project,status:exportStatus,dirty}}))}
 function rememberDraft(){if(!project)return;try{localStorage.setItem(draftPrefix+project.id,JSON.stringify({project,dirty,aKey,bKey,seamReferences,seamSnapshot:seamSnapshots.get(seamModelKey())||null}))}catch{message('瀏覽器儲存空間不足，請按「儲存表情組」保留方案。',true)}}
 function pushHistory(snapshot){if(!project)return;const saved=snapshot||clone(project);seamHistoryReferences.set(saved,clone(seamReferences));history.push(saved);if(history.length>24)history.shift();el('Undo').disabled=false}
 function markDirty(){dirty=true;revision++;rememberDraft();renderProjectState();renderProjectList();notify()}
 function renderProjectState(){el('ProjectState').textContent=project?project.name+' · '+(dirty?'尚未儲存':'已儲存'):'先建立表情組';el('ProjectState').dataset.dirty=String(dirty);el('Save').disabled=!project||operation||toneBusy||seamBusy||loadingProject;el('ReplayPreview').disabled=operation||!previewFrames.length||!previewBelongs();el('Undo').disabled=!history.length||operation||toneBusy||seamBusy;el('AddSource').disabled=!project||!catalog.length||operation||toneBusy||seamBusy;el('Export').disabled=!project||project.clips.length<2||exportStatus.state==='running'||operation||toneBusy||seamBusy;el('Analyze').disabled=!project?.clips.length||analyzing||operation;el('Compare').disabled=!project?.clips.length||operation;el('PreparePreview').disabled=!project?.clips.length||operation;el('Swap').disabled=!aKey||!bKey;const dims=project?.clips.length?sourceOf(project.clips[0])?.dimensions||project.dimensions:null;el('Dimensions').textContent=dims?'固定畫布 '+dims.join(' × ')+' px · '+project.clips.length+' 個表情':'每個表情須使用相同畫布；播放 FPS 可不同。';renderAlignment();renderTone();renderSequence();renderLayout();renderClipControls();renderSeams();renderWorkflow()}
 function sourceLabel(source){return source.label+' · '+source.frames+' 幀 · '+fps(source.fps).toFixed(2).replace(/\.00$/,'')+' FPS · '+source.dimensions.join('×')}
 function fillSelect(select,items,selected,emptyText){select.replaceChildren();for(const item of items){const option=document.createElement('option');option.value=item.value;option.textContent=item.label;option.disabled=false;select.append(option)}if(!items.length){const option=document.createElement('option');option.value='';option.textContent=emptyText;select.append(option)}select.value=items.some(item=>item.value===selected)?selected:items[0]?.value||''}
 function renderSources(previousSource=null){const index=previousSource?catalog.findIndex(s=>s.job_id===previousSource.job_id&&s.version===previousSource.version):-1,previous=index>=0?String(index):el('Source').value;fillSelect(el('Source'),catalog.map((source,index)=>({value:String(index),label:sourceLabel(source)})),previous,'尚無完成去背的素材');el('Source').disabled=!catalog.length;renderProjectState()}
 function renderProjectList(){const items=[{value:'',label:'選擇表情組'},...projectList.map(p=>({value:p.id,label:(p.id===project?.id?project.name:p.name)+' · '+(p.id===project?.id?project.clips.length:p.clip_count)+' 個表情'+(p.id===project?.id&&dirty?'（草稿）':'')}))],signature=JSON.stringify([items,project?.id]);if(signature===projectListSignature)return;projectListSignature=signature;fillSelect(el('ProjectSelect'),items,project?.id||'','尚無表情組')}
 let catalogEpoch=0;
 async function refreshCatalog(){
  const epoch=++catalogEpoch,old=catalog,selectedSource=old[Number(el('Source').value)];
  try{
   const result=await call('catalog');if(epoch!==catalogEpoch)return;
   catalog=(result.sources||[]).filter(s=>Number(s.frames)>=2&&Array.isArray(s.dimensions));renderSources(selectedSource);
   if(!project)return;
   const changed=(project.clips||[]).filter(c=>{const before=old.find(s=>s.job_id===c.job_id&&s.version===c.version),after=sourceOf(c);return !after||!before||before.revision!==after.revision});
   clearPreview();releaseOutput();compareEpoch++;comparison=null;drawComparison();clearTimeout(compareTimer);
   if(changed.length){
    pushHistory();const keys=new Set(changed.map(c=>c.key));
    for(const clip of project.clips)for(const side of ['head','tail']){const alignment=clip[side]?.alignment,p=alignment?.model?.provenance;if(p&&(keys.has(p.source?.clip_key)||keys.has(p.reference?.clip_key)))alignmentInvalid.set(alignmentKey(alignment),'來源內容已更新，請重新對齊參考幀。')}
    for(const clip of changed){
     const source=sourceOf(clip);if(source){const n=Number(source.frames);clip.start=Math.max(1,Math.min(n-1,clip.start));clip.end=Math.max(clip.start+1,Math.min(n,clip.end));const count=clip.end-clip.start+1,total=clip.head_frames+clip.tail_frames;if(total>count){clip.head_frames=Math.floor(count*clip.head_frames/total);clip.tail_frames=count-clip.head_frames}}
    }
    for(const pair of Object.keys(project.reviews||{}))if(pair.split('>').some(key=>keys.has(key)))delete project.reviews[pair];
    for(const pair of pairResults.keys())if(pair.split('>').some(key=>keys.has(key)))pairResults.delete(pair);
    markDirty();
   }
   renderClips();renderPairs();
   const missing=project.clips.filter(c=>!sourceOf(c));
   if(missing.length)message('找不到來源：'+missing.map(c=>c.label).join('、')+'。請恢復原資料夾，或移除這段後加入新的來源；其餘修整設定已保留。',true);
   else{message(changed.length?'已重新讀取更新後的素材，相關接點需重新確認。':'來源已重新讀取，正在更新比較。');queueCompare()}
   const id=project.id;await reloadVersions(id);
  }catch(error){if(epoch===catalogEpoch)message('無法讀取動畫來源：'+error.message,true)}
 }
 async function refreshProjects(){const result=await call('list');projectList=result.projects||[];renderProjectList()}
 function reviewFor(a,b){const result=pairResults.get(pairKey(a,b)),review=project?.reviews?.[pairKey(a,b)];return review&&result?.signature===review.signature?review:null}
 function renderMatrix(){
  renderSequence();
  const clips=project?.clips||[],signature=JSON.stringify([clips.map(c=>[c.key,c.label]),aKey,bKey,clips.flatMap(a=>clips.map(b=>{const result=pairResults.get(pairKey(a.key,b.key));return [result?.signature,reviewFor(a.key,b.key)?.verdict]}))]);if(signature===matrixSignature)return;matrixSignature=signature;
  const box=el('Matrix');box.replaceChildren();if(!clips.length)return;const table=document.createElement('table'),head=document.createElement('tr'),corner=document.createElement('th');corner.textContent='A ↓ / B →';head.append(corner);for(const clip of clips){const th=document.createElement('th');th.textContent=clip.label;th.title=clip.label;th.scope='col';head.append(th)}const thead=document.createElement('thead');thead.append(head);table.append(thead);const body=document.createElement('tbody');
  for(const a of clips){const row=document.createElement('tr'),th=document.createElement('th');th.textContent=a.label;th.title=a.label;th.scope='row';row.append(th);for(const b of clips){const td=document.createElement('td'),button=document.createElement('button'),review=reviewFor(a.key,b.key),result=pairResults.get(pairKey(a.key,b.key));button.textContent=review?.verdict==='pass'?'✓':review?.verdict==='needs_work'?'!':'○';button.dataset.verdict=review?.verdict||'unchecked';button.setAttribute('aria-pressed',String(a.key===aKey&&b.key===bKey));button.setAttribute('aria-label',a.label+' 尾段到 '+b.label+' 頭段，'+(review?.verdict==='pass'?'已確認':review?.verdict==='needs_work'?'需修整':'待確認'));button.title=a.label+' → '+b.label+(result?' · '+metricText(result.metrics):' · 尚未分析');button.onclick=()=>selectPair(a.key,b.key);td.append(button);row.append(td)}body.append(row)}table.append(body);box.append(table)
 }
 function renderPairs(){const clips=project?.clips||[],items=clips.map(c=>({value:c.key,label:c.label}));if(!clips.some(c=>c.key===aKey))aKey=clips[0]?.key||'';if(!clips.some(c=>c.key===bKey))bKey=clips[1]?.key||clips[0]?.key||'';fillSelect(el('A'),items,aKey,'先加入動畫');fillSelect(el('B'),items,bKey,'先加入動畫');el('A').disabled=el('B').disabled=!clips.length;renderEditor();renderMatrix();renderReview();renderSeams()}
 function renderClipControls(){const clips=project?.clips||[],sequence=routeKeys(clips,project?.sequence),ordinary=fullRoute(clips,sequence),busy=operation||toneBusy||seamBusy||loadingProject;for(const row of el('ClipList').children){const index=sequence.indexOf(row.dataset.key);for(const button of row.querySelectorAll('button')){const delta=Number(button.dataset.move);button.disabled=busy||(button.dataset.move!==undefined&&(!ordinary||index<0||index+delta<0||index+delta>=sequence.length))}}}
 function renderClips(){
  el('ClipList').replaceChildren();const clips=project?.clips||[],sequence=routeKeys(clips,project?.sequence),ordinary=fullRoute(clips,sequence),ordered=[...new Set([...sequence,...clips.map(c=>c.key)])].map(key=>clips.find(c=>c.key===key));
  for(const [index,clip]of ordered.entries()){
   const row=document.createElement('div');row.className='tr-clip-row';row.dataset.key=clip.key;const number=document.createElement('span');number.className='tr-clip-number';number.textContent=ordinary?String(index+1):'•';
   const name=document.createElement('input');name.value=clip.label;name.maxLength=80;name.setAttribute('aria-label','表情名稱：'+clip.label);let renameSnapshot=null;
   name.onfocus=()=>renameSnapshot=clone(project);name.oninput=()=>{const current=project?.clips.find(c=>c.key===clip.key),value=name.value.trim();if(!current||!value||value===current.label)return;if(renameSnapshot){pushHistory(renameSnapshot);renameSnapshot=null}else if(document.activeElement!==name)pushHistory();current.label=value;markDirty();renderPairs();renderTone()};name.onblur=()=>{const current=project?.clips.find(c=>c.key===clip.key);if(current)name.value=current.label;renameSnapshot=null};
   const actions=document.createElement('div');actions.className='tr-clip-actions';
   for(const[delta,label]of [[-1,'↑'],[1,'↓']]){const button=document.createElement('button');button.className='quiet';button.textContent=label;button.dataset.move=String(delta);button.setAttribute('aria-label',(delta<0?'上移 ':'下移 ')+clip.label);button.disabled=!ordinary||index+delta<0||index+delta>=clips.length||operation||toneBusy||seamBusy;button.onclick=()=>moveClip(clip.key,delta);actions.append(button)}
   const remove=document.createElement('button');remove.className='quiet';remove.textContent='移除';remove.disabled=operation||toneBusy||seamBusy;remove.setAttribute('aria-label','從方案移除 '+clip.label);remove.onclick=()=>{pushHistory();invalidateClip(clip.key);project.clips=project.clips.filter(c=>c.key!==clip.key);project.sequence=routeKeys(clips,project.sequence).filter(k=>k!==clip.key);if(project.tone_match){delete project.tone_match;toneNotice='來源已移除，請重新校準整組明暗。'}markDirty();renderClips();renderPairs();queueCompare()};actions.append(remove);
   const detail=document.createElement('small'),source=sourceOf(clip);detail.textContent=source?source.frames+' 幀 · '+source.dimensions.join(' × ')+' · '+fps(source.fps).toFixed(2).replace(/\.00$/,'')+' FPS':'來源暫時無法讀取';detail.title=source?sourceLabel(source):'來源 '+clip.job_id+' · '+clip.version;row.append(number,name,actions,detail);el('ClipList').append(row)
  }renderProjectState();renderSequence()
 }
 function alignmentKey(alignment){return JSON.stringify(alignment?.model||{})}
 function alignmentReason(clip,side){const a=clip?.[side]?.alignment;if(!a?.model)return '';const p=a.model.provenance;if(!p?.source||!p.reference)return '此對位缺少來源資訊，請重新計算。';const cached=alignmentInvalid.get(alignmentKey(a));if(cached)return cached;if(p.scope!=='transition'||p.source.job_id!==clip.job_id||p.source.version!==clip.version||p.source.clip_key!==clip.key||p.source.side!==side||p.source.frame!==(side==='head'?clip.start:clip.end))return '修整端的來源或首尾幀已變更，請重新對齊。';const ref=project?.clips.find(c=>c.key===p.reference.clip_key);if(!ref||ref.job_id!==p.reference.job_id||ref.version!==p.reference.version||p.reference.frame!==(p.reference.side==='head'?ref.start:ref.end))return '計算時參考的來源或端點已變更，請重新對齊。';return ''}
 function alignmentActive(clip=currentClip(),side=el('EditSide').value){return !!clip?.[side]?.alignment?.enabled&&!alignmentReason(clip,side)}
 function assertAlignmentSources(){for(const clip of project?.clips||[])for(const side of ['head','tail']){const reason=alignmentReason(clip,side);if(clip[side]?.alignment?.enabled&&reason)throw Error(clip.label+' '+(side==='head'?'頭段':'尾段')+'：'+reason+' 請重新計算或清除對位，再儲存／輸出。')}}
 function alignmentReportText(report){
  if(!report)return '';const out=[],before=report.before||{},after=report.after||{};
  const distance=(a,b)=>{if(!Array.isArray(a)||!Array.isArray(b)||!a.length||a.length!==b.length)return null;let max=0;for(let i=0;i<a.length;i++){if(!Array.isArray(a[i])||!Array.isArray(b[i])||a[i].length!==2||b[i].length!==2)return null;for(let j=0;j<2;j++){if(!Number.isFinite(a[i][j])||!Number.isFinite(b[i][j]))return null;max=Math.max(max,Math.abs(a[i][j]-b[i][j]))}}return max};
  for(const[key,label,unit]of [['silhouette_mismatch_pixels','輪廓差異','像素'],['linework_symmetric_distance_px','線條距離','px']])if(Number.isFinite(before[key])&&Number.isFinite(after[key]))out.push(label+'：'+before[key].toFixed(key==='silhouette_mismatch_pixels'?0:2)+' → '+after[key].toFixed(key==='silhouette_mismatch_pixels'?0:2)+' '+unit);
  for(const[key,label]of [['left','左'],['right','右']]){const b=report.boundaries?.[key];if(!b)continue;const source=b.source_intervals,target=b.target_intervals,candidate=b.candidate_intervals;if([source,target,candidate].every(x=>Array.isArray(x)&&x.length===0)){out.push(label+'側：未接觸畫布邊緣');continue}const initial=distance(source,target),result=distance(candidate,target);out.push(initial!==null&&result!==null?label+'貼邊偏差：'+initial.toFixed(2)+' → '+result.toFixed(2)+' px':label+'側：輪廓對應不足，請檢查')}
  for(const warning of Array.isArray(report.warnings)?report.warnings:[])if(typeof warning==='string')out.push('⚠ '+warning);return out.join('\n')||'已完成量測；請以放大預覽確認細節。';
 }
 function renderAlignment(){const clip=currentClip(),side=el('EditSide').value,a=clip?.[side]?.alignment,active=alignmentActive(clip,side),reason=alignmentReason(clip,side),key=[project?.id,clip?.key,side].join(':'),reference=project?.clips.find(c=>c.key===(side==='tail'?bKey:aKey)),report=a?alignmentReports.get(alignmentKey(a)):null;el('Align').disabled=!clip||!reference||!sourceOf(clip)||!sourceOf(reference)||loadingProject||alignmentBusy||exportStatus.state==='running';el('Align').textContent=alignmentBusy?'正在計算局部對位…':a?'重新對齊參考幀':'自動對齊參考幀';el('AlignDirection').textContent=clip&&reference?(side==='tail'?'A 尾幀 '+clip.end+' → B 首幀 '+reference.start:'B 首幀 '+clip.start+' → A 尾幀 '+reference.end):'先選擇 A／B 動畫';el('AlignEnabled').checked=active;el('AlignEnabled').disabled=!a||!!reason||alignmentBusy;el('AlignStrength').disabled=!a||!!reason||alignmentBusy;if(document.activeElement!==el('AlignStrength'))el('AlignStrength').value=a?.strength??100;el('AlignStrengthValue').textContent=(a?.strength??100)+'%';el('AlignClear').disabled=!a||alignmentBusy;const saved=a?.model?.provenance?.reference,oldReference=saved&&reference&&saved.clip_key!==reference.key?'此端保留計算時參考的對位；重新對齊會改用目前配對。':'';el('AlignStatus').textContent=alignmentBusy?'正在計算目前提交的修整端；請稍候。':reason||(alignmentOwner===key&&alignmentError?alignmentNotice:'')||oldReference||(alignmentOwner===key?alignmentNotice:'')||(!a?'選擇要修整的一端，再自動對齊另一端。':active?'局部對位已啟用；依計算時參考修整此端。':'局部對位已停用，保留方案供再次啟用。');el('AlignStatus').dataset.error=String(!alignmentBusy&&(!!reason||alignmentOwner===key&&alignmentError));el('AlignReport').textContent=report?(active&&Number(a.strength)===100&&!oldReference?'計算候選量測（100% 強度）\n'+alignmentReportText(report):!active?'局部對位未啟用；100% 候選量測不代表目前畫面。':oldReference?'目前比較參考與計算時不同；原候選量測不代表目前配對。':'目前修正強度 '+Number(a.strength)+'%；100% 候選量測不適用目前設定，請以更新後畫面為準。'):'';if(project?.seam_closure?.enabled)el('AlignReport').textContent='共用接點已啟用；局部對位的候選量測不是最終接點結果。請看更新後的實際比較與成品接點驗證。';if(comparison?.valid&&comparison.a===aKey&&comparison.b===bKey&&a?.enabled)el('AlignReport').textContent+='\n目前實際配對：'+metricText(comparison.metrics)+'（越低越接近，非合格保證）';el('ManualNotice').hidden=!active;el('ManualTransform').disabled=active;el('ResetTransform').disabled=!clip||active;if(active){el('TransformDetails').open=false;regionEditor?.deactivate(false)}}
 function renderEditor(){const clip=currentClip(),side=el('EditSide').value;el('EditLabel').textContent=clip?'正在調整：'+clip.label+' 的'+(side==='tail'?'結尾':'開頭'):'先選擇要比較的動畫';for(const[suffix,key]of Object.entries(numeric)){el(suffix).disabled=!clip;if(clip&&document.activeElement!==el(suffix))el(suffix).value=clip[key]??0}for(const[suffix,key]of Object.entries(transformFields)){el(suffix).disabled=!clip;if(clip&&document.activeElement!==el(suffix))el(suffix).value=clip[side]?.[key]??identity()[key]}el('ResetTransform').disabled=!clip;const n=clip?sourceOf(clip)?.frames||clip.end:2;el('Start').max=Math.max(1,n-1);el('End').max=n;const length=clip?clip.end-clip.start+1:2;el('HeadFrames').max=Math.max(0,length-(clip?.tail_frames||0));el('TailFrames').max=Math.max(0,length-(clip?.head_frames||0));regionEditor?.sync();renderAlignment();renderSeams();renderAdvancedSummary()}
 function normalizeClipRange(clip,key){const before=JSON.stringify([clip.start,clip.end,clip.head_frames,clip.tail_frames]),n=sourceOf(clip)?.frames||clip.end;if(key==='start')clip.start=Math.max(1,Math.min(clip.end-1,n-1,Math.round(clip.start)));if(key==='end')clip.end=Math.max(clip.start+1,Math.min(n,Math.round(clip.end)));const count=clip.end-clip.start+1,total=clip.head_frames+clip.tail_frames;if(total>count){clip.head_frames=Math.floor(count*clip.head_frames/total);clip.tail_frames=count-clip.head_frames}if(before!==JSON.stringify([clip.start,clip.end,clip.head_frames,clip.tail_frames])){invalidateClip(clip.key);markDirty();message('已將保留範圍與兩端漸進幀數限制在有效區間內。');queueCompare()}}
 function invalidateClip(key){compareEpoch++;clearPreview();if(comparison)comparison.valid=false;for(const[pair]of pairResults)if(pair.split('>').includes(key))pairResults.delete(pair);renderMatrix();renderReview()}
 function selectPair(a,b){regionEditor?.deactivate(false);aKey=a;bKey=b;clearPreview();compareEpoch++;if(comparison)comparison.valid=false;renderPairs();rememberDraft();drawComparison();queueCompare()}
 function setMode(next){mode=next;el('CheckArea').hidden=next!=='check';el('OutputArea').hidden=next!=='output';el('CheckMode').setAttribute('aria-pressed',String(next==='check'));el('OutputMode').setAttribute('aria-pressed',String(next==='output'));stopPreview();pauseOutput();requestAnimationFrame(()=>{drawComparison();drawOutput()})}
 function normalizeProject(value){const p=clone(value);p.clips=p.clips||[];p.reviews=p.reviews||{};p.sequence=routeKeys(p.clips,p.sequence);p.shared_tone=p.shared_tone||{tone:0,contrast:0};for(const c of p.clips){c.head={...identity(),...c.head};c.tail={...identity(),...c.tail};c.tone=c.tone||0;c.contrast=c.contrast||0}return p}
 async function loadProject(id){if(!id)return;rememberDraft();const epoch=++loadEpoch;loadingProject=true;toneEpoch++;toneBusy=false;toneNotice='';seamEpoch++;seamBusy=false;seamNotice='';seamServerError='';seamServerErrorKey='';seamReferences={};clearPreview();releaseOutput();versions=[];renderVersions();compareEpoch++;comparison=null;drawComparison();pairResults.clear();matrixSignature='';clearTimeout(compareTimer);operation=true;renderProjectState();message('正在載入表情組…');try{const result=await call('load',{project_id:id});if(epoch!==loadEpoch)return;releaseOutput();clearPreview();project=normalizeProject(result.project);seamReferences=Object.fromEntries((project.seam_closure?.links||[]).map(l=>[pairKey(l.a,l.b),l.reference]));seamServerError=project.seam_closure&&result.source_error||'';seamServerErrorKey=seamModelKey();rememberSeamSnapshot();versions=result.versions||[];dirty=false;history=[];revision=0;aKey=bKey='';let restored=false;try{const local=JSON.parse(localStorage.getItem(draftPrefix+id)||'null');if(local?.dirty&&local.project?.id===id&&Array.isArray(local.project.clips)){project=normalizeProject(local.project);seamReferences=local.seamReferences||Object.fromEntries((project.seam_closure?.links||[]).map(l=>[pairKey(l.a,l.b),l.reference]));if(local.seamSnapshot&&project.seam_closure)seamSnapshots.set(seamModelKey(),local.seamSnapshot);dirty=true;aKey=local.aKey||'';bKey=local.bKey||'';restored=true}}catch{}exportStatus={};renderProjectList();renderClips();renderPairs();renderVersions();pollStatus();queueCompare();message(result.source_error|| (restored?'已還原這個表情組尚未儲存的草稿。':'選擇 A 尾段與 B 頭段，逐一確認需要的方向。'),!!result.source_error)}catch(error){if(epoch===loadEpoch)message(error.message,true)}finally{if(epoch===loadEpoch){loadingProject=false;operation=false;renderVersions();renderProjectState();notify();queueCompare()}}}
 async function saveProject(silent=false){if(!project)return null;assertAlignmentSources();assertSeamsReady();const id=project.id,rev=revision,submitted=clone(project),result=await call('save',{project:submitted}),saved=result.project||result;assertFeatureRoundTrip(submitted,saved);if(project?.id!==id)return saved;if(rev===revision){project=normalizeProject(saved);dirty=false;rememberDraft();renderClips();renderPairs();renderProjectState();notify()}if(!silent)message(rev===revision?'表情組方案已儲存。':'已儲存提交時的方案；新的變更仍保留在草稿。');return saved}
 function metricText(metrics){if(!metrics)return '尚無分析';const number=x=>Number.isFinite(Number(x))?Number(x).toFixed(3):'—';return '輪廓 '+number(metrics.silhouette)+' · 外觀 '+number(metrics.appearance)+' · 動作 '+number(metrics.motion)}
 function renderReview(){renderCompareStatus();const result=pairResults.get(pairKey()),review=reviewFor(aKey,bKey),raw=project?.reviews?.[pairKey()],valid=!!comparison?.valid&&comparison.a===aKey&&comparison.b===bKey;el('Pass').disabled=!valid||!!comparison?.clipped;el('NeedsWork').disabled=!valid;el('ReviewState').textContent=review?.verdict==='pass'?'✓ 已人工確認':review?.verdict==='needs_work'?'! 需修整':raw?'設定已變更，需重新確認':result?'等待人工確認':'尚未檢查';if(document.activeElement!==el('ReviewNote'))el('ReviewNote').value=raw?.note||'';el('Metrics').textContent=result?metricText(result.metrics)+'（僅供比較，不代表已合格）':'外觀差異只是輔助；動作是否自然仍需播放確認。'}
 function setReview(verdict){if(!project||!comparison?.valid||comparison.a!==aKey||comparison.b!==bKey)return;if(verdict==='pass'&&comparison.clipped)return;pushHistory();project.reviews[pairKey()]={signature:comparison.signature,verdict,note:el('ReviewNote').value.trim()};markDirty();renderMatrix();renderReview()}
 const loadImage=url=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('預覽圖片無法讀取'));image.src=url});
 function queueCompare(){clearTimeout(compareTimer);if(comparison&&!comparison.valid){compareState='pending';compareFailure='';renderCompareStatus()}if(!inView()||mode!=='check')return;compareTimer=setTimeout(compare,400)}
 async function compare(){clearTimeout(compareTimer);if(loadingProject)return;if(!project||!aKey||!bKey){comparison=null;drawComparison();return}stopPreview();const epoch=++compareEpoch,id=project.id,a=aKey,b=bKey,snapshot=clone(project);compareState='updating';compareFailure='';if(comparison)comparison.valid=false;renderReview();message('正在更新比較，保留上一張畫面…');try{const result=await call('compare',{project:snapshot,a,b});if(epoch!==compareEpoch||id!==project?.id)return;const [left,right]=await Promise.all([loadImage(result.left),loadImage(result.right)]);if(epoch!==compareEpoch||id!==project?.id)return;const sourceA=snapshot.clips.find(c=>c.key===a),sourceB=snapshot.clips.find(c=>c.key===b);compareState='fresh';compareFailure='';comparison={...result,left,right,a,b,valid:true,leftLabel:'A · '+sourceA.label+' · 尾幀 '+sourceA.end,rightLabel:'B · '+sourceB.label+' · 首幀 '+sourceB.start};pairResults.set(pairKey(a,b),{metrics:result.metrics,signature:result.signature});renderMatrix();renderReview();renderAlignment();drawComparison();message(result.clipped?'修整後可能超出固定畫布，請減少位移／縮放；尚不能確認為可用。':'完整解析度比對 · 左為 A 尾幀，右為 B 首幀。',!!result.clipped)}catch(error){if(epoch===compareEpoch){compareState='error';compareFailure=error.message;renderCompareStatus();message(error.message,true)}}}
 function drawComparison(single=null){
  regionEditor?.sync();renderCompareStatus();
  const canvas=el('CompareCanvas'),view=el('CompareViewport'),ctx=canvas.getContext('2d'),left=single||comparison?.left,right=single?null:comparison?.right;
  if(!left){canvas.width=canvas.height=1;el('CompareEmpty').textContent=project?.clips.length?'正在準備銜接比較；若未出現畫面，請按「更新比對」。':'加入已完成去背的動畫，開始檢查表情之間的銜接。';el('CompareEmpty').hidden=false;el('LeftLabel').textContent='左 · A 尾幀';el('RightLabel').textContent='右 · B 首幀';return}el('CompareEmpty').hidden=true;
  const w=left.naturalWidth||left.width,h=left.naturalHeight||left.height;renderLayout([w,h]);view.style.maxWidth=panel.dataset.layout==='portrait'&&el('Zoom').value==='fit'?Math.max(250,view.clientHeight*w/h)+'px':'';canvas.width=w;canvas.height=h;const scale=el('Zoom').value==='fit'?Math.min(view.clientWidth/w,view.clientHeight/h):Number(el('Zoom').value);canvas.style.width=Math.max(1,w*scale)+'px';canvas.style.height=Math.max(1,h*scale)+'px';el('LeftLabel').parentElement.style.width=Math.min(view.clientWidth,Math.max(340,w*scale))+'px';el('CompareLegend').textContent=el('CompareMode').value==='contour'?'紅色：A 多出的透明輪廓 · 青色：B 多出的透明輪廓 · 淺灰：重疊；只檢查透明外框，不代表內部線條相同。':el('CompareMode').value==='onion'?'半透明疊圖會混合 A／B；邊緣可能看似接近，請搭配輪廓差異或拖曳比對。':el('CompareMode').value==='diff'?'差異 ×4：顯示圖像內容差異；越亮表示差異越大。':'拖曳分隔線：左為 A 尾幀，右為 B 首幀。';ctx.fillStyle=el('Backdrop').value;ctx.fillRect(0,0,w,h);view.style.backgroundColor=el('Backdrop').value;
  if(single){ctx.drawImage(single,0,0,w,h);return}el('LeftLabel').textContent=comparison.leftLabel||'左 · A 尾幀';el('RightLabel').textContent=comparison.rightLabel||'右 · B 首幀';
  if(el('CompareMode').value==='contour')drawContour(ctx,left,right,w,h);
  else if(el('CompareMode').value==='onion'){ctx.drawImage(left,0,0,w,h);ctx.globalAlpha=.5;ctx.drawImage(right,0,0,w,h);ctx.globalAlpha=1}
  else if(el('CompareMode').value==='diff'){const temp=document.createElement('canvas');temp.width=w;temp.height=h;const tc=temp.getContext('2d',{willReadFrequently:true});tc.drawImage(left,0,0);const l=tc.getImageData(0,0,w,h);tc.clearRect(0,0,w,h);tc.drawImage(right,0,0,w,h);const r=tc.getImageData(0,0,w,h),out=ctx.createImageData(w,h);for(let i=0;i<out.data.length;i+=4){const la=l.data[i+3]/255,ra=r.data[i+3]/255;for(let c=0;c<3;c++)out.data[i+c]=Math.min(255,Math.abs(l.data[i+c]*la-r.data[i+c]*ra)*4);out.data[i+3]=255}ctx.putImageData(out,0,0)}
  else{const split=w*Number(el('Split').value)/100;ctx.drawImage(right,0,0,w,h);ctx.save();ctx.beginPath();ctx.rect(0,0,split,h);ctx.clip();ctx.drawImage(left,0,0,w,h);ctx.restore();ctx.strokeStyle='#ffffff';ctx.lineWidth=Math.max(1,2/Math.max(.01,scale));ctx.beginPath();ctx.moveTo(split,0);ctx.lineTo(split,h);ctx.stroke()}
  regionEditor?.draw(ctx,w,h);
 }
 function stopPreview(){previewRunning=false;previewEpoch++;clearTimeout(previewTimer);el('StopPreview').disabled=true}
 function previewIdentity(){if(!project||!aKey||!bKey)return '';return JSON.stringify({project:project.id,a:aKey,b:bKey,shared_tone:project.shared_tone,tone_match:project.tone_match,seam_closure:project.seam_closure,clips:[aKey,bKey].map(key=>{const clip=project.clips.find(c=>c.key===key);return clip?{...clip,label:undefined}:null})})}
 function previewBelongs(){return !!previewOwner&&!loadingProject&&previewOwner===previewIdentity()}
 function clearPreview(){stopPreview();previewFrames=[];previewIndex=0;previewOwner=null;el('ReplayPreview').disabled=true;el('StopPreview').disabled=true}
 function playPreview(){if(!previewBelongs()){clearPreview();drawComparison();return}if(!previewFrames.length||!inView()||mode!=='check')return;pauseOutput();stopPreview();previewRunning=true;el('StopPreview').disabled=false;const epoch=previewEpoch;function next(){if(!previewRunning||epoch!==previewEpoch||!inView())return;if(!previewBelongs()){clearPreview();drawComparison();return}const item=previewFrames[previewIndex];drawComparison(item.decoded);el('LeftLabel').textContent=item.label||('第 '+item.frame+' 幀');el('RightLabel').textContent='草稿短播 · 預覽長邊 ≤ 720 px';previewIndex=(previewIndex+1)%previewFrames.length;previewTimer=setTimeout(next,Math.max(1,item.duration_ms||1000/24)/Number(el('PreviewSpeed').value))}next()}
 async function preparePreview(){if(!project||!aKey||!bKey||loadingProject)return;clearPreview();const epoch=++previewEpoch,id=project.id,a=aKey,b=bKey,rev=revision,owner=previewIdentity();message('正在準備 A 尾段 → B 頭段短播…');el('PreparePreview').disabled=true;try{const result=await call('render_preview',{project:clone(project),a,b,span:Math.max(1,Math.min(12,Number(el('Span').value)||6))});if(epoch!==previewEpoch||id!==project?.id||rev!==revision)return;const decoded=await Promise.all(result.frames.map(async item=>({...item,decoded:await loadImage(item.image)})));if(epoch!==previewEpoch||id!==project?.id||rev!==revision)return;previewFrames=decoded;previewIndex=0;previewOwner=owner;el('ReplayPreview').disabled=!decoded.length;message('草稿接縫短播：長邊限制 720 px。輸出仍維持原始畫布。');playPreview()}catch(error){if(epoch===previewEpoch)message(error.message,true)}finally{if(id===project?.id)renderProjectState()}}

 function renderVersions(){const old=el('Version').value,items=completeVersions();fillSelect(el('Version'),items.map(v=>({value:versionName(v),label:versionName(v)+' · '+v.clips.length+' 個表情'})),old||versionName(items.at(-1)),'尚無已完成版本');el('Version').disabled=loadingProject||!items.length;el('LoadOutput').disabled=loadingProject||!items.length||outputLoading;el('OpenVersion').disabled=loadingProject||!items.length;renderWorkflow()}
 function transitionFile(id,path){return '/transition-file/'+encodeURIComponent(id)+'/'+String(path).split('/').map(encodeURIComponent).join('/')}
 function framePath(pattern,index){if(!/%(?:0\d+)?d/.test(pattern))throw Error('輸出版本的 PNG 圖序格式無效');return pattern.replace(/%(?:0(\d+))?d/,(_,width)=>String(index).padStart(Number(width)||0,'0'))}
 function disposeCache(cache){for(const images of cache.values())for(const image of images||[])image?.close?.();cache.clear()}
 function pauseOutput(){outputRunning=false;cancelAnimationFrame(outputRAF);outputRAF=0;outputClock=0;el('OutputPlay').textContent='播放／暫停'}
 function releaseOutput(){pauseOutput();outputEpoch++;outputAbort?.abort();outputAbort=null;disposeCache(outputCache);if(pendingOutputCache){disposeCache(pendingOutputCache);pendingOutputCache=null}outputClips=[];outputSequence=[];outputSequenceIndex=0;outputSeamVerification=null;outputReadyVersion='';outputKey=queuedKey='';outputFrame=0;outputLoading=false;el('OutputPlay').disabled=el('OutputRestart').disabled=true;el('LoadProgress').hidden=true;el('EmotionButtons').replaceChildren();el('Now').textContent='目前：—';el('Queued').textContent='待切換：—';el('OutputEmpty').hidden=false;el('OutputCanvas').width=el('OutputCanvas').height=1;el('OutputCanvas').style.width=el('OutputCanvas').style.height='';el('OutputViewport').style.maxWidth='';el('OutputEmpty').textContent='選擇已輸出版本，載入完整 PNG 圖序後再播放。';el('OutputInfo').textContent='播放的是已輸出 PNG；請選擇版本並載入成品檢查。';el('OutputInfo').dataset.warning='false';el('OutputSequence').textContent='';el('SkipSeam').checked=false;renderOutputSeams()}
 function selectedOutput(){return completeVersions().find(v=>versionName(v)===el('Version').value)}
 async function preloadOutput(){
  const version=selectedOutput();if(loadingProject||!project||!version)return;releaseOutput();const projectEpoch=loadEpoch,id=project.id,name=versionName(version),clips=version.clips.map(c=>({...c,frames:Number(c.frames),fps:fps(c.fps)}));let bytes=0,total=0;
  for(const clip of clips){const [w,h]=clip.dimensions||[];if(!Number.isInteger(clip.frames)||clip.frames<1||!w||!h||!clip.png_pattern){message('輸出版本缺少有效的 PNG 規格。',true);return}bytes+=w*h*4*clip.frames;total+=clip.frames}
  if(typeof createImageBitmap!=='function'){message('目前瀏覽器不支援 PNG 縮小解碼預載，請使用支援 createImageBitmap 的桌面瀏覽器。',true);return}
  const originalLong=Math.max(...clips[0].dimensions),scale=Math.min(1,720/originalLong,Math.sqrt(memoryLimit/bytes)*.98),previewLong=Math.floor(originalLong*scale);
  if(previewLong<Math.min(256,originalLong)){el('OutputInfo').dataset.warning='true';el('OutputInfo').textContent='這組圖序在 384 MiB 預載預算內會縮到低於 256 px 長邊。請減少每段幀數，或分成較小表情組後輸出。';message('圖序過長，請分組檢查以維持可辨識的預覽尺寸。',true);return}
  bytes=0;for(const clip of clips){clip.preview_dimensions=clip.dimensions.map(n=>Math.max(1,Math.floor(n*scale)));bytes+=clip.preview_dimensions[0]*clip.preview_dimensions[1]*4*clip.frames}
  const epoch=++outputEpoch,controller=new AbortController(),cache=new Map(clips.map(c=>[c.key,new Array(c.frames)])),tasks=[];pendingOutputCache=cache;outputAbort=controller;outputLoading=true;renderVersions();el('LoadProgress').hidden=false;el('LoadProgress').max=total;el('LoadProgress').value=0;el('OutputEmpty').textContent='正在預載輸出 PNG，完成後才會開始播放…';el('OutputInfo').dataset.warning='false';let cursor=0,done=0;
  for(const clip of clips)for(let index=1;index<=clip.frames;index++)tasks.push({clip,index});
  async function worker(){while(cursor<tasks.length){if(epoch!==outputEpoch||projectEpoch!==loadEpoch||controller.signal.aborted)return;const task=tasks[cursor++],response=await fetch(transitionFile(id,framePath(task.clip.png_pattern,task.index)),{signal:controller.signal});if(!response.ok)throw Error('無法讀取 '+task.clip.label+' 第 '+task.index+' 幀');const blob=await response.blob();if(epoch!==outputEpoch||projectEpoch!==loadEpoch)return;const [width,height]=task.clip.preview_dimensions,image=await createImageBitmap(blob,{resizeWidth:width,resizeHeight:height,resizeQuality:'high'});if(epoch!==outputEpoch||projectEpoch!==loadEpoch||controller.signal.aborted){image.close();return}if(image.width!==width||image.height!==height){image.close();throw Error('瀏覽器未依要求縮小 PNG 解碼，已停止預載')}cache.get(task.clip.key)[task.index-1]=image;done++;el('LoadProgress').value=done;el('OutputInfo').textContent='預載 '+done+' / '+total+' 幀 · 約 '+Math.ceil(bytes/1024/1024)+' MiB 解碼像素'}}
  try{const results=await Promise.allSettled(Array.from({length:Math.min(4,tasks.length)},()=>worker().catch(error=>{controller.abort();throw error})));const failed=results.find(result=>result.status==='rejected');if(epoch!==outputEpoch||projectEpoch!==loadEpoch||project?.id!==id){disposeCache(cache);return}if(failed)throw failed.reason;outputCache=cache;pendingOutputCache=null;outputClips=clips;outputSeamVerification=version.seam_verification?clone(version.seam_verification):null;outputSequence=routeKeys(clips,version.sequence);outputSequenceIndex=0;outputReadyVersion=name;outputKey=outputSequence[0];el('OutputSequence').textContent='成品順序：'+routeText(clips,outputSequence);outputFrame=0;outputElapsed=0;el('OutputEmpty').hidden=true;el('LoadProgress').hidden=true;el('OutputPlay').disabled=el('OutputRestart').disabled=false;el('OutputInfo').textContent='成品 PNG '+name+' · 預覽 '+clips[0].preview_dimensions.join(' × ')+' · 輸出仍 '+clips[0].dimensions.join(' × ')+' · '+total+' 幀／各段原 FPS';renderEmotionButtons();renderOutputSeams();renderWorkflow();drawOutput();message('整組成品 PNG 已縮小解碼預載（不修改輸出）。輸出原尺寸保持不變；成品細節可開啟資料夾查看 PNG。');startOutput()}catch(error){disposeCache(cache);if(epoch===outputEpoch){el('OutputEmpty').textContent='成品載入失敗，請重新載入。';message(error.message,true)}}finally{if(epoch===outputEpoch){outputLoading=false;outputAbort=null;el('LoadProgress').hidden=true;renderVersions()}}
 }
 function renderEmotionButtons(){el('EmotionButtons').replaceChildren();for(const clip of [...new Set([...outputSequence,...outputClips.map(c=>c.key)])].map(key=>outputClips.find(c=>c.key===key))){const button=document.createElement('button');button.textContent=(outputSequence.indexOf(clip.key)>=0?(outputSequence.indexOf(clip.key)+1)+'. ':'')+clip.label;button.dataset.key=clip.key;button.onclick=()=>{if(outputRunning){queuedKey=clip.key}else{outputKey=clip.key;outputSequenceIndex=Math.max(0,outputSequence.indexOf(clip.key));outputFrame=0;outputElapsed=0;queuedKey='';drawOutput()}updatePlaybackLabels()};el('EmotionButtons').append(button)}updatePlaybackLabels()}
 function verifiedSkipPair(a,b){if(!outputSeamVerification?.enabled)return false;const row=outputSeamVerification.pairs?.find(p=>p.a===a&&p.b===b),from=outputClips.find(c=>c.key===a),to=outputClips.find(c=>c.key===b);return !!(row?.endpoints_equal===true&&row.same_fps===true&&row.can_skip_duplicate_head===true&&from&&to&&to.frames>1&&Math.abs(fps(from.fps)-fps(to.fps))<1e-9)}
 function renderOutputSeams(){const report=outputSeamVerification,rows=report?.enabled&&Array.isArray(report.pairs)?report.pairs:[],box=el('OutputSeamRows');box.replaceChildren();el('OutputSeamReport').hidden=!rows.length;const names=new Map(outputClips.map(c=>[c.key,c.label]));for(const pair of rows){const row=document.createElement('p');row.dataset.equal=String(pair.endpoints_equal===true);row.textContent=(names.get(pair.a)||pair.a)+' → '+(names.get(pair.b)||pair.b)+'：'+(pair.endpoints_equal===true?'端點完全相同':'端點仍有差異')+' · 差異像素 '+(pair.changed_pixels??'—')+' · 最大通道差 '+(pair.max_channel_error??'—');box.append(row)}el('OutputSeamSummary').textContent='成品接點：'+rows.filter(p=>p.endpoints_equal===true).length+' / '+rows.length+' 完全相同（動作仍需播放確認）';const eligible=outputSequence.reduce((n,a,i)=>n+(verifiedSkipPair(a,outputSequence[(i+1)%outputSequence.length])?1:0),0);el('SkipSeam').disabled=!eligible;if(!eligible)el('SkipSeam').checked=false;el('SkipSeamHint').textContent=eligible?'此成品有 '+eligible+' 個已驗證且 FPS 相同的接點。勾選後順序循環每圈少播 '+eligible+' 幀；原始輸出檔保留全部幀。':'僅限成品已驗證相同且 FPS 相同的相鄰接點；目前沒有可跳過的接點。'}
 function updatePlaybackLabels(){const current=outputClips.find(c=>c.key===outputKey),next=outputClips.find(c=>c.key===queuedKey);el('Now').textContent=current?'目前：'+current.label+' · '+(outputFrame+1)+' / '+current.frames+' 幀':'目前：—';el('Queued').textContent=next?'待切換：'+next.label:el('Random').checked?'待切換：片段結束時隨機':el('PlaybackMode').value==='sequence'?'下一段：'+(outputClips.find(c=>c.key===nextOutputKey())?.label||'—')+'（順序循環）':'待切換：目前表情循環';for(const button of el('EmotionButtons').children){button.setAttribute('aria-pressed',String(button.dataset.key===outputKey));button.dataset.queued=String(button.dataset.key===queuedKey)}}
 function drawOutput(){const clip=outputClips.find(c=>c.key===outputKey),image=outputCache.get(outputKey)?.[outputFrame];if(!clip||!image)return;const canvas=el('OutputCanvas'),ctx=canvas.getContext('2d'),view=el('OutputViewport'),[w,h]=clip.preview_dimensions||clip.dimensions;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}renderLayout(clip.dimensions);view.style.maxWidth=panel.dataset.layout==='portrait'?Math.max(250,view.clientHeight*w/h)+'px':'';const scale=Math.min(view.clientWidth/w,view.clientHeight/h);canvas.style.width=Math.max(1,w*scale)+'px';canvas.style.height=Math.max(1,h*scale)+'px';ctx.fillStyle=el('Backdrop').value;ctx.fillRect(0,0,w,h);ctx.drawImage(image,0,0,w,h);view.style.backgroundColor=el('Backdrop').value;updatePlaybackLabels()}
 function nextOutputKey(){return outputSequence.length?outputSequence[(outputSequenceIndex+1)%outputSequence.length]:outputKey}
 function advanceOutput(){const clip=outputClips.find(c=>c.key===outputKey);if(!clip)return;outputFrame++;if(outputFrame<clip.frames)return;outputFrame=0;if(queuedKey){outputKey=queuedKey;queuedKey='';outputSequenceIndex=Math.max(0,outputSequence.indexOf(outputKey))}else if(el('Random').checked&&outputClips.length>1){const choices=outputClips.filter(c=>c.key!==outputKey);outputKey=choices[Math.floor(Math.random()*choices.length)].key;outputSequenceIndex=Math.max(0,outputSequence.indexOf(outputKey))}else if(el('PlaybackMode').value==='sequence'&&outputSequence.length){const previous=outputKey;outputSequenceIndex=(outputSequenceIndex+1)%outputSequence.length;outputKey=outputSequence[outputSequenceIndex];if(el('SkipSeam').checked&&verifiedSkipPair(previous,outputKey))outputFrame=1}}
 function outputTick(timestamp){if(!outputRunning||!inView()||mode!=='output')return;if(outputClock)outputElapsed+=Math.min(100,timestamp-outputClock)*Number(el('OutputSpeed').value);outputClock=timestamp;let count=0,changed=false;while(outputElapsed>=1000/outputClips.find(c=>c.key===outputKey).fps&&count++<120){outputElapsed-=1000/outputClips.find(c=>c.key===outputKey).fps;advanceOutput();changed=true}if(changed)drawOutput();outputRAF=requestAnimationFrame(outputTick)}
 function startOutput(){if(!outputClips.length||!inView()||mode!=='output')return;pauseOutput();outputRunning=true;outputClock=0;el('OutputPlay').textContent='暫停';outputRAF=requestAnimationFrame(outputTick)}
 function statusText(status){let text=status.phase||'';const p=status.progress;if(p){text+=(text?' · ':'')+(p.done||0)+' / '+(p.total||'?');if(p.remaining!=null)text+=' · 此階段約剩 '+Math.max(1,Math.ceil(p.remaining))+' 秒'}return text}
 function applyExportStatus(status){const previous=exportStatus.state;exportStatus=status||{};if(status.state==='complete'&&previous!=='complete')message('整組 '+(status.version||'')+' 已輸出完成。按「載入成品」檢查實際結果。');if(status.state==='error'&&previous!=='error')message('整組輸出失敗：'+status.phase,true);el('ExportState').textContent=status.state==='complete'?'✓ 輸出完成。到左側載入這個成品版本。':statusText(status)||(project?.clips.length>=2?'可另存整組成品。':'至少加入兩個動畫。');el('ExportState').dataset.error=String(status.state==='error');el('ExportProgress').hidden=status.state!=='running';el('ExportProgress').max=status.progress?.total||project?.clips.length||1;el('ExportProgress').value=status.progress?.done||status.done||0;renderProjectState();notify()}
 async function reloadVersions(id){const result=await call('load',{project_id:id});if(project?.id!==id)return;versions=result.versions||[];renderVersions()}
 async function pollStatus(){clearTimeout(statusTimer);if(!project)return;const id=project.id;statusProject=id;try{const status=await call('status',{project_id:id});if(project?.id!==id||statusProject!==id)return;const previous=exportStatus.state;applyExportStatus(status);if(status.state==='complete'&&previous!=='complete')await reloadVersions(id);if(status.state==='running')statusTimer=setTimeout(pollStatus,1800)}catch(error){if(project?.id===id)message('無法讀取輸出進度：'+error.message,true)}}

 el('CheckMode').onclick=()=>setWorkflowStep('seams');el('OutputMode').onclick=()=>setWorkflowStep('output');
 for(const button of panel.querySelectorAll('[data-tr-step]'))button.onclick=()=>setWorkflowStep(button.dataset.trStep);
 el('StepBack').onclick=()=>{const i=workflowSteps.findIndex(s=>s.key===workflowStep);if(i>0)setWorkflowStep(workflowSteps[i-1].key)};
 el('StepNext').onclick=()=>{const i=workflowSteps.findIndex(s=>s.key===workflowStep);if(i<workflowSteps.length-1)setWorkflowStep(workflowSteps[i+1].key)};
 el('AppliedAdvanced').onclick=()=>{setWorkflowStep('seams',{focus:false});el('AdvancedSettings').open=true;el('AdvancedSettings').scrollIntoView({block:'start',behavior:'smooth'});el('AdvancedSettings').querySelector('summary')?.focus({preventScroll:true})};
 el('AdvancedSettings').addEventListener('toggle',()=>{if(!el('AdvancedSettings').open){regionEditor?.deactivate(false);drawComparison()}});
 el('StageAction').onclick=()=>{if(!project){setWorkflowStep('sources',{focus:false});el('ProjectManage').open=true;el('NewName').focus();return}if(project.clips.length<2){setWorkflowStep('sources',{focus:false});if(!catalog.length){refreshCatalog();return}el('Source').focus();return}if(workflowStep==='output'){if(completeVersions().length)preloadOutput();else el('Export').onclick()}};
 window.workbenchTransitionStep=key=>setWorkflowStep(key);
 el('ProjectSelect').onchange=()=>loadProject(el('ProjectSelect').value);el('RefreshSources').onclick=refreshCatalog;
 el('Create').onclick=async()=>{const name=el('NewName').value.trim();if(!name){el('NewName').focus();message('請先輸入表情組名稱。');return}el('Create').disabled=true;try{const result=await call('create',{name});const created=result.project||result;el('NewName').value='';await refreshProjects();await loadProject(created.id)}catch(error){message(error.message,true)}finally{el('Create').disabled=false}};
 el('Save').onclick=async()=>{if(!project||operation||toneBusy||seamBusy||loadingProject)return;try{operation=true;renderProjectState();await saveProject();await refreshProjects()}catch(error){message(error.message,true)}finally{operation=false;renderProjectState()}};
 document.addEventListener('keydown',event=>{if(!inView()||!(event.ctrlKey||event.metaKey)||event.altKey||String(event.key).toLowerCase()!=='s')return;event.preventDefault();if(!el('Save').disabled)el('Save').onclick()});
 el('Layout').onchange=()=>{renderLayout();drawComparison();drawOutput()};
 el('ResetSequence').onclick=()=>{if(!project||operation||toneBusy||seamBusy)return;pushHistory();project.sequence=project.clips.map(c=>c.key);project.sequence_version=2;markDirty();renderClips();message('草稿已改為每段一次的完整循環；既有成品版本順序保持原樣。')};
 el('BuildSeams').onclick=async()=>{
  if(!project||operation||toneBusy||seamBusy||loadingProject)return;const route=routeKeys(project.clips,project.sequence),reason=project.clips.length<2?'至少加入兩段動畫。':!fullRoute(project.clips,route)?'請先使用每段一次的完整固定循環。':seamWindowReason();if(reason){seamNotice=reason;message(reason,true);el('SeamClosureStatus').textContent=reason;el('SeamClosureStatus').dataset.error='true';return}
  const id=project.id,rev=revision,epoch=loadEpoch,token=++seamEpoch,snapshot=clone(project),references=seamReferenceValues();seamBusy=true;seamNotice='';renderProjectState();
  try{const result=await call('build_seams',{project:snapshot,references});if(token!==seamEpoch||id!==project?.id||epoch!==loadEpoch)return;if(rev!==revision||JSON.stringify(references)!==JSON.stringify(seamReferenceValues())){seamNotice='建立期間設定已變更，未套用舊基準；請確認草稿後重新建立。';message(seamNotice,true);return}const built=result.project,closure=built?.seam_closure;if(!closure?.enabled||closure.schema!==1||!closure.binding||!Array.isArray(closure.links)||closure.links.length!==route.length||sequencePairs(snapshot).some(({a,b})=>!closure.links.some(l=>l.a===a&&l.b===b&&l.anchor_id&&l.sha256&&l.reference===references[pairKey(a,b)])))throw Error('服務未回傳完整的共用接點基準，尚未套用。');pushHistory();project=normalizeProject(built);seamReferences=Object.fromEntries(closure.links.map(l=>[pairKey(l.a,l.b),l.reference]));seamServerError='';seamServerErrorKey='';rememberSeamSnapshot();invalidateAll();markDirty();renderClips();renderEditor();message('已建立全部共用接點，包含最後一段 → 第一段。請用 0.1× 短播檢查雙邊過渡，再另存輸出驗證端點。')}
  catch(error){if(token===seamEpoch&&id===project?.id){seamNotice='共用接點未建立：'+error.message;message(seamNotice,true)}}finally{if(token===seamEpoch){seamBusy=false;renderProjectState();renderClips();if(seamNotice){el('SeamClosureStatus').textContent=seamNotice;el('SeamClosureStatus').dataset.error='true'}}}
 };
 el('SeamEnabled').onchange=()=>{if(!project?.seam_closure||seamBusy||operation)return;const enabled=el('SeamEnabled').checked;if(enabled){const reason=seamWindowReason()||seamStaleReason();if(reason){el('SeamEnabled').checked=false;message(reason,true);renderSeams();return}}pushHistory();project.seam_closure.enabled=enabled;invalidateAll();markDirty();renderEditor()};
 el('ClearSeams').onclick=()=>{if(!project?.seam_closure||seamBusy||operation)return;pushHistory();delete project.seam_closure;seamServerError='';seamServerErrorKey='';seamNotice='已清除共用接點，恢復原本各段修整。';invalidateAll();markDirty();renderEditor()};
 el('SeamSlowPlay').onclick=()=>{el('PreviewSpeed').value='0.1';setWorkflowStep('seams',{focus:false});preparePreview()};
 el('MatchTone').onclick=async()=>{
  if(!project||project.clips.length<2||toneBusy||seamBusy||operation)return;const id=project.id,rev=revision,epoch=loadEpoch,token=++toneEpoch,snapshot=clone(project),reference=el('ToneReference').value;toneBusy=true;toneNotice='';renderProjectState();
  try{const result=await call('match_tone',{project:snapshot,reference});if(token!==toneEpoch||id!==project?.id||epoch!==loadEpoch)return;if(rev!==revision||reference!==el('ToneReference').value){toneNotice='分析期間設定已變更，舊校準結果未套用，請重新校準。';message(toneNotice,true);return}if(!result.project?.tone_match?.enabled||!result.project.tone_match.adjustments)throw Error('服務未回傳完整的整組校準方案，尚未套用。');pushHistory();project=normalizeProject(result.project);toneNotice='';invalidateAll();markDirty();renderClips();renderEditor();message('整組明暗校準已套用至草稿；可按「復原」回到調整前。請接播檢查後另存輸出。')}
  catch(error){if(token===toneEpoch&&id===project?.id){toneNotice='校準未完成：'+error.message;message(toneNotice,true)}}finally{if(token===toneEpoch){toneBusy=false;renderProjectState();renderClips()}}
 };
 el('ClearToneMatch').onclick=()=>{if(!project?.tone_match||toneBusy||seamBusy||operation)return;pushHistory();delete project.tone_match;toneNotice='已清除自動校準；各段原有微調與整組微調仍保留。';invalidateAll();markDirty();renderTone()};
 el('ResetGroupTone').onclick=()=>{if(!project||toneBusy||seamBusy||operation)return;pushHistory();project.shared_tone={tone:0,contrast:0};invalidateAll();markDirty();renderTone()};
 for(const[suffix,key]of [['GroupTone','tone'],['GroupContrast','contrast']]){const input=el(suffix);input.onfocus=()=>toneSnapshot=project?clone(project):null;input.oninput=()=>{if(!project||toneBusy||seamBusy||operation||input.value===''||!Number.isFinite(Number(input.value)))return;if(toneSnapshot){pushHistory(toneSnapshot);toneSnapshot=null}else if(document.activeElement!==input)pushHistory();project.shared_tone=project.shared_tone||{tone:0,contrast:0};project.shared_tone[key]=Math.max(Number(input.min),Math.min(Number(input.max),Number(input.value)));invalidateAll();markDirty()};input.onchange=()=>{toneSnapshot=null;renderTone()};input.onblur=()=>toneSnapshot=null}
 el('AddSource').onclick=()=>{const source=catalog[Number(el('Source').value)];if(!project||!source)return;const first=project.clips[0]&&sourceOf(project.clips[0]);if(first&&first.dimensions.join(',')!==source.dimensions.join(',')){message('畫布不同：目前表情組 '+first.dimensions.join(' × ')+'，此來源 '+source.dimensions.join(' × ')+'。請使用相同解析度的素材。',true);return}pushHistory();const n=Number(source.frames),key=crypto.randomUUID().replace(/-/g,'');project.clips.push({key,label:source.label,job_id:source.job_id,version:source.version,start:1,end:n,head_frames:Math.min(12,Math.floor(n/2)),tail_frames:Math.min(12,Math.floor(n/2)),tone:0,contrast:0,head:identity(),tail:identity()});project.sequence.push(key);if(project.tone_match){delete project.tone_match;toneNotice='新增了來源，請重新校準整組明暗。'}clearPreview();if(!aKey)aKey=key;bKey=key;markDirty();renderClips();renderPairs();queueCompare()};
 el('Undo').onclick=()=>{if(!history.length||operation||toneBusy||seamBusy)return;toneNotice='';project=history.pop();seamReferences=seamHistoryReferences.get(project)||Object.fromEntries((project.seam_closure?.links||[]).map(l=>[pairKey(l.a,l.b),l.reference]));seamNotice='';compareEpoch++;comparison=null;pairResults.clear();clearPreview();drawComparison();markDirty();renderClips();renderPairs();queueCompare()};
 el('A').onchange=()=>selectPair(el('A').value,bKey);el('B').onchange=()=>selectPair(aKey,el('B').value);el('Swap').onclick=()=>selectPair(bKey,aKey);el('Compare').onclick=compare;el('EditSide').onchange=()=>{regionEditor?.deactivate(false);renderEditor();drawComparison()};
 for(const[suffix,key]of Object.entries({...numeric,...transformFields})){const input=el(suffix);input.addEventListener('focus',()=>focusedSnapshot=project?clone(project):null);input.addEventListener('input',()=>{const clip=currentClip();if(!clip||input.value===''||!Number.isFinite(Number(input.value)))return;if(focusedSnapshot){pushHistory(focusedSnapshot);focusedSnapshot=null}const target=transformFields[suffix]?clip[el('EditSide').value]:clip;target[key]=Number(input.value);if(['tone','contrast','start','end'].includes(key)&&project.tone_match?.enabled){toneNotice='單段明暗或範圍已變更；請重新校準整組，或清除自動校準後繼續。';renderTone()}invalidateClip(clip.key);markDirty();queueCompare()});input.addEventListener('change',()=>{if(input.value===''){renderEditor();return}const min=Number(input.min),max=Number(input.max),value=Math.min(Number.isFinite(max)&&input.max!==''?max:Infinity,Math.max(Number.isFinite(min)&&input.min!==''?min:-Infinity,Number(input.value)));if(value!==Number(input.value)){input.value=value;input.dispatchEvent(new Event('input'))}const clip=currentClip();if(clip&&numeric[suffix]){normalizeClipRange(clip,key);input.value=clip[key]}renderEditor()})}
 el('Align').onclick=async()=>{const clip=currentClip();if(!project||!clip||alignmentBusy)return;const id=project.id,projectEpoch=loadEpoch,rev=revision,side=el('EditSide').value,key=clip.key,a=aKey,b=bKey,snapshot=clone(project),token=++alignmentEpoch;alignmentBusy=true;alignmentOwner=[id,key,side].join(':');alignmentNotice='';alignmentError=false;renderAlignment();try{const result=await call('align',{project:snapshot,a,b,side});if(token!==alignmentEpoch||project?.id!==id||projectEpoch!==loadEpoch)return;if(rev!==revision||a!==aKey||b!==bKey||side!==el('EditSide').value){alignmentNotice='計算期間設定或檢查位置已變更，未套用舊結果。請重新對齊。';alignmentError=true;return}if(!result.alignment?.model)throw Error('服務未回傳完整對位方案，請重新計算。');const target=project.clips.find(c=>c.key===key);if(!target)return;pushHistory();target[side].alignment=clone(result.alignment);alignmentInvalid.delete(alignmentKey(target[side].alignment));if(result.report)alignmentReports.set(alignmentKey(target[side].alignment),clone(result.report));invalidateClip(key);markDirty();renderEditor();queueCompare();alignmentNotice='局部對位已套用，正在更新此端的比較結果。'}catch(error){if(token===alignmentEpoch&&project?.id===id){alignmentNotice=error.message;alignmentError=true}}finally{if(token===alignmentEpoch){alignmentBusy=false;renderAlignment()}}};
 el('AlignEnabled').onchange=()=>{const clip=currentClip(),side=el('EditSide').value,a=clip?.[side]?.alignment;if(!a||alignmentBusy||alignmentReason(clip,side)){renderAlignment();return}pushHistory();a.enabled=el('AlignEnabled').checked;alignmentNotice='';alignmentError=false;invalidateClip(clip.key);markDirty();renderEditor();queueCompare()};
 el('AlignStrength').onfocus=()=>alignmentStrengthSnapshot=project?clone(project):null;el('AlignStrength').oninput=()=>{const clip=currentClip(),side=el('EditSide').value,a=clip?.[side]?.alignment;if(!a||alignmentBusy||alignmentReason(clip,side))return;if(alignmentStrengthSnapshot){pushHistory(alignmentStrengthSnapshot);alignmentStrengthSnapshot=null}a.strength=Math.max(0,Math.min(100,Number(el('AlignStrength').value)||0));invalidateClip(clip.key);markDirty();renderEditor();queueCompare()};el('AlignStrength').onchange=el('AlignStrength').onblur=()=>alignmentStrengthSnapshot=null;
 el('AlignClear').onclick=()=>{const clip=currentClip(),side=el('EditSide').value;if(!clip?.[side]?.alignment||alignmentBusy)return;pushHistory();delete clip[side].alignment;alignmentOwner=[project.id,clip.key,side].join(':');alignmentNotice='已清除對位，恢復原本手動變形設定。';alignmentError=false;invalidateClip(clip.key);markDirty();renderEditor();queueCompare()};
 el('ResetTransform').onclick=()=>{const clip=currentClip();if(!clip)return;pushHistory();const side=el('EditSide').value,region=clone(clip[side]?.region||null),alignment=clone(clip[side]?.alignment||null);if(region?.outside)region.outside=identity();clip[side]={...identity(),...(region?{region}:{}),...(alignment?{alignment}:{})};invalidateClip(clip.key);markDirty();renderEditor();queueCompare()};
 el('Pass').onclick=()=>setReview('pass');el('NeedsWork').onclick=()=>setReview('needs_work');el('ReviewNote').onchange=()=>{const review=project?.reviews?.[pairKey()];if(!review)return;pushHistory();review.note=el('ReviewNote').value.trim();markDirty()};
 async function analyzeDirections(scope){if(!project||analyzing||operation||toneBusy||seamBusy)return;const id=project.id,rev=revision,snapshot=clone(project);analyzing=true;renderProjectState();message(scope==='sequence'?'正在分析循環相鄰接點（含最後 → 第一段）…':'正在分析所有有向銜接…');try{const result=await call('analyze',{project:snapshot,scope});if(id!==project?.id||revision!==rev){message('分析期間設定已變更，舊分析未套用；請重新分析。');return}for(const pair of result.pairs||[])pairResults.set(pairKey(pair.a,pair.b),pair);renderMatrix();renderReview();message('已更新 '+(result.pairs||[]).length+' 個接點。分析不會自動標示合格。')}catch(error){if(project?.id===id)message(error.message,true)}finally{analyzing=false;renderProjectState()}}
 el('Analyze').onclick=()=>analyzeDirections('all');el('AnalyzeSequence').onclick=()=>analyzeDirections('sequence');
 el('PreparePreview').onclick=preparePreview;el('ReplayPreview').onclick=()=>{previewIndex=0;playPreview()};el('StopPreview').onclick=()=>{stopPreview();drawComparison()};
 for(const suffix of ['CompareMode','Zoom','Backdrop'])el(suffix).onchange=()=>{stopPreview();drawComparison();drawOutput()};el('Split').oninput=()=>{stopPreview();drawComparison()};
 let dragSplit=false;function moveSplit(event){const rect=el('CompareCanvas').getBoundingClientRect();el('Split').value=Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100));drawComparison()}
 el('CompareCanvas').onpointerdown=event=>{if(el('CompareMode').value!=='wipe'||!comparison)return;stopPreview();dragSplit=true;el('CompareCanvas').setPointerCapture(event.pointerId);moveSplit(event)};el('CompareCanvas').onpointermove=event=>{if(dragSplit)moveSplit(event)};el('CompareCanvas').onpointerup=el('CompareCanvas').onpointercancel=()=>dragSplit=false;
 el('Version').onchange=()=>{releaseOutput();el('OutputInfo').textContent='版本已切換，請重新載入這個版本的輸出 PNG。';renderVersions()};el('LoadOutput').onclick=preloadOutput;el('OpenVersion').onclick=async()=>{if(loadingProject||!project||!el('Version').value)return;try{await call('open',{project_id:project.id,version:el('Version').value})}catch(error){message(error.message,true)}};
 el('OutputPlay').onclick=()=>outputRunning?pauseOutput():startOutput();el('OutputRestart').onclick=()=>{outputKey=outputSequence[0]||outputKey;outputSequenceIndex=0;queuedKey='';outputFrame=0;outputElapsed=0;outputClock=0;drawOutput();startOutput()};el('Random').onchange=updatePlaybackLabels;el('PlaybackMode').onchange=updatePlaybackLabels;el('SkipSeam').onchange=()=>{renderOutputSeams();updatePlaybackLabels()};
 el('Export').onclick=async()=>{if(!project||project.clips.length<2||exportStatus.state==='running'||toneBusy||seamBusy||operation)return;const id=project.id,rev=revision;operation=true;renderProjectState();try{const saved=await saveProject(true);if(project?.id!==id)return;if(rev!==revision)throw Error('儲存期間設定已變更，尚未開始輸出；請確認最新草稿後再按輸出。');const status=await call('export',{project:saved});if(project?.id!==id)return;applyExportStatus(status);message('整組正在另存輸出，原始來源不會被覆寫。');pollStatus()}catch(error){if(project?.id===id)message(error.message,true)}finally{operation=false;renderProjectState()}};
 window.transitionsShow=async()=>{renderWorkflow();notify();if(!initialized){initialized=true;try{await Promise.all([refreshCatalog(),refreshProjects()]);if(!project&&projectList.length)await loadProject(projectList[0].id)}catch(error){initialized=false;message(error.message,true)}}else{drawComparison();drawOutput();if(project&&mode==='check'&&!comparison?.valid)queueCompare();if(project)pollStatus()}};
 window.addEventListener('workbench:tab',event=>{if(event.detail.id!=='tabTransitions'){regionEditor?.deactivate(false);clearTimeout(compareTimer);stopPreview();pauseOutput()}else requestAnimationFrame(()=>{renderWorkflow();drawComparison();drawOutput();if(project&&mode==='check'&&!comparison?.valid)queueCompare()})});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPreview();pauseOutput()}});window.addEventListener('pagehide',()=>{rememberDraft();stopPreview();pauseOutput();outputAbort?.abort()});
 new ResizeObserver(()=>{if(inView()){if(!previewRunning)drawComparison();drawOutput()}}).observe(el('CompareViewport'));new ResizeObserver(()=>{if(inView())drawOutput()}).observe(el('OutputViewport'));
 if(window.RegionEditor&&el('RegionControls'))regionEditor=new RegionEditor({
  container:el('RegionControls'),outsideContainer:el('OutsideControls'),canvas:el('CompareCanvas'),prefix:'trRegion',
  getContext:()=>[project?.id,currentClip()?.key,el('EditSide').value,currentClip()?.start,currentClip()?.end].join(':'),getValue:()=>currentClip()?.[el('EditSide').value]?.region,
  getTransform:()=>currentClip()?.[el('EditSide').value],
  getLegacy:()=>'此端沿用整體變形。框選範圍只影響目前選擇的 A 尾段或 B 頭段。',
  isReady:()=>!loadingProject&&!alignmentActive()&&mode==='check'&&!previewRunning&&!!currentClip()&&!!comparison?.left&&comparison.a===aKey&&comparison.b===bKey,
  onBegin:()=>pushHistory(),onActivate:()=>{stopPreview();drawComparison()},
  onChange:(r,transform)=>{const clip=currentClip();if(!clip)return;const target=clip[el('EditSide').value],enteringScoped=['split','edge'].includes(r.mode)&&target.region?.mode!==r.mode;if(transform)Object.assign(target,transform);target.region=r;if(enteringScoped)el('TransformDetails').open=true;invalidateClip(clip.key);markDirty();renderEditor();queueCompare()},
  onSync:r=>{el('TransformHeading').textContent=r?.mode==='edge'?'中間修整（向所選邊緣漸退）':r?.mode==='split'?'框內變形':r?.mode==='inside'?'框內變形（框外不變）':r?.mode==='outside'?'框外變形（框內不變）':'位移、縮放與旋轉';el('ResetTransform').textContent=r?.mode==='split'?'重設這一端的框內與框外':'重設這一端'},onDraw:()=>drawComparison()
 });
 renderProjectState();renderPairs();renderVersions();
})();
